// CANDIDATE 0605 critical-region rectangles in 144-DPI reference pixels.
//
// GENERATED by visual/tools/generate-region-table.spec.ts from this form's own
// rendered DOM, then REVIEWED BY HAND. Regeneration is a starting point, not an
// authority: names are lifted from the form's own headings and may be wrong or
// unhelpful, nested wrappers may still produce near-duplicate rows, and the
// rectangles describe OUR render rather than the official page.
//
// Because these are measured from our own output they are valid for ATTRIBUTION
// (telling a reader which part of the form a diff landed in) and invalid as
// calibration evidence (they can never argue that our geometry matches the
// official form - only the pinned references and the geometry contract can).

export interface CriticalRegion {
  name: string;
  selector: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export const PAGE_ONE_CRITICAL_REGIONS: readonly CriticalRegion[] = [
  { name: "Payment Form", selector: ".masthead-0605", x: 25, y: 83, width: 1137, height: 137 },
  { name: "Fill in all applicable spaces. Mark all appropriate boxes wi", selector: ".fill-instruction-0605", x: 25, y: 223, width: 1137, height: 43 },
  { name: "1►For theCalendarXFiscal2►Year Ended (MM / YYYY)0620263►Quar", selector: ".header-fields-0605", x: 25, y: 269, width: 1137, height: 152 },
  { name: "1►For theCalendarXFiscal2►Year Ended (MM / YYYY)062026", selector: ".period-block-0605", x: 28, y: 272, width: 308, height: 72 },
  { name: "3►Quarter1stX2nd3rd4th", selector: ".quarter-block-0605", x: 336, y: 272, width: 240, height: 72 },
  { name: "4►Due Date ( MM / DD / YYYY)07152026", selector: ".header-value-0605:nth-of-type(1)", x: 576, y: 272, width: 255, height: 72 },
  { name: "5►No. of SheetsAttached02", selector: ".header-value-0605:nth-of-type(2)", x: 831, y: 272, width: 165, height: 72 },
  { name: "07152026", selector: "div", x: 608, y: 298, width: 218, height: 40 },
  { name: "II011", selector: "div", x: 1028, y: 298, width: 125, height: 40 },
  { name: "062026", selector: ".guided-field-0605:nth-of-type(1)", x: 162, y: 300, width: 173, height: 46 },
  { name: "2026", selector: ".guided-segment-0605:nth-of-type(2)", x: 220, y: 301, width: 113, height: 43 },
  { name: "7►Return Period ( MM / DD / YYYY)06302026", selector: ".header-value-0605:nth-of-type(4)", x: 28, y: 344, width: 308, height: 72 },
  { name: "8►Tax Type CodeIT", selector: ".header-value-0605:nth-of-type(5)", x: 336, y: 344, width: 240, height: 72 },
  { name: "BCS No./Item No. (To be filled up by the BIR)", selector: ".bcs-item-0605", x: 576, y: 344, width: 581, height: 72 },
  { name: "06302026", selector: "div", x: 80, y: 372, width: 251, height: 40 },
  { name: "2026", selector: ".guided-segment-0605:nth-of-type(9)", x: 205, y: 373, width: 124, height: 37 },
  { name: "region at 249", selector: "i", x: 638, y: 374, width: 513, height: 40 },
  { name: "Part IBackground Information", selector: ".part-one-0605", x: 25, y: 425, width: 1137, height: 436 },
  { name: "Part IBackground Information", selector: "h2", x: 28, y: 428, width: 1131, height: 38 },
  { name: "9►Taxpayer Identification No.1234567890000010►RDO Code01811►", selector: ".identity-row-0605", x: 28, y: 466, width: 1131, height: 72 },
  { name: "9►Taxpayer Identification No.12345678900000", selector: ".header-value-0605:nth-of-type(6)", x: 28, y: 466, width: 423, height: 71 },
  { name: "10►RDO Code018", selector: ".header-value-0605:nth-of-type(7)", x: 451, y: 466, width: 125, height: 71 },
  { name: "11►Taxpayer ClassificationXIN", selector: ".classification-0605", x: 576, y: 466, width: 228, height: 71 },
  { name: "SOFTWARE DEVELOPMENT", selector: "div", x: 836, y: 483, width: 317, height: 40 },
  { name: "12345678900000", selector: "div", x: 60, y: 491, width: 388, height: 40 },
  { name: "13►Taxpayer's NameJUAN DELA CRUZ(Last Name, First Name, Midd", selector: ".name-phone-0605", x: 28, y: 538, width: 1131, height: 76 },
  { name: "13►Taxpayer's NameJUAN DELA CRUZ(Last Name, First Name, Midd", selector: "div", x: 28, y: 538, width: 890, height: 73 },
  { name: "JUAN DELA CRUZ", selector: ".plain-field-shell-0605:nth-of-type(4)", x: 184, y: 542, width: 720, height: 40 },
  { name: "09123456789", selector: "div", x: 944, y: 557, width: 207, height: 40 },
  { name: "15►Registered Address53 SANTOL EXTENSION, NEW CABALAN, OLONG", selector: ".address-zip-0605", x: 28, y: 614, width: 1131, height: 50 },
  { name: "15►Registered Address53 SANTOL EXTENSION, NEW CABALAN, OLONG", selector: "div", x: 28, y: 614, width: 890, height: 48 },
  { name: "2200", selector: "div", x: 1032, y: 616, width: 119, height: 40 },
  { name: "53 SANTOL EXTENSION, NEW CABALAN, OLONGAPO CITY", selector: ".plain-field-shell-0605:nth-of-type(6)", x: 172, y: 618, width: 744, height: 40 },
  { name: "► 17 Manner of Payment► 18 Type of Payment", selector: ".payment-choice-head-0605", x: 28, y: 664, width: 1131, height: 38 },
  { name: "► 17 Manner of Payment", selector: "span", x: 28, y: 664, width: 890, height: 36 },
  { name: "Voluntary Payment", selector: ".manner-0605", x: 28, y: 702, width: 890, height: 154 },
  { name: "region at 543", selector: ".plain-field-shell-0605:nth-of-type(7)", x: 220, y: 814, width: 315, height: 38 },
  { name: "Part II► Computation of Tax", selector: ".part-two-0605", x: 25, y: 864, width: 1137, height: 203 },
  { name: "Part II► Computation of Tax", selector: "h2", x: 28, y: 867, width: 1131, height: 40 },
  { name: "125000•00", selector: ".money-0605:nth-of-type(1)", x: 807, y: 907, width: 346, height: 43 },
  { name: "2500•00", selector: ".money-0605:nth-of-type(2)", x: 96, y: 969, width: 216, height: 42 },
  { name: "750•00", selector: ".money-0605:nth-of-type(3)", x: 340, y: 969, width: 214, height: 42 },
  { name: "1000•00", selector: ".money-0605:nth-of-type(4)", x: 586, y: 969, width: 190, height: 42 },
  { name: "4250•00", selector: ".money-0605:nth-of-type(5)", x: 808, y: 969, width: 345, height: 42 },
  { name: "129250•00", selector: ".money-0605:nth-of-type(6)", x: 807, y: 1018, width: 346, height: 42 },
  { name: "For Voluntary Payment", selector: ".declaration-0605", x: 25, y: 1070, width: 1137, height: 258 },
  { name: "For Voluntary Payment", selector: ".voluntary-signature-0605", x: 28, y: 1073, width: 684, height: 252 },
  { name: "For Payment of Deficiency TaxesFrom Audit/Investigation/Deli", selector: ".deficiency-signature-0605", x: 712, y: 1073, width: 311, height: 252 },
  { name: "JUAN DELA CRUZ", selector: ".plain-field-shell-0605:nth-of-type(9)", x: 60, y: 1265, width: 405, height: 28 },
  { name: "OWNER", selector: ".plain-field-shell-0605:nth-of-type(10)", x: 493, y: 1265, width: 203, height: 28 },
  { name: "region at 844", selector: ".plain-field-shell-0605:nth-of-type(11)", x: 728, y: 1265, width: 285, height: 28 },
  { name: "Part IIIDetails of Payment", selector: ".part-three-0605", x: 25, y: 1324, width: 1137, height: 410 },
  { name: "Part IIIDetails of Payment", selector: "h2", x: 28, y: 1327, width: 1131, height: 36 },
  { name: "ParticularsDrawee Bank/AgencyNumberMMDDYYYYAmount", selector: ".payment-table-head-0605", x: 28, y: 1363, width: 1131, height: 36 },
  { name: "Drawee Bank/Agency", selector: "span", x: 138, y: 1363, width: 211, height: 35 },
  { name: "Number", selector: "span", x: 349, y: 1363, width: 199, height: 35 },
  { name: "129250•00", selector: ".money-0605:nth-of-type(7)", x: 796, y: 1401, width: 357, height: 44 },
  { name: "region at 970", selector: ".plain-field-shell-0605:nth-of-type(12)", x: 150, y: 1456, width: 154, height: 40 },
  { name: "region at 970", selector: ".plain-field-shell-0605:nth-of-type(13)", x: 346, y: 1456, width: 137, height: 40 },
  { name: "region at 970", selector: ".guided-field-0605:nth-of-type(8)", x: 540, y: 1456, width: 215, height: 40 },
  { name: "•", selector: ".money-0605:nth-of-type(8)", x: 796, y: 1456, width: 357, height: 40 },
  { name: "region at 1004", selector: ".plain-field-shell-0605:nth-of-type(14)", x: 346, y: 1506, width: 137, height: 40 },
  { name: "region at 1004", selector: ".guided-field-0605:nth-of-type(9)", x: 540, y: 1506, width: 215, height: 40 },
  { name: "•", selector: ".money-0605:nth-of-type(9)", x: 796, y: 1506, width: 357, height: 40 },
  { name: "region at 1038", selector: ".plain-field-shell-0605:nth-of-type(15)", x: 150, y: 1557, width: 154, height: 40 },
  { name: "region at 1038", selector: ".plain-field-shell-0605:nth-of-type(16)", x: 346, y: 1557, width: 137, height: 40 },
  { name: "region at 1038", selector: ".guided-field-0605:nth-of-type(10)", x: 540, y: 1557, width: 215, height: 40 },
  { name: "•", selector: ".money-0605:nth-of-type(10)", x: 796, y: 1557, width: 357, height: 40 },
  { name: "Machine Validation/Revenue Official Receipt Details (If not", selector: ".machine-validation-0605", x: 28, y: 1601, width: 1131, height: 128 },
  { name: "Machine Validation/Revenue Official Receipt Details (If not", selector: "span", x: 28, y: 1604, width: 1131, height: 26 }
];

export const PAGE_TWO_CRITICAL_REGIONS: readonly CriticalRegion[] = [
  { name: "ATCNATURE OF PAYMENTATCNATURE OF PAYMENTATCNATURE OF PAYMENT", selector: ".atc-table-0605", x: 42, y: 93, width: 1143, height: 439 },
  { name: "NATURE OF PAYMENT", selector: "th", x: 158, y: 95, width: 286, height: 26 },
  { name: "NATURE OF PAYMENT", selector: "th", x: 557, y: 95, width: 286, height: 26 },
  { name: "NATURE OF PAYMENT", selector: "th", x: 957, y: 95, width: 226, height: 26 },
  { name: "Pure Compensation Income", selector: "td", x: 158, y: 121, width: 286, height: 16 },
  { name: "Sweetened Products", selector: ".atc-category-0605:nth-of-type(1)", x: 557, y: 121, width: 286, height: 16 },
  { name: "Pure Business Income", selector: "td", x: 158, y: 137, width: 286, height: 16 },
  { name: "Sweetened Juice Drinks", selector: "td", x: 557, y: 137, width: 286, height: 16 },
  { name: "Mixed (Compensation and Business)", selector: "td", x: 158, y: 153, width: 286, height: 16 },
  { name: "Sweetened Tea", selector: "td", x: 557, y: 153, width: 286, height: 16 },
  { name: "VAT/Non-VAT Registration Fee", selector: "td", x: 158, y: 170, width: 286, height: 16 },
  { name: "Carbonated Beverages", selector: "td", x: 557, y: 170, width: 286, height: 16 },
  { name: "Travel Tax", selector: "td", x: 158, y: 186, width: 286, height: 16 },
  { name: "Flavored Water", selector: "td", x: 557, y: 186, width: 286, height: 16 },
  { name: "Tin Card Fees", selector: "td", x: 158, y: 203, width: 286, height: 16 },
  { name: "Energy and Sports Drinks", selector: "td", x: 557, y: 203, width: 286, height: 16 },
  { name: "Tax Amnesty", selector: "td", x: 158, y: 219, width: 286, height: 16 },
  { name: "Powdered Drinks not Classified as Milk, Juice, Tea and Coffe", selector: ".atc-narrow-0605:nth-of-type(1)", x: 557, y: 219, width: 286, height: 16 },
  { name: "Income from Forfeited Properties", selector: "td", x: 158, y: 235, width: 286, height: 16 },
  { name: "Cereal and Grain Beverages", selector: "td", x: 557, y: 235, width: 286, height: 16 },
  { name: "Proceeds from Sale of Rent Estate", selector: "td", x: 158, y: 252, width: 286, height: 16 },
  { name: "Other Non-Alcoholic Beverages that Contain Added Sugar", selector: ".atc-narrow-0605:nth-of-type(2)", x: 557, y: 252, width: 286, height: 16 },
  { name: "Energy Tax on Electric Power Consumption", selector: "td", x: 158, y: 268, width: 286, height: 16 },
  { name: "Using Purely High Fructose Corn Syrup", selector: "td", x: 557, y: 268, width: 286, height: 16 },
  { name: "Deficiency Tax", selector: "td", x: 158, y: 285, width: 286, height: 16 },
  { name: "Using Purely Coconut Sap Sugar & Purely Steviol Glycosides", selector: ".atc-narrow-0605:nth-of-type(3)", x: 557, y: 285, width: 286, height: 16 },
  { name: "Delinquent Accounts/Accounts Receivable", selector: "td", x: 158, y: 301, width: 286, height: 16 },
  { name: "Invasive Cosmetic Products", selector: ".atc-category-0605:nth-of-type(2)", x: 557, y: 301, width: 286, height: 16 },
  { name: "Fines and Penalties", selector: "td", x: 158, y: 317, width: 286, height: 16 },
  { name: "Performance of Services on Invasive Cosmetic Procedures", selector: ".atc-narrow-0605:nth-of-type(4)", x: 557, y: 317, width: 286, height: 16 },
  { name: "Others", selector: "td", x: 158, y: 334, width: 286, height: 16 },
  { name: "Tobacco Products", selector: ".atc-category-0605:nth-of-type(3)", x: 557, y: 334, width: 286, height: 16 },
  { name: "Miscellaneous Taxes -Other Tax Revenue", selector: "td", x: 158, y: 350, width: 286, height: 16 },
  { name: "Smoking and Chewing Tobacco", selector: "td", x: 557, y: 350, width: 286, height: 16 },
  { name: "Advance Payment on Privilege Store", selector: "td", x: 158, y: 366, width: 286, height: 16 },
  { name: "Cigars", selector: "td", x: 557, y: 366, width: 286, height: 16 },
  { name: "VAT on Manufacturing - Sugar", selector: "td", x: 158, y: 383, width: 286, height: 16 },
  { name: "Cigarettes Packed By Hand", selector: "td", x: 557, y: 383, width: 286, height: 16 },
  { name: "Income Tax on International Carriers", selector: "td", x: 158, y: 399, width: 286, height: 16 },
  { name: "Cigarettes Packed By Machine", selector: "td", x: 557, y: 399, width: 286, height: 16 },
  { name: "Percentage Tax on International Carriers", selector: "td", x: 158, y: 416, width: 286, height: 16 },
  { name: "Tobacco Inspection Fees", selector: ".atc-category-0605:nth-of-type(6)", x: 557, y: 416, width: 286, height: 16 },
  { name: "Documentary Stamp Tax - General", selector: "td", x: 158, y: 432, width: 286, height: 16 },
  { name: "Cigars", selector: "td", x: 557, y: 432, width: 286, height: 16 },
  { name: "Excise Tax on Goods", selector: ".atc-category-0605:nth-of-type(7)", x: 158, y: 448, width: 286, height: 16 },
  { name: "Cigarettes", selector: "td", x: 557, y: 448, width: 286, height: 16 },
  { name: "Alcohol Products", selector: ".atc-category-0605:nth-of-type(8)", x: 158, y: 465, width: 286, height: 16 },
  { name: "Leaf Tobacco & Other Manufactured Tobacco", selector: "td", x: 557, y: 465, width: 286, height: 16 },
  { name: "Distilled Spirits", selector: "td", x: 158, y: 481, width: 286, height: 16 },
  { name: "Monitoring Fees", selector: "td", x: 557, y: 481, width: 286, height: 16 },
  { name: "Wines", selector: "td", x: 158, y: 497, width: 286, height: 16 },
  { name: "Petroleum Products", selector: ".atc-category-0605:nth-of-type(9)", x: 557, y: 497, width: 286, height: 16 },
  { name: "Fermented Liquor", selector: "td", x: 158, y: 514, width: 286, height: 16 },
  { name: "Premium (Leaded) Gasoline", selector: "td", x: 557, y: 514, width: 286, height: 16 },
  { name: "T A X T Y P E", selector: "h2", x: 42, y: 526, width: 1143, height: 23 },
  { name: "CodeDescriptionCodeDescriptionCodeDescriptionRFREGISTRATION", selector: ".tax-type-table-0605", x: 42, y: 549, width: 1143, height: 167 },
  { name: "Description", selector: "th", x: 843, y: 550, width: 340, height: 14 },
  { name: "WITHHOLDING TAX-COMPENSATION", selector: "td", x: 843, y: 564, width: 340, height: 15 },
  { name: "WITHHOLDING TAX-EXPANDED", selector: "td", x: 843, y: 579, width: 340, height: 15 },
  { name: "WITHHOLDING TAX-FINAL", selector: "td", x: 843, y: 594, width: 340, height: 15 },
  { name: "WITHHOLDING TAX - VAT AND OTHER PERCENTAGE TAXES", selector: "td", x: 843, y: 609, width: 340, height: 15 },
  { name: "region at 416", selector: "td", x: 843, y: 624, width: 340, height: 15 },
  { name: "WITHHOLDING TAX-OTHERS (ONE-TIME TRANSACTION NOT SUBJECT TO", selector: "td", x: 843, y: 639, width: 340, height: 15 },
  { name: "region at 436", selector: "td", x: 843, y: 654, width: 340, height: 15 },
  { name: "region at 446", selector: "td", x: 843, y: 669, width: 340, height: 15 },
  { name: "WITHHOLDING TAX - FRINGE BENEFITS", selector: "td", x: 843, y: 684, width: 340, height: 15 },
  { name: "WITHHOLDING TAX - PERCENTAGE TAX ON WINNING AND PRIZES", selector: "td", x: 843, y: 699, width: 340, height: 15 }
];

export function criticalRegionsFor(pageNumber: number): readonly CriticalRegion[] {
  const pages = [PAGE_ONE_CRITICAL_REGIONS, PAGE_TWO_CRITICAL_REGIONS];
  return pages[pageNumber - 1] ?? [];
}
