//! Runtime Snapshot Loader — embeds the compiled JSON snapshot and provides
//! a static, lazily-parsed `CompiledRuleSnapshot` via `OnceLock`.
//!
//! No filesystem access at runtime. The snapshot is baked into the binary.

use std::sync::OnceLock;

use super::snapshot::CompiledRuleSnapshot;

/// The compiled temporal snapshot JSON, embedded at build time.
///
/// This file is generated by `build.rs` from the canonical TOML data files
/// in `data/temporal/`. If the data directory doesn't exist, an empty
/// snapshot is generated.
const SNAPSHOT_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/temporal_snapshot.json"));

/// Global singleton holding the parsed snapshot.
static COMPILED_SNAPSHOT: OnceLock<CompiledRuleSnapshot> = OnceLock::new();

/// Returns a reference to the compiled temporal snapshot.
///
/// The snapshot is parsed lazily on first access and cached for the
/// lifetime of the process. This function never panics in production
/// because the build script validates the JSON before embedding it.
pub fn compiled_snapshot() -> &'static CompiledRuleSnapshot {
    COMPILED_SNAPSHOT.get_or_init(|| {
        serde_json::from_slice(SNAPSHOT_BYTES).unwrap_or_else(|e| {
            tracing::error!("Failed to parse embedded temporal snapshot: {}", e);
            CompiledRuleSnapshot::empty()
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_snapshot_loads_successfully() {
        let snapshot = compiled_snapshot();
        // The build script should have generated a non-empty snapshot
        assert!(
            !snapshot.snapshot_id.is_empty(),
            "Snapshot ID should not be empty"
        );
        assert!(snapshot.schema_version >= 1);
    }

    #[test]
    fn test_snapshot_has_eras() {
        let snapshot = compiled_snapshot();
        assert!(
            !snapshot.eras.is_empty(),
            "Snapshot should contain at least one era"
        );
    }

    #[test]
    fn test_snapshot_has_form_artifacts() {
        let snapshot = compiled_snapshot();
        assert!(
            !snapshot.form_artifacts.is_empty(),
            "Snapshot should contain form artifacts"
        );
    }

    #[test]
    fn test_snapshot_has_citations() {
        let snapshot = compiled_snapshot();
        assert!(
            !snapshot.citations.is_empty(),
            "Snapshot should contain legal citations"
        );
    }

    #[test]
    fn test_snapshot_has_content_hash() {
        let snapshot = compiled_snapshot();
        assert!(
            !snapshot.content_hash.is_empty(),
            "Snapshot should have a content hash"
        );
    }

    #[test]
    fn test_snapshot_era_resolution() {
        let snapshot = compiled_snapshot();

        let pre_train = snapshot.find_primary_era(2017);
        assert!(pre_train.is_some(), "Should find PRE_TRAIN era for 2017");
        assert_eq!(pre_train.unwrap().era_id, "PRE_TRAIN");

        let train = snapshot.find_primary_era(2020);
        assert!(train.is_some(), "Should find TRAIN era for 2020");
        assert_eq!(train.unwrap().era_id, "TRAIN_2018");

        let eopt = snapshot.find_primary_era(2025);
        assert!(eopt.is_some(), "Should find EOPT era for 2025");
        assert_eq!(eopt.unwrap().era_id, "EOPT_2024");
    }
}
