#!/usr/bin/env python3
"""
Debug script to test IMAP authentication independently of the Rust app.

Tests:
1. App Password login via IMAP LOGIN
2. OAuth2 XOAUTH2 IMAP authentication (with token refresh)
"""

import imaplib
import base64
import json
import urllib.request
import urllib.parse
import sys

# ── Configuration ─────────────────────────────────────────────────────────────

EMAIL = "codeitlikemiley@gmail.com"
APP_PASSWORD = "tnlr iyqz olar simf"  # as generated by Google

GOOGLE_CLIENT_ID = "594275113512-ds9h0m7bef2mmp3udifjj8lr2cfnkgh9.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# You must paste a valid refresh_token here after running the OAuth flow once.
# Get it from your app's database or from the OAuth flow output.
REFRESH_TOKEN = ""  # <-- PASTE YOUR REFRESH TOKEN HERE


# ── Test 1: App Password ─────────────────────────────────────────────────────

def test_app_password():
    print("=" * 60)
    print("TEST 1: App Password IMAP LOGIN")
    print("=" * 60)
    
    # Test with spaces (as Google generates it)
    for label, pw in [
        ("with spaces", APP_PASSWORD),
        ("spaces removed", APP_PASSWORD.replace(" ", "")),
    ]:
        print(f"\n  Trying {label}: '{pw}'")
        try:
            mail = imaplib.IMAP4_SSL("imap.gmail.com")
            status, data = mail.login(EMAIL, pw)
            print(f"  ✅ SUCCESS: {status} {data}")
            mail.select("INBOX")
            print(f"  INBOX selected OK")
            mail.logout()
            return True
        except imaplib.IMAP4.error as e:
            print(f"  ❌ FAILED: {e}")
        except Exception as e:
            print(f"  ❌ ERROR: {type(e).__name__}: {e}")
    
    print("\n  ⚠️  Both App Password formats failed.")
    print("  This means the App Password is revoked or incorrect.")
    print("  Go to https://myaccount.google.com/apppasswords to generate a new one.")
    return False


# ── Test 2: OAuth2 XOAUTH2 ───────────────────────────────────────────────────

def refresh_access_token(refresh_token):
    """Refresh the access token using the refresh token."""
    print("\n  Refreshing access token...")
    
    data = urllib.parse.urlencode({
        "client_id": GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }).encode()
    
    req = urllib.request.Request(
        "https://oauth2.googleapis.com/token",
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    
    try:
        with urllib.request.urlopen(req) as resp:
            body = json.loads(resp.read().decode())
            access_token = body.get("access_token")
            print(f"  ✅ Token refreshed OK (first 20 chars): {access_token[:20]}...")
            return access_token
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        print(f"  ❌ Token refresh FAILED: HTTP {e.code}")
        print(f"  Response: {error_body}")
        return None


def test_xoauth2(access_token):
    """Test XOAUTH2 IMAP authentication."""
    print(f"\n  Testing XOAUTH2 with access_token (first 20 chars): {access_token[:20]}...")
    
    # Build the XOAUTH2 SASL string per Google spec:
    # https://developers.google.com/gmail/imap/xoauth2-protocol
    # Format: "user={email}\x01auth=Bearer {token}\x01\x01"
    auth_string = f"user={EMAIL}\x01auth=Bearer {access_token}\x01\x01"
    
    print(f"  Raw SASL string (repr): {repr(auth_string)}")
    print(f"  Raw SASL string length: {len(auth_string)}")
    
    # Base64 encode it ONCE
    encoded = base64.b64encode(auth_string.encode()).decode()
    print(f"  Base64 encoded: {encoded[:60]}...")
    
    try:
        mail = imaplib.IMAP4_SSL("imap.gmail.com")
        
        # Send AUTHENTICATE XOAUTH2 command
        status, data = mail.authenticate("XOAUTH2", lambda x: auth_string.encode())
        print(f"  ✅ XOAUTH2 SUCCESS: {status} {data}")
        mail.select("INBOX")
        print(f"  INBOX selected OK")
        mail.logout()
        return True
    except imaplib.IMAP4.error as e:
        print(f"  ❌ XOAUTH2 FAILED: {e}")
        
        # Decode the error — it often contains a JSON response
        try:
            # The error response from Gmail is base64-encoded JSON
            error_str = str(e)
            print(f"  Error details: {error_str}")
        except:
            pass
        return False
    except Exception as e:
        print(f"  ❌ ERROR: {type(e).__name__}: {e}")
        return False


def test_oauth2():
    print("\n" + "=" * 60)
    print("TEST 2: OAuth2 XOAUTH2 IMAP Authentication")
    print("=" * 60)
    
    if not REFRESH_TOKEN:
        print("\n  ⚠️  No REFRESH_TOKEN set. Skipping OAuth2 test.")
        print("  To test, paste your refresh_token into this script.")
        print("  You can find it by querying your app's database:")
        print("    sqlite3 ~/Library/Application\\ Support/Taxman/eBIRForms/bir_data.db")
        print("    SELECT data_json FROM profiles;")
        return False
    
    # Step 1: Refresh the access token
    access_token = refresh_access_token(REFRESH_TOKEN)
    if not access_token:
        return False
    
    # Step 2: Test XOAUTH2 with the fresh token
    return test_xoauth2(access_token)


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"Email: {EMAIL}")
    print(f"IMAP Host: imap.gmail.com")
    print()
    
    app_pw_ok = test_app_password()
    oauth_ok = test_oauth2()
    
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"  App Password:  {'✅ OK' if app_pw_ok else '❌ FAILED'}")
    print(f"  OAuth2 XOAUTH2: {'✅ OK' if oauth_ok else '❌ SKIPPED/FAILED'}")
    print()
    
    if not app_pw_ok:
        print("ACTION NEEDED: Generate a new App Password at:")
        print("  https://myaccount.google.com/apppasswords")
        print()
    
    if not oauth_ok and REFRESH_TOKEN:
        print("ACTION NEEDED: Re-authorize your Google account in the app.")
