pub mod cron_tasks;
pub mod dashboard;
pub mod debug_log_viewer;
pub mod email_confirmation_view;
pub mod form_1601c_view;
pub mod form_1701q_view;
pub mod form_2551q_view;
pub mod global_dashboard;
pub mod import_export;
pub mod lock_screen;
#[cfg(feature = "layout-editor")]
pub mod pdf_layout_editor_view;
pub mod pdf_viewer;
pub mod profile_manager;
pub mod settings;
pub mod typst_calibration_view;
