param(
 [string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),
 [string]$ExtractedRoot='C:\Users\uriah\AppData\Local\Temp\{68379049-6E6C-4478-A2C5-EF7B77ED7E38}',
 [string]$OfficialDir='C:\Mac\Home\Downloads\forms\2200Pv2020',
 [string]$SampleDir='C:\Mac\Home\Downloads\forms\2200P'
)
$ErrorActionPreference='Stop';$formId='2200p-v2020';$revision='2020-01-01';$packageVersion='7.9.6.0'
$htaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2200Pv2020.hta';$legacyPath=Join-Path $ExtractedRoot 'forms\BIR-Form2200P.hta'
$helpPath=Join-Path $ExtractedRoot 'helpfile\Help2200Pv2020.hta';$legacyHelpPath=Join-Path $ExtractedRoot 'helpfile\Help2200P.hta'
$pdfPath=Join-Path $OfficialDir '2200-P Jan 2020 ENCS final version2correct.pdf';$packagePath='C:\eBIRForms\BIRForms.exe'
$outDir=Join-Path $RepoRoot 'rules\forms\2200p-v2020';$fixtureDir=Join-Path $outDir 'fixtures'
$expected=@{hta='fbfa4f1224b99aa2effcad00f4aa3deaf960b4cc4f0d3899bfdbc63a2a02f8ec';legacy='2a41a474b4e81c85d597f304f5c373b49f279a2116698c347032ec2e8f1d830a';help='ed7f2828ad56127b7ae3c151c964526c39acd80df5d577655ffd4aa46fcf6a86';legacy_help='28895081de6548343554c52f53aa34e88dee0d23e4b32559b2b6c6f2085de0f4';pdf='7bf29a28a93f45ae7af9ba344d4755540abd324137831d594bc623b4a0c06d2c';package='de8ef0815509d65189e6794e1f8135a5ecf5f2800005d1fc5c87043efd96dbca';cipher='486067fae7d376db0a2a7ed00622a9204abc3de918fffe771b204d87332eb8c6';plain='0fd9030c1e4cf01bef8f7a83efdfab95f4ff744e305c87bc9f10bf41eb0055ca';inventory='9ae25b522dc21061031a5f069841fa63d2424051aa3dc9b0b36d67ef8ff5dbd1'}
function WJ($p,$v){[IO.File]::WriteAllText($p,(($v|ConvertTo-Json -Depth 60)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function WT($p,$v){[IO.File]::WriteAllText($p,$v,[Text.UTF8Encoding]::new($false))}
function HL([string[]]$l){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes(($l-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Attr($t,$n){$m=[regex]::Match($t,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($n)));if($m.Success){$m.Groups[2].Value}else{$null}}
function Asset($id,$kind,$path,$binding,$display=''){$i=Get-Item -LiteralPath $path;[pscustomobject][ordered]@{asset_id=$id;kind=$kind;path=if($display){$display}else{$path};sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();size=$i.Length;revision_binding=$binding}}
foreach($pair in @(@($htaPath,'hta'),@($legacyPath,'legacy'),@($helpPath,'help'),@($legacyHelpPath,'legacy_help'),@($pdfPath,'pdf'),@($packagePath,'package'))){if(-not(Test-Path -LiteralPath $pair[0] -PathType Leaf)){throw"Missing $($pair[0])"};if((Get-FileHash -LiteralPath $pair[0] -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected[$pair[1]]){throw"Hash changed: $($pair[0])"}}
$sample=@(Get-ChildItem -LiteralPath $SampleDir -File -Filter '*.xml');if($sample.Count-ne1){throw"Expected one sample; found $($sample.Count)."};if((Get-FileHash -LiteralPath $sample[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected.cipher){throw'Sample hash changed.'}
$hta=[IO.File]::ReadAllText($htaPath);$legacy=[IO.File]::ReadAllText($legacyPath);$help=[IO.File]::ReadAllText($helpPath);if($hta-notmatch'APPLICATIONNAME="2200Pv2020"'-or$hta-notmatch'January 2020 \(ENCS\)'){throw'Current revision binding changed.'};if($help-notmatch'Excise Tax Return for Petroleum Products'-or$help-notmatch'before removal of the petroleum products'){throw'Help binding changed.'}
$pb=[IO.File]::ReadAllBytes($pdfPath);if([Text.Encoding]::ASCII.GetString($pb[0..4])-ne'%PDF-'){throw'PDF magic mismatch.'};New-Item -ItemType Directory -Force -Path $fixtureDir|Out-Null
$redacted=Join-Path $SampleDir '2200P-final-copy-#email-redacted#.xml';$kt=Join-Path $RepoRoot 'rules\tools\extract-encrypted-field-keys.ps1'
$keyJson=&$kt -SourcePath $sample[0].FullName -RedactedSourcePath $redacted -FormId '2200p-legacy-excluded' -ExpectedCiphertextSha256 $expected.cipher -ExpectedDecryptedSha256 $expected.plain -ExpectedFieldCount 330 -ExpectedFieldInventorySha256 $expected.inventory
$ka=$keyJson|ConvertFrom-Json;$legacyKeys=@($ka.keys);$ci=@([regex]::Matches($hta,'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique);$li=@([regex]::Matches($legacy,'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique);$co=@($legacyKeys|Where-Object{$ci-contains$_});$lo=@($legacyKeys|Where-Object{$li-contains$_});$legacyDynamic=@($legacyKeys|Where-Object{$_-match'^frm2200P:(?:txtPlaceOfRemoval|txtLocally|txtImported|txtTaxRem|txtTaxPaid|txtUnderbond|txtExports|txtOthers|txtConditional|txtBasicTaxDue)\d+$'});if($co.Count-ne6-or$lo.Count-ne70-or$legacyDynamic.Count-ne260-or($lo.Count+$legacyDynamic.Count)-ne330){throw"Sample discrimination changed: current/static-legacy/dynamic-legacy $($co.Count)/$($lo.Count)/$($legacyDynamic.Count)."};WT (Join-Path $fixtureDir 'excluded-legacy-encrypted-field-keys-v796.json') ($keyJson-join[Environment]::NewLine)
$fm=[regex]::Match($hta,'(?is)<form\b[^>]*(?:id|name)\s*=\s*["'']frmMain["''][^>]*>(?<body>.*?)</form>');if(-not$fm.Success){throw'frmMain missing.'};$body=$fm.Groups['body'].Value;$offset=$fm.Groups['body'].Index;$excluded=@(@([regex]::Matches($body,'(?is)<script\b.*?</script>'))+@([regex]::Matches($body,'(?is)<!--.*?-->')))
$controls=[Collections.Generic.List[object]]::new();$ord=0;foreach($m in [regex]::Matches($body,'(?is)<(input|select|textarea|button)\b[^>]*>')){$skip=$false;foreach($r in $excluded){if($m.Index-ge$r.Index-and$m.Index-lt($r.Index+$r.Length)){$skip=$true;break}};if($skip){continue};$ord++;$tag=$m.Value;$el=$m.Groups[1].Value.ToLowerInvariant();$kind=if($el-eq'input'){Attr $tag 'type'}else{$el};if(-not$kind){$kind='text'};$kind=$kind.ToLowerInvariant();$def=Attr $tag 'value';if($kind-in@('radio','checkbox')){$def=if($tag-match'(?i)\bchecked(?:\s*=|\s|>)'){'true'}else{'false'}};$controls.Add([pscustomobject][ordered]@{ordinal=$ord;id=Attr $tag 'id';name=Attr $tag 'name';element=$el;control_kind=$kind;source_line=1+[regex]::Matches($hta.Substring(0,$offset+$m.Index),"`n").Count;default_value=$def;maxlength=Attr $tag 'maxlength';disabled=$tag-match'(?i)\bdisabled(?:\s*=|\s|>)';readonly=$tag-match'(?i)\breadonly(?:\s*=|\s|>)'})}
$serial=@($controls|Where-Object{$_.control_kind-in@('text','select','select-one','textarea','radio','checkbox')-and$_.id});$runtime='frm2200P:rdoPg1Pt1I6RDO';if($controls.Count-ne490-or$serial.Count-ne463-or@($serial.id|Sort-Object -Unique).Count-ne463){throw"Control inventory changed: $($controls.Count)/$($serial.Count)/$(@($serial.id|Sort-Object -Unique).Count)."};if($serial.id-contains$runtime-or$hta-notmatch[regex]::Escape("<select id='frm2200P:rdoPg1Pt1I6RDO'")){throw'Runtime RDO changed.'}
$familyNames=@('chkBoxSched1ATC','txtSched1ATC','txtSched1Description','txtSched1UnitOfMeasure','txtSched1ApplicableRate','txtSched1PlaceOfRemoval','txtSched1LocalManuProd','txtSched1Imported','txtSched1TotTaxRemovals','txtSched1TaxPaidImported','txtSched1UnderBond','txtSched1Exports','txtSched1Others','txtSched1TotTaxPaid','txtSched1BasicExciseTaxDue')
$required=@('frm2200P:txtPg1I1Month','frm2200P:txtPg1I1Day','frm2200P:txtPg1I1Year','frm2200P:txtPg1I5RDO',$runtime,'frm2200P:txtPg1Pt1I6RegisteredName','frm2200P:txtPg1Pt1I7RegisteredAddress','frm2200P:txPg1I7ZipCode','frm2200P:txtPg1Pt1I8ContactNumber','frm2200P:txtPg1Pt1I9Email','frm2200P:txtPg1Pt1I10Region','frm2200P:txtPg1Pt1I10Province','frm2200P:txtPg1Pt1I10City','frm2200P:txtPg1Pt1I11Region','frm2200P:txtPg1Pt1I11Province','frm2200P:txtPg1Pt1I11City')
$computed=@('frm2200P:txtSched1TotalTaxDue','frm2200P:txtPg1P3I16ExciseTaxDue','frm2200P:txtPg1P3I17CTotal','frm2200P:txtPg1P3I18NetTaxDue','frm2200P:txtPg1P3I20TaxStillDue','frm2200P:txtPg1P3I21DTotPenalties','frm2200P:txtPg1P3I22AmountPayable','frm2200P:txtPg1P3I23BPenalties','frm2200P:txtPg1P3I23CTotPmntMade','frm2200P:txtPg1P3I24BalToCarryOver')
function F($key,$ser,$occ,$c,$logical=''){$kind=if($c){$c.control_kind}else{'runtime-generated-select'};if(-not$logical){$logical=if($kind-in@('radio','checkbox')){'boolean'}elseif($key-match'(?i)(TIN|RDO|ATC|Zip|Month|Year|Region|Province|City)'){'code'}elseif($key-match'(?i)(Tax|Bal|Credit|Pmnt|Surcharge|Interest|Compromise|Amount|Rate|Local|Imported|Removal|Bond|Exports|Others|Total)'){'decimal-amount'}else{'string'}};$comp=$computed-contains$ser;$status=if($comp){'computed'}elseif($required-contains$ser){'required'}else{'optional'};$req=$null;if($ser-eq'frm2200P:txtPg1I12TaxReliefSpecify'){$status='conditional';$req='Tax Relief Yes is selected.'};if($ser-eq'frm2200P:txtPg1Pt2MOPOtherDesc'){$status='conditional';$req='Other manner of payment is selected.'};$cons=[ordered]@{};if($c-and$c.maxlength-match'^\d+$'){$cons.max_length=[int]$c.maxlength};if($logical-eq'decimal-amount'){$cons.precision=2;$cons.sign='source-dependent'};$enum=[object[]]::new(0);if($logical-eq'boolean'){$enum=[object[]]@('true','false')};$norm=[string[]]::new(0);if($logical-eq'decimal-amount'){$norm=[string[]]@('NumWithComma','formatCurrency','round(2)')};[pscustomobject][ordered]@{field_key=$key;serialized_key=$ser;serialized_occurrence=$occ;label=$ser;page=if($ser-match'(?i)Sched1'){2}else{1};item_number=if($ser-match'P3I(\d+[A-D]?)'){$Matches[1]}elseif($ser-match'Sched1'){'Schedule 1'}else{$null};control_kind=$kind;storage_type='string';logical_type=$logical;required=$status;required_when=$req;enabled_when=if($ser-eq'frm2200P:txtPg1P3I19PmntOnRtrnPrevFiled'){'Amended Return Yes is selected.'}else{$null};visible_when=$null;default_value=if($c){$c.default_value}else{'000'};empty_representation='';constraints=[pscustomobject]$cons;enum_values=$enum;normalization=$norm;computed=$comp;calculation_id=if($comp){'See calculations.json'}else{$null};source_refs=@('official-hta-runtime#saveXML',"official-hta-runtime#control:L$(if($c){$c.source_line}else{10571})");confidence='high';notes=@('Source-derived from the hash-pinned January 2020 runtime; no revision-matched final copy is available.')}}
$fields=[Collections.Generic.List[object]]::new();$occ=@{};foreach($c in $serial){$k=$c.id;if(-not$occ.ContainsKey($k)){$occ[$k]=0};$occ[$k]++;$fk=if($occ[$k]-eq1){$k}else{"$k#occurrence-$($occ[$k])"};$fields.Add((F $fk $k $occ[$k] $c))};$fields.Add((F $runtime $runtime 1 $null))
foreach($n in $familyNames){$logical=if($n-like'chk*'){'boolean'}elseif($n-match'ATC'){'code'}elseif($n-match'Description|Unit|Place'){'string'}else{'decimal-amount'};$enum=[object[]]::new(0);if($logical-eq'boolean'){$enum=[object[]]@('true','false')};$norm=[string[]]::new(0);if($logical-eq'decimal-amount'){$norm=[string[]]@('NumWithComma','formatCurrency','round(2)')};$k="frm2200P:$n{n>=28}";$fields.Add([pscustomobject][ordered]@{field_key=$k;serialized_key=$k;serialized_occurrence=1;label=$k;page=2;item_number='Schedule 1 dynamic row';control_kind=if($n-like'chk*'){'checkbox'}else{'text'};storage_type='string';logical_type=$logical;required='conditional';required_when='Dynamic row exists; ATC, description, unit, applicable rate, place of removal and at least one additional amount are required.';enabled_when=$null;visible_when='Dynamic row n exists.';default_value='';empty_representation='';constraints=[pscustomobject]@{index_minimum=28;unbounded=$true};enum_values=$enum;normalization=$norm;computed=$false;calculation_id=$null;source_refs=@('official-hta-runtime#rowTemplate:L5577-L5615','official-hta-runtime#saveXML');confidence='high';notes=@('Unbounded runtime family; source reindexes rows after deletion.')})}
$concrete=$serial.Count+1;if($concrete-ne464-or$familyNames.Count-ne15-or$fields.Count-ne479){throw"Typed inventory changed: $concrete/$($familyNames.Count)/$($fields.Count)."};WJ (Join-Path $outDir 'fields.json') ([ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;field_count=$fields.Count;runtime_serializable_element_count=$concrete;inventory_sha256=HL @($fields.field_key|Sort-Object);fields=$fields})
WJ (Join-Path $fixtureDir 'runtime-control-inventory-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;official_hta_sha256=$expected.hta;live_control_count=$controls.Count;static_serialized_occurrence_count=$serial.Count;static_unique_serialized_id_count=@($serial.id|Sort-Object -Unique).Count;runtime_generated_scalar_count=1;runtime_generated_scalars=@($runtime);runtime_family_count=$familyNames.Count;runtime_families=@($familyNames|ForEach-Object{"frm2200P:$_{n>=28}"});excluded_legacy_sample_key_count=$legacyKeys.Count;excluded_sample_current_overlap=$co.Count;excluded_sample_legacy_static_overlap=$lo.Count;excluded_sample_legacy_dynamic_family_match=$legacyDynamic.Count;controls=$controls})
$fn=Join-Path $RepoRoot 'rules\tools\extract-hta-function-inventory.ps1';WT (Join-Path $fixtureDir 'validation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200P:' -NamePattern '(?i)valid|check|save|date|submit|final|row')-join[Environment]::NewLine);WT (Join-Path $fixtureDir 'calculation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200P:' -NamePattern '(?i)comput|total|tax|penalt|balance|format')-join[Environment]::NewLine)
$rules=[Collections.Generic.List[object]]::new();Remove-Item Alias:R -ErrorAction SilentlyContinue;function R($id,$phase,$order,$cond,[string[]]$keys,$msg,[string[]]$refs,$assessment='verified-correct',$official='The branch alerts and stops the active operation.',$recommended='Retain as a structured revision-aware error.'){$rules.Add([pscustomobject][ordered]@{rule_id=$id;form_id=$formId;revision=$revision;phase=$phase;order=$order;condition=$cond;fields=$keys;accepted_behavior='Condition is false; processing continues.';rejected_behavior='The active operation stops unless official_behavior states otherwise.';exact_message=$msg;source_refs=$refs;evidence_type=@('source');assessment=$assessment;official_behavior=$official;recommended_app_behavior=$recommended;confidence='high';unresolved_questions=@()})}
R '2200p-validate-001-month' validate 1 'Month is 00.' @('frm2200P:txtPg1I1Month') 'Month field on Page 1 Item 1 is required.' @('official-hta-runtime#validateAll:L5201-L5207')
R '2200p-validate-002-day' validate 2 'Day is blank.' @('frm2200P:txtPg1I1Day') 'Day field on Page 1 Item 1 is required.' @('official-hta-runtime#validateAll:L5209-L5214')
R '2200p-validate-003-year' validate 3 'Year is blank.' @('frm2200P:txtPg1I1Year') 'Year field on Page 1 Item 1 is required.' @('official-hta-runtime#validateAll:L5216-L5221')
R '2200p-validate-004-date' validate 4 'Return date fails calendar/component checks.' @('Return-period-fields') 'Please provide a valid date. (MM/DD/YYYY format) in Page 1 Item 1.' @('official-hta-runtime#validateDate:L5777-L5850')
R '2200p-validate-005-future' validate 5 'Return date is after today.' @('Return-period-fields') 'Page 1 Item 1 Date cannot be a future date ' @('official-hta-runtime#validateDate:L5839-L5843')
R '2200p-validate-006-pre-revision' validate 6 'Return date is before January 1, 2020.' @('Return-period-fields') 'Page 1 Item 1 Date cannot be earlier than January 2020' @('official-hta-runtime#validateDate:L5844-L5848')
R '2200p-validate-007-rdo' validate 7 'Hidden RDO is 000.' @('frm2200P:txtPg1I5RDO') 'Please enter a valid RDO Code on Page 1 Item 6.' @('official-hta-runtime#validateAll:L5224')
$base=@(@('name','frm2200P:txtPg1Pt1I6RegisteredName','Name field on Page 1 Item 7 is required.'),@('address','frm2200P:txtPg1Pt1I7RegisteredAddress','Registered Address field on Page 1 Item 8 is required.'),@('zip','frm2200P:txPg1I7ZipCode','Zip Code field on Page 1 Item 8A is required.'),@('contact','frm2200P:txtPg1Pt1I8ContactNumber','Contact Number field on Page 1 Item 9 is required.'),@('email','frm2200P:txtPg1Pt1I9Email','E-mail address on page 1 item 10 is required.'));$o=8;foreach($x in $base){R "2200p-validate-$('{0:d3}'-f$o)-$($x[0])" validate $o 'Field is blank after trim.' @($x[1]) $x[2] @('official-hta-runtime#validateAll:L5225-L5229');$o++}
$loc=@(@('prod-region','frm2200P:txtPg1Pt1I10Region','Region field on Page 1 Item 10 (Place of Production) is required.'),@('prod-province','frm2200P:txtPg1Pt1I10Province','Province field on Page 1 Item 10 (Place of Production) is required.'),@('prod-city','frm2200P:txtPg1Pt1I10City','City field on Page 1 Item 10 (Place of Production) is required.'),@('rem-region','frm2200P:txtPg1Pt1I11Region','Region field on Page 1 Item 11 (Place of Removal) is required.'),@('rem-province','frm2200P:txtPg1Pt1I11Province','Province field on Page 1 Item 11 (Place of Removal) is required.'),@('rem-city','frm2200P:txtPg1Pt1I11City','City field on Page 1 Item 11 (Place of Removal) is required.'));foreach($x in $loc){R "2200p-validate-$('{0:d3}'-f$o)-$($x[0])" validate $o 'Location selector is 00.' @($x[1]) $x[2] @('official-hta-runtime#validateAll:L5231-L5241');$o++}
R '2200p-validate-019-relief-choice' validate 19 'Neither relief radio is selected.' @('frm2200P:rdoPg1I12TaxReliefYes','frm2200P:rdoPg1I12TaxReliefNo') 'Availing of Tax Relief field on Page 1 Item 12 is required.' @('official-hta-runtime#validateAll:L5243-L5247')
R '2200p-validate-020-relief-specify' validate 20 'Relief Yes is selected and specification is blank.' @('frm2200P:rdoPg1I12TaxReliefYes','frm2200P:txtPg1I12TaxReliefSpecify') 'Specify Tax Relief field on Page 1 Item 12A is required.' @('official-hta-runtime#validateAll:L5249-L5253')
R '2200p-validate-021-payment-choice' validate 21 'No manner-of-payment radio is selected.' @('Manner-of-payment-fields') 'Manner of Payment on Page 1 Part II is required.' @('official-hta-runtime#validateAll:L5255-L5260')
R '2200p-validate-022-payment-other' validate 22 'Other manner is selected and description is blank.' @('frm2200P:rdoPg1Pt2MOPOther','frm2200P:txtPg1Pt2MOPOtherDesc') 'Specfy Manner of Payment field on Page 1 Part II Item 15 is required.' @('official-hta-runtime#validateAll:L5262-L5266')
R '2200p-validate-023-fund' validate 23 'Item 24 balance is positive.' @('frm2200P:txtPg1P3I24BalToCarryOver') 'YOU HAVE INSUFICIENT FUND. PLEASE APPLY DEPOSIT TO PROCEED' @('official-hta-runtime#validateAll:L5268-L5272')
R '2200p-schedule-024-atc' validate 24 'Custom/dynamic row 26+ lacks ATC.' @('frm2200P:txtSched1ATC{26..n}') 'ATC in row #{row} is required.' @('official-hta-runtime#checkPartVReqRow:L5728-L5735')
R '2200p-schedule-025-description' validate 25 'Custom/dynamic row lacks description.' @('frm2200P:txtSched1Description{26..n}') 'Description in row #{row} is required.' @('official-hta-runtime#checkPartVReqRow:L5737-L5743')
R '2200p-schedule-026-unit' validate 26 'Custom/dynamic row lacks unit of measure.' @('frm2200P:txtSched1UnitOfMeasure{26..n}') 'Unit of Measure in row #{row} is required.' @('official-hta-runtime#checkPartVReqRow:L5745-L5751')
R '2200p-schedule-027-rate' validate 27 'Custom/dynamic row lacks applicable rate.' @('frm2200P:txtSched1ApplicableRate{26..n}') 'Applicable Rate in row #{row} is required.' @('official-hta-runtime#checkPartVReqRow:L5753-L5759')
R '2200p-schedule-028-place' validate 28 'Populated row lacks place of removal.' @('frm2200P:txtSched1PlaceOfRemoval{1..n}') 'Place of Removal in row #{row} is required.' @('official-hta-runtime#checkPartVRow:L5757-L5764')
R '2200p-schedule-029-one-column' validate 29 'Row has place but all other tested amount columns are blank.' @('Schedule-1-row-fields') 'Input at least 1 more column in row #{row}' @('official-hta-runtime#checkPartVRow:L5766-L5774')
R '2200p-addrow-030-atc' 'blur/change' 1 'Previous custom row lacks ATC before Add Row.' @('frm2200P:txtSched1ATC{n}') 'ATC in row #{row} is required.' @('official-hta-runtime#isPrevRowValid')
R '2200p-input-031-email' 'blur/change' 2 'Nonblank email fails source substring regex.' @('frm2200P:txtPg1Pt1I9Email') 'Please enter a valid e-mail address on page 1 item 10' @('official-hta-runtime#validateEmail:L6023-L6034')
R '2200p-input-032-year' 'blur/change' 3 'Nonblank year is after current year.' @('frm2200P:txtPg1I1Year') 'Year shall not be greater than the present year' @('official-hta-runtime#checkYear:L6107-L6119')
R '2200p-save-033-date' save 1 'Return date is blank or month/day is 00.' @('Return-period-fields') 'Please enter correct date on Item 1.' @('official-hta-runtime#initialValidateBeforeSave:L11812-L11815')
R '2200p-save-034-rdo' save 2 'Runtime RDO is 000.' @($runtime) 'Please enter a valid RDO Code on Item 6.' @('official-hta-runtime#initialValidateBeforeSave:L11819')
R '2200p-save-035-name' save 3 'Name is blank.' @('frm2200P:txtPg1Pt1I6RegisteredName') 'Please enter a valid name on Page 1 Item 7.' @('official-hta-runtime#initialValidateBeforeSave:L11820')
R '2200p-save-036-address' save 4 'Address is blank.' @('frm2200P:txtPg1Pt1I7RegisteredAddress') 'Please enter a valid Registered Address on Page 1 Item 8.' @('official-hta-runtime#initialValidateBeforeSave:L11821')
R '2200p-save-037-contact' save 5 'Contact is blank.' @('frm2200P:txtPg1Pt1I8ContactNumber') 'Please enter a valid Contact Number on Page 1 Item 9.' @('official-hta-runtime#initialValidateBeforeSave:L11822')
R '2200p-defect-038-manual-derived' 'blur/change' 4 'Derived schedule totals/tax due disagree with their inputs.' @('Schedule-1-derived-columns') $null @('official-hta-runtime#computeTotTaxRemov:L5344-L5370','official-hta-runtime#computeTotTaxPaid:L5372-L5406','official-hta-runtime#computeBasicExciseDue:L5408-L5421') 'incorrect-official-behavior' 'All row derivation functions are commented out; taxable removals, tax-paid totals, and excise due remain manual.' 'Compute every derived schedule column from revision-pinned inputs and rates.'
R '2200p-defect-039-nonnumeric-date' validate 30 'Day is two nonnumeric characters or year is four nonnumeric characters.' @('frm2200P:txtPg1I1Day','frm2200P:txtPg1I1Year') $null @('official-hta-runtime#validateDate:L5777-L5850') 'incorrect-official-behavior' 'isNaN(strmm || strdd || stryyyy) checks only the first truthy component and Invalid Date comparisons fail open.' 'Strictly parse each component as digits.'
R '2200p-defect-040-email-substring' 'blur/change' 5 'Email has a valid-looking substring plus junk.' @('frm2200P:txtPg1Pt1I9Email') $null @('official-hta-runtime#validateEmail:L6023-L6034') 'official-bug-compatible' 'The regex is unanchored.' 'Validate the full normalized value.'
R '2200p-defect-041-save-sparse' save 6 'Any Validate-only location, relief, payment, balance, ZIP, email, or schedule rule fails.' @('Validate-only-fields') $null @('official-hta-runtime#initialValidateBeforeSave:L11809-L11825','official-hta-runtime#validateAll:L5198-L5277') 'incorrect-official-behavior' 'Save checks only date, RDO, name, address, and contact.' 'Use one phase-aware validation graph.'
R '2200p-defect-042-row-index' 'blur/change' 6 'Dynamic row index reaches 100.' @('Schedule-1-dynamic-families') $null @('official-hta-runtime#getFieldRowNum:L5465-L5476') 'incorrect-official-behavior' 'Only the final two ID characters are parsed.' 'Keep typed row identity.'
R '2200p-defect-043-malformed-template' 'blur/change' 7 'A dynamic row is created from rowTemplate.' @('Schedule-1-dynamic-families') $null @('official-hta-runtime#rowTemplate:L5577-L5615') 'official-bug-compatible' 'Generated input strings omit whitespace/closing quotes between id, name, type, and value attributes in multiple controls.' 'Generate controls through DOM APIs or valid escaped templates.'
WJ (Join-Path $outDir 'validations.json') ([ordered]@{'$schema'='../../schema/validations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;first_error_behavior='Validate/Save stop at the first source-ordered failure; Schedule 1 stops at the first failing row.';rules=$rules})
$calcs=[Collections.Generic.List[object]]::new();function C($id,[string[]]$out,[string[]]$in,$formula,$trigger,[string[]]$deps,[string[]]$refs,$assessment='verified-correct'){$calcs.Add([pscustomobject][ordered]@{calculation_id=$id;outputs=$out;inputs=$in;condition=$null;official_formula=$formula;rounding='toFixed(2), then formatCurrency.';trigger=$trigger;depends_on=$deps;source_refs=$refs;assessment=$assessment;recommended_app_behavior='Use typed decimals and two-decimal display; replace manual derived schedule values with revision-pinned calculations.';confidence='high'})}
C '2200p-schedule-total' @('frm2200P:txtSched1TotalTaxDue') @('frm2200P:txtSched1BasicExciseTaxDue{1..n}') 'Sum manually entered Basic Excise Tax Due across all extant rows.' computeBasicExciseTaxDue @() @('official-hta-runtime#computeBasicExciseTaxDue:L5440-L5463') 'official-bug-compatible'
C '2200p-item16' @('frm2200P:txtPg1P3I16ExciseTaxDue') @('frm2200P:txtSched1TotalTaxDue') 'Item 16 copies schedule total, or 0.00 when blank.' partThreeComputation @('2200p-schedule-total') @('official-hta-runtime#partThreeComputation')
C '2200p-item17c' @('frm2200P:txtPg1P3I17CTotal') @('frm2200P:txtPg1P3I17ABalCarriedOver','frm2200P:txtPg1P3I17BCredExciseTax') '17C = 17A + 17B.' partThreeComputation @() @('official-hta-runtime#partThreeComputation')
C '2200p-item18' @('frm2200P:txtPg1P3I18NetTaxDue') @('frm2200P:txtPg1P3I16ExciseTaxDue','frm2200P:txtPg1P3I17CTotal') '18 = 16 - 17C.' partThreeComputation @('2200p-item16','2200p-item17c') @('official-hta-runtime#partThreeComputation')
C '2200p-item20' @('frm2200P:txtPg1P3I20TaxStillDue') @('frm2200P:txtPg1P3I18NetTaxDue','frm2200P:txtPg1P3I19PmntOnRtrnPrevFiled') '20 = 18 - 19.' partThreeComputation @('2200p-item18') @('official-hta-runtime#partThreeComputation')
C '2200p-item21d' @('frm2200P:txtPg1P3I21DTotPenalties') @('frm2200P:txtPg1P3I21ASurcharge','frm2200P:txtPg1P3I21BInterest','frm2200P:txtPg1P3I21CCompromise') '21D = 21A + 21B + 21C.' partThreeComputation @() @('official-hta-runtime#partThreeComputation')
C '2200p-item22' @('frm2200P:txtPg1P3I22AmountPayable') @('frm2200P:txtPg1P3I20TaxStillDue','frm2200P:txtPg1P3I21DTotPenalties') '22 = 20 + 21D.' partThreeComputation @('2200p-item20','2200p-item21d') @('official-hta-runtime#partThreeComputation')
C '2200p-item23b' @('frm2200P:txtPg1P3I23BPenalties') @('frm2200P:txtPg1P3I21DTotPenalties') '23B copies 21D.' partThreeComputation @('2200p-item21d') @('official-hta-runtime#partThreeComputation')
C '2200p-item23c' @('frm2200P:txtPg1P3I23CTotPmntMade') @('frm2200P:txtPg1P3I23ATaxPmntDposit','frm2200P:txtPg1P3I23BPenalties') '23C = 23A + 23B.' partThreeComputation @('2200p-item23b') @('official-hta-runtime#partThreeComputation')
C '2200p-item24' @('frm2200P:txtPg1P3I24BalToCarryOver') @('frm2200P:txtPg1P3I22AmountPayable','frm2200P:txtPg1P3I23CTotPmntMade') '24 = 22 - 23C.' partThreeComputation @('2200p-item22','2200p-item23c') @('official-hta-runtime#partThreeComputation')
WJ (Join-Path $outDir 'calculations.json') ([ordered]@{'$schema'='../../schema/calculations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;evaluation_order=@($calcs.calculation_id);calculations=$calcs})
$cases=@();$n=0;foreach($r in @($rules|Where-Object{$_.exact_message})){$n++;$cases+=[pscustomobject][ordered]@{case_id=('case-{0:d2}-{1}'-f$n,$r.rule_id);phase=$r.phase;mutations=@{synthetic_condition=$r.condition};expected_message=$r.exact_message;expected_behavior=$r.official_behavior;rule_id=$r.rule_id}};WJ (Join-Path $fixtureDir 'negative-cases.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;synthetic_only=$true;cases=$cases});WJ (Join-Path $fixtureDir 'calculation-boundaries.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;cases=@(@{case_id='schedule-total';calculation_id='2200p-schedule-total';rows=@(10.25,20.10);official_output=30.35},@{case_id='item24';calculation_id='2200p-item24';item22=1200;item23c=1100;official_output=100})})
$resources=@();foreach($src in @([regex]::Matches($hta,'(?i)<script[^>]+src\s*=\s*(["''])(?<v>.*?)\1')|ForEach-Object{$_.Groups['v'].Value}|Sort-Object -Unique)){$full=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $htaPath) $src));if(Test-Path -LiteralPath $full){$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$true;size=(Get-Item -LiteralPath $full).Length;sha256=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()}}else{$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$false;size=$null;sha256=$null}}};WJ (Join-Path $fixtureDir 'official-resource-hashes-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;resources=$resources})
$deadline='For each place of production, file a separate return and pay before removal of petroleum products from the place of production.'
$workflow=[ordered]@{'$schema'='../../schema/workflow.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;phases=@(@{phase='edit';official_behavior='January 2020 petroleum-products excise return with 27 fixed schedule rows and unbounded add-more rows.';source_refs=@('official-hta-runtime','official-form-pdf','revision-help');confidence='high'},@{phase='saved-draft';official_behavior='Save runs the narrow date/RDO/name/address/contact graph.';source_refs=@('official-hta-runtime#initialValidateBeforeSave');confidence='high'},@{phase='validated';official_behavior='Validate checks identity, locations, relief/payment, balance and Schedule 1 completeness.';source_refs=@('official-hta-runtime#validateAll','official-hta-runtime#checkPartVFields');confidence='high'},@{phase='final-copy';official_behavior='The available 330-key artifact belongs to the predecessor and is excluded.';source_refs=@('excluded-legacy-encrypted-field-keys-v796');confidence='high'},@{phase='submitted';official_behavior='Online transport was not exercised.';source_refs=@('official-hta-runtime#sendEmail');confidence='medium'});transitions=@(@{from='edit';action='Save';to='saved-draft';guard='Sparse Save checks pass.';side_effects=@('Writes flat pseudo-XML.');source_refs=@('official-hta-runtime#saveXML')},@{from='edit';action='Validate';to='validated';guard='Validate graph passes.';side_effects=@('Disables controls.','Enables Final Copy.');source_refs=@('official-hta-runtime#validate')},@{from='validated';action='Edit';to='edit';guard=$null;side_effects=@('Re-enables controls.');source_refs=@('official-hta-runtime#enableAllControl')},@{from='validated';action='Final Copy';to='final-copy';guard='Finalization succeeds.';side_effects=@('Encrypts/compresses copy.');source_refs=@('official-hta-runtime#saveEncryptedProfile')},@{from='final-copy';action='Transport';to='submitted';guard='Connectivity and acceptance succeed.';side_effects=@('Untested online attempt.');source_refs=@('official-hta-runtime#sendEmail')});prerequisites=@('Return date','RDO/identity','Production/removal locations','Tax relief','Payment manner','Sufficient prepayment','Schedule rows');required_attachments=@();filing_deadlines=@(@{quarter='Q1';due_date_rule=$deadline;source_refs=@('revision-help#L150-L152');confidence='high'},@{quarter='Q2';due_date_rule=$deadline;source_refs=@('revision-help#L150-L152');confidence='high'},@{quarter='Q3';due_date_rule=$deadline;source_refs=@('revision-help#L150-L152');confidence='high'},@{quarter='Q4';due_date_rule=$deadline;source_refs=@('revision-help#L150-L152');confidence='high'})};WJ (Join-Path $outDir 'workflow.json') $workflow
$bugs=@($rules|Where-Object{$_.assessment-in@('official-bug-compatible','incorrect-official-behavior','obsolete')}).Count;$assets=@(Asset 'package-7.9.6' 'official-package-executable' $packagePath 'Installed Offline eBIRForms package 7.9.6.0.';Asset 'official-hta-runtime' 'runtime-extracted-hta' $htaPath 'January 2020 ENCS runtime.';Asset 'legacy-runtime-excluded' 'runtime-extracted-hta' $legacyPath 'Predecessor used only for sample discrimination.';Asset 'revision-help' 'official-runtime-help' $helpPath 'January 2020 petroleum instructions.';Asset 'legacy-help-excluded' 'official-runtime-help' $legacyHelpPath 'Predecessor help excluded.';Asset 'official-form-pdf' 'official-form-pdf' $pdfPath 'January 2020 form PDF.';Asset 'legacy-encrypted-sample-excluded' 'dummy-profile-encrypted-final-copy' $sample[0].FullName 'Excluded predecessor-shaped dummy final copy; values omitted.' $redacted)
$manifest=[ordered]@{'$schema'='../../schema/form-manifest.schema.json';schema_version='1.0.0';form_id=$formId;form_code='2200P';revision=$revision;package_version=$packageVersion;status='complete';official_assets=$assets;counts=[ordered]@{concrete_fields=$concrete;runtime_field_families=$familyNames.Count;fields_total=$fields.Count;typed_fields=$fields.Count;validation_rules=$rules.Count;confirmed_official_bugs=$bugs;calculations=$calcs.Count;negative_fixtures=$cases.Count;unverified_gaps=2};artifacts=[ordered]@{fields='fields.json';validations='validations.json';calculations='calculations.json';workflow='workflow.json';evidence='evidence.md';audit='audit.md';gaps='gaps.md';excluded_legacy_encrypted_keys='fixtures/excluded-legacy-encrypted-field-keys-v796.json';runtime_controls='fixtures/runtime-control-inventory-v796.json';validation_functions='fixtures/validation-function-inventory-v796.json';calculation_functions='fixtures/calculation-function-inventory-v796.json';resources='fixtures/official-resource-hashes-v796.json';negative_fixtures='fixtures/negative-cases.json';calculation_fixtures='fixtures/calculation-boundaries.json'};scope_notes=@('Research only; no renderer/release metadata changed.','No decrypted values or email-bearing filenames emitted.','Current static controls plus runtime RDO and 15 unbounded schedule families are preserved.','Available 330-key predecessor artifact is excluded.')}
WJ (Join-Path $outDir 'manifest.json') $manifest;WT (Join-Path $outDir 'README.md') "# BIR Form 2200P - January 2020`n`nRevision-specific Offline eBIRForms rules with $concrete concrete serialized fields and 15 unbounded Schedule 1 families.`n";WT (Join-Path $outDir 'evidence.md') "# Evidence`n`n- January 2020 runtime: $($expected.hta); predecessor: $($expected.legacy), excluded.`n- Revision help: $($expected.help); PDF: $($expected.pdf).`n- Sample: ciphertext $($expected.cipher), decrypted $($expected.plain), 330 keys, inventory $($expected.inventory); values never emitted.`n- Sample discrimination: $($co.Count) current-ID overlaps; $($lo.Count) predecessor static-ID overlaps plus $($legacyDynamic.Count) predecessor dynamic-family matches cover all 330 keys. Sample excluded.`n- Inventory: $($serial.Count) static occurrences + runtime RDO + 15 families.`n`nAll email-bearing filenames use `#email-redacted#`.`n";WT (Join-Path $outDir 'gaps.md') "# Gaps`n`n1. No revision-matched January 2020 final copy is available; predecessor artifact excluded.`n2. Online submission was not exercised.`n";WT (Join-Path $outDir 'audit.md') "# Audit`n`n- Revision separation: pass.`n- Sample discrimination: $($co.Count) current overlaps; $($lo.Count) predecessor static plus $($legacyDynamic.Count) predecessor dynamic matches.`n- Typed inventory: $concrete concrete + $($familyNames.Count) families.`n- Validations $($rules.Count); calculations $($calcs.Count); negatives $($cases.Count); defects $bugs.`n- Full structural/schema audit must run.`n- No renderer/release/capability/commit/push changes.`n"
$ip=Join-Path $RepoRoot 'rules\index.json';$index=Get-Content -Raw -LiteralPath $ip|ConvertFrom-Json;$e=$index.forms|Where-Object{$_.form_id-eq$formId};if($e){$e.form_code='2200P';$e.revision=$revision;$e.package_version=$packageVersion;$e.priority=35;$e.status='complete';$e.path='forms/2200p-v2020/manifest.json'}else{$index.forms+=[pscustomobject][ordered]@{form_id=$formId;form_code='2200P';revision=$revision;package_version=$packageVersion;priority=35;status='complete';path='forms/2200p-v2020/manifest.json'}};$index.forms=@($index.forms|Sort-Object priority);$index.updated='2026-07-23';WJ $ip $index
[pscustomobject]@{form_id=$formId;live_controls=$controls.Count;static_serialized=$serial.Count;unique_static=@($serial.id|Sort-Object -Unique).Count;concrete_fields=$concrete;families=$familyNames.Count;typed_fields=$fields.Count;sample_current_overlap=$co.Count;sample_legacy_overlap=$lo.Count;validations=$rules.Count;calculations=$calcs.Count;negative_fixtures=$cases.Count;confirmed_official_bugs=$bugs;next_form='2200S'}|ConvertTo-Json
