param(
    [string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),
    [string]$ExtractedRoot='C:\Users\uriah\AppData\Local\Temp\{68379049-6E6C-4478-A2C5-EF7B77ED7E38}',
    [string]$OfficialDir='C:\Mac\Home\Downloads\forms\2552v2018',
    [string]$SampleDir='C:\Mac\Home\Downloads\forms\2552'
)
$ErrorActionPreference='Stop'
$formId='2552-v2018';$revision='2018-01-01';$packageVersion='7.9.6.0'
$htaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2552v2018.hta';$legacyPath=Join-Path $ExtractedRoot 'forms\BIR-Form2552.hta'
$helpPath=Join-Path $ExtractedRoot 'helpfile\Help2552.hta';$pdfPath=Join-Path $OfficialDir '2552 2018ENCS Final.pdf';$guidePath=Join-Path $OfficialDir '2552 Guidelines and Instructions.pdf'
$packagePath='C:\eBIRForms\BIRForms.exe';$outDir=Join-Path $RepoRoot 'rules\forms\2552-v2018';$fixtureDir=Join-Path $outDir 'fixtures'
$expected=@{
 hta='a608d954cff716ea0240a5648ae01bdff42e50dc0244dafe32c2747eb59114a4';legacy='3692c9ca93e09e982db28197323de56982a958da2c714f92c6749dbe856dd32e';help='81bfb72ab829ac7ff9774ed940eacb1f3ced347d710393e90b2f9dffd0e7f19e';pdf='c0a9d7cd44cf931fb939a010a265d05655b9a1d55d21841ecf0b590594b1742a';guide='667888b776a01174bc6a7faf7e7ba8836eefeaae8cbaebe0dd67ef8cda144e05';cipher='c9eb4ca9bcf5b9a90a2b438ce627facf3f5385cc22bb47c8ceef7320537abfae';plain='29ed49c8666f6872a0f8495cbc813d15fce69c996bc3358d32729b193ff0c6f4';inventory='cc5acb4fb0a2dbcf71f1252ede7ba70857f76c44220d453aad245752071f4682';package='de8ef0815509d65189e6794e1f8135a5ecf5f2800005d1fc5c87043efd96dbca'
}
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 60)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function Write-Utf8([string]$Path,[string]$Value){[IO.File]::WriteAllText($Path,$Value,[Text.UTF8Encoding]::new($false))}
function Hash-Lines([string[]]$Lines){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes(($Lines-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Attr([string]$Tag,[string]$Name){$m=[regex]::Match($Tag,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($Name)));if($m.Success){$m.Groups[2].Value}else{$null}}
function Asset([string]$Id,[string]$Kind,[string]$Path,[string]$Binding,[string]$Display=''){$i=Get-Item -LiteralPath $Path;[pscustomobject][ordered]@{asset_id=$Id;kind=$Kind;path=if($Display){$Display}else{$Path};sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant();size=$i.Length;revision_binding=$Binding}}
foreach($pair in @(@($htaPath,'hta'),@($legacyPath,'legacy'),@($helpPath,'help'),@($pdfPath,'pdf'),@($guidePath,'guide'),@($packagePath,'package'))){if(-not(Test-Path -LiteralPath $pair[0] -PathType Leaf)){throw "Missing $($pair[0])"};if((Get-FileHash -LiteralPath $pair[0] -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected[$pair[1]]){throw "Hash changed: $($pair[0])"}}
$sample=@(Get-ChildItem -LiteralPath $SampleDir -File -Filter '*.xml');if($sample.Count-ne1){throw "Expected one sample; found $($sample.Count)."};if((Get-FileHash -LiteralPath $sample[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected.cipher){throw 'Sample hash changed.'}
foreach($pdf in @($pdfPath,$guidePath)){$b=[IO.File]::ReadAllBytes($pdf);if([Text.Encoding]::ASCII.GetString($b[0..4])-ne'%PDF-'){throw "PDF magic mismatch: $pdf"}}
$hta=[IO.File]::ReadAllText($htaPath);$help=[IO.File]::ReadAllText($helpPath)
if($hta-notmatch'(?i)January\s+2018\s+\(ENCS\)'-or$hta-notmatch'(?i)var\s+formType\s*=\s*["'']2552v2018["'']'){throw 'January 2018 runtime binding changed.'}
if($help-notmatch'(?i)five\s+\(5\)\s+banking\s+days'-or$help-notmatch'(?i)thirty\s+\(30\)\s+days'){throw 'Packaged help content changed.'}
New-Item -ItemType Directory -Force -Path $fixtureDir|Out-Null
$keyTool=Join-Path $RepoRoot 'rules\tools\extract-encrypted-field-keys.ps1'
$keyJson=&$keyTool -SourcePath $sample[0].FullName -RedactedSourcePath (Join-Path $SampleDir '2552-final-copy-#email-redacted#.xml') -FormId '2552-v1999' -ExpectedCiphertextSha256 $expected.cipher -ExpectedDecryptedSha256 $expected.plain -ExpectedFieldCount 61 -ExpectedFieldInventorySha256 $expected.inventory
$ka=$keyJson|ConvertFrom-Json;$legacyKeys=@($ka.keys);Write-Utf8 (Join-Path $fixtureDir 'excluded-legacy-encrypted-field-keys-v796.json') ($keyJson-join[Environment]::NewLine)
$legacyIds=@([regex]::Matches([IO.File]::ReadAllText($legacyPath),'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique);$currentIds=@([regex]::Matches($hta,'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique)
$lo=@($legacyKeys|Where-Object{$legacyIds-contains$_});$co=@($legacyKeys|Where-Object{$currentIds-contains$_});if($lo.Count-ne61-or$co.Count-ne6){throw "Sample discrimination changed: $($lo.Count)/$($co.Count)."}

$fm=[regex]::Match($hta,'(?is)<form\b[^>]*(?:id|name)\s*=\s*["'']frmMain["''][^>]*>(?<body>.*?)</form>');if(-not$fm.Success){throw 'frmMain missing.'};$body=$fm.Groups['body'].Value;$offset=$fm.Groups['body'].Index;$excluded=@(@([regex]::Matches($body,'(?is)<script\b.*?</script>'))+@([regex]::Matches($body,'(?is)<!--.*?-->')))
$controls=[Collections.Generic.List[object]]::new();$ordinal=0
foreach($m in [regex]::Matches($body,'(?is)<(input|select|textarea|button)\b[^>]*>')){$skip=$false;foreach($r in $excluded){if($m.Index-ge$r.Index-and$m.Index-lt($r.Index+$r.Length)){$skip=$true;break}};if($skip){continue};$ordinal++;$tag=$m.Value;$el=$m.Groups[1].Value.ToLowerInvariant();$kind=if($el-eq'input'){Attr $tag 'type'}else{$el};if(-not$kind){$kind='text'};$controls.Add([pscustomobject][ordered]@{ordinal=$ordinal;id=Attr $tag 'id';name=Attr $tag 'name';element=$el;control_kind=$kind.ToLowerInvariant();source_line=1+[regex]::Matches($hta.Substring(0,$offset+$m.Index),"`n").Count;value=Attr $tag 'value';maxlength=Attr $tag 'maxlength';disabled=$tag-match'(?i)\bdisabled(?:\s*=|\s|>)';readonly=$tag-match'(?i)\breadonly(?:\s*=|\s|>)'})}
$serial=@($controls|Where-Object{$_.control_kind-in@('text','select','select-one','textarea','radio','checkbox')});$staticIds=@($serial.id|Where-Object{$_}|Sort-Object -Unique)
if($controls.Count-ne283-or$staticIds.Count-ne237){throw "Expected 283 live/237 serial IDs; found $($controls.Count)/$($staticIds.Count)."}
$byId=@{};foreach($c in $controls){if($c.id-and-not$byId.ContainsKey($c.id)){$byId[$c.id]=$c}}
$runtimeScalar='frm2552:rdoPg1Pt1I5RDO';if($staticIds-contains$runtimeScalar-or$hta-notmatch[regex]::Escape("<select id='frm2552:rdoPg1Pt1I5RDO'")){throw 'Runtime RDO selector derivation changed.'}
$families=@();foreach($sch in 1..3){foreach($col in 1..8){$logical=if($col-eq1){'date-string-mm-dd-yyyy'}elseif($col-in@(2,3,4)){'string'}else{'whole-peso-amount'};$families+=[pscustomobject]@{field_pattern="frm2552:txtPg2Pt5Sch${sch}_{N>=1}Col$col";schedule=$sch;column=$col;logical=$logical;source_line=if($col-le3){3870+$col-1}else{3871+$col}}}}
if($families.Count-ne24){throw 'Family count changed.'}
$required=@('frm2552:txtPg1I1Month','frm2552:txtPg1I1Day','frm2552:txtPg1I1Year','frm2552:txtPg1Pt1I6Name','frm2552:txtPg1Pt1I7RegisteredAddress','frm2552:txPg1I7ZipCode','frm2552:txtPg1Pt1I8ContactNumber','frm2552:txtPg1Pt1I9Email',$runtimeScalar)
function Meta([string]$Key,$Control,[bool]$Family,[string]$Logical=''){$page=$null;if($Key-match'(?i)Pg(?<p>\d+)'){$page=[int]$Matches.p};$item=$null;$ims=@([regex]::Matches($Key,'(?i)(?:Itm?|I)(?<i>\d+[A-Z]?)'));if($ims.Count){$item=$ims[-1].Groups['i'].Value};$logical=if($Logical){$Logical}else{'string'};$norm=[string[]]@();$enum=[object[]]@();if(($Control-and$Control.control_kind-in@('radio','checkbox'))-or$Key-match'(?i):(rdo|chk)'){$logical='boolean';$enum=[object[]]@('true','false')}elseif($Key-match'(?i)Email'){$logical='email-string'}elseif($Key-match'(?i)Date|I1Month|I1Day|I1Year'){$logical='date-string-mm-dd-yyyy';$norm=[string[]]@('MM/DD/YYYY')}elseif($Key-match'(?i)(TIN|RDO|Zip|ATC)'){$logical='code'}elseif($Key-match'(?i)(Amount|Amnt|TaxBase|TaxRate|TaxDue|TaxPaid|TaxCred|TaxStll|Penalty|Penalties|Surcharge|Interest|Compromise|NumShares|TotShare)'){$logical='whole-peso-amount';$norm=[string[]]@('NumWithComma','formatCurrency','toFixed(0)')};$computed=$false;if($Control-and($Control.disabled-or$Control.readonly)-and$logical-eq'whole-peso-amount'){$computed=$true};if($Key-match'(?i)(TaxDue|TaxDueTot|TotTax|TotAmnt|TaxStllDue|TotPenalties)$'){$computed=$true};$status=if($required-contains$Key){'required'}elseif($computed){'computed'}else{'optional'};if($Family){$status='conditional';$computed=$false};$constraints=[ordered]@{};if($Control-and$Control.maxlength-match'^\d+$'){$constraints.max_length=[int]$Control.maxlength};if($logical-eq'whole-peso-amount'){$constraints.precision=0;$constraints.sign='signed unless source validation constrains the field'};[pscustomobject]@{page=$page;item=$item;logical=$logical;norm=$norm;enum=$enum;computed=$computed;status=$status;constraints=[pscustomobject]$constraints}}
$fields=[Collections.Generic.List[object]]::new()
foreach($key in $staticIds){$c=$byId[$key];$m=Meta $key $c $false;$fields.Add([pscustomobject][ordered]@{field_key=$key;serialized_key=$key;serialized_occurrence=1;label=if($key-like'frm2552:*'){$key.Substring(8)}else{$key};page=$m.page;item_number=$m.item;control_kind=$c.control_kind;storage_type='string';logical_type=$m.logical;required=$m.status;required_when=$null;enabled_when=$null;visible_when=$null;default_value=$c.value;empty_representation='';constraints=$m.constraints;enum_values=$m.enum;normalization=$m.norm;computed=$m.computed;calculation_id=if($m.computed){'See calculations.json'}else{$null};source_refs=@('official-hta-runtime#saveXML',"official-hta-runtime#control:L$($c.source_line)");confidence='high';notes=@('Source-derived from the hash-pinned January 2018 runtime; no revision-matched final copy is available.')})}
$m=Meta $runtimeScalar $null $false;$fields.Add([pscustomobject][ordered]@{field_key=$runtimeScalar;serialized_key=$runtimeScalar;serialized_occurrence=1;label='Runtime-generated RDO selector';page=1;item_number='5';control_kind='runtime-generated-select';storage_type='string';logical_type='code';required='required';required_when=$null;enabled_when=$null;visible_when=$null;default_value='000';empty_representation='000';constraints=[pscustomobject]@{};enum_values=@();normalization=@();computed=$false;calculation_id=$null;source_refs=@('official-hta-runtime#getRDO:L5948-L5964','official-hta-runtime#saveXML');confidence='high';notes=@('Generated into frmMain at runtime and serialized; distinct from the visible txtPg1I5RDO mirror.')})
foreach($f in $families){$m=Meta $f.field_pattern $null $true $f.logical;$fields.Add([pscustomobject][ordered]@{field_key=$f.field_pattern;serialized_key=$null;serialized_occurrence=$null;label="Runtime-indexed Part V Schedule $($f.schedule) Column $($f.column)";page=2;item_number='5';control_kind='runtime-indexed-family';storage_type='string';logical_type=$m.logical;required='conditional';required_when='The corresponding add-more row exists.';enabled_when='The row exists.';visible_when='The popup row exists.';default_value=$null;empty_representation='';constraints=[pscustomobject]@{index='one-based, source-unbounded'};enum_values=@();normalization=$m.norm;computed=$false;calculation_id=$null;source_refs=@("official-hta-runtime#dynamic-id:L$($f.source_line)",'official-hta-runtime#popup-serialization');confidence='high';notes=@('Source-derived unbounded family.')})}
if($fields.Count-ne262){throw "Expected 262 fields; found $($fields.Count)."}
Write-Json (Join-Path $outDir 'fields.json') ([ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;field_count=$fields.Count;runtime_serializable_element_count=238;inventory_sha256=Hash-Lines @($fields.field_key|Sort-Object);fields=$fields})
Write-Json (Join-Path $fixtureDir 'runtime-control-inventory-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;official_hta_sha256=$expected.hta;live_control_count=$controls.Count;static_serialized_id_count=$staticIds.Count;runtime_generated_scalar_count=1;runtime_generated_scalars=@($runtimeScalar);revision_matched_final_copy_key_count=0;excluded_legacy_sample_key_count=$legacyKeys.Count;excluded_legacy_sample_overlap_with_legacy_runtime=$lo.Count;excluded_legacy_sample_overlap_with_current_runtime=$co.Count;active_runtime_family_count=$families.Count;controls=$controls;dynamic_families=$families})
$fn=Join-Path $RepoRoot 'rules\tools\extract-hta-function-inventory.ps1';Write-Utf8 (Join-Path $fixtureDir 'validation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2552:' -NamePattern '(?i)valid|check|mandatory|save|enable|disable|date|email|submit|final')-join[Environment]::NewLine);Write-Utf8 (Join-Path $fixtureDir 'calculation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2552:' -NamePattern '(?i)compute|amount|sum|format|tax|penalty|interest')-join[Environment]::NewLine)

$rules=[Collections.Generic.List[object]]::new()
function Rule([string]$Id,[string]$Phase,$Order,[string]$Condition,[string[]]$Keys,$Message,[string[]]$Refs,[string]$Assessment='verified-correct',[string]$Official='The branch alerts and stops the active operation.',[string]$Recommended='Retain as a structured revision-aware error.'){$rules.Add([pscustomobject][ordered]@{rule_id=$Id;form_id=$formId;revision=$revision;phase=$Phase;order=$Order;condition=$Condition;fields=$Keys;accepted_behavior='Condition is false; processing continues.';rejected_behavior='The active operation stops unless official_behavior states otherwise.';exact_message=$Message;source_refs=$Refs;evidence_type=@('source');assessment=$Assessment;official_behavior=$Official;recommended_app_behavior=$Recommended;confidence='high';unresolved_questions=@()})}
Rule '2552-validate-001-month' validate 1 'Month equals 00.' @('frm2552:txtPg1I1Month') 'Month field on Page 1 Item 1 is required.' @('official-hta-runtime#checkDatePage1:L4401-L4407')
Rule '2552-validate-002-day' validate 2 'Day is blank.' @('frm2552:txtPg1I1Day') 'Day field on Page 1 Item 1 is required.' @('official-hta-runtime#checkDatePage1:L4409-L4414')
Rule '2552-validate-003-year' validate 3 'Year is blank.' @('frm2552:txtPg1I1Year') 'Year field on Page 1 Item 1 is required.' @('official-hta-runtime#checkDatePage1:L4416-L4421')
Rule '2552-validate-004-date-shape' validate 4 'Transaction date is not a valid MM/DD/YYYY date.' @('frm2552:txtPg1I1Month','frm2552:txtPg1I1Day','frm2552:txtPg1I1Year') 'Please provide a valid date. (MM/DD/YYYY format) in Page 1 Item 1.' @('official-hta-runtime#dateInPage1Item1:L4638-L4715')
Rule '2552-validate-005-date-future' validate 5 'Transaction date is after today.' @('frm2552:txtPg1I1Month','frm2552:txtPg1I1Day','frm2552:txtPg1I1Year') 'Page 1 Item 1 Date cannot be a future date ' @('official-hta-runtime#dateInPage1Item1:L4716-L4721')
Rule '2552-validate-006-year-range' 'blur/change' 1 'Year is before 2018 or after current year.' @('frm2552:txtPg1I1Year') 'Year shall not be greater than the present year and not earlier than 2018.' @('official-hta-runtime#checkYear:L4945-L4957')
Rule '2552-validate-007-rdo' validate 6 'Visible RDO mirror is 000.' @('frm2552:txtPg1I5RDO') 'Please enter a valid RDO Code on Page 1 Item 5.' @('official-hta-runtime#validateAll:L4360')
Rule '2552-validate-008-name' validate 7 'Name is blank.' @('frm2552:txtPg1Pt1I6Name') 'Name field on Page 1 Item 6 is required.' @('official-hta-runtime#validateAll:L4361')
Rule '2552-validate-009-address' validate 8 'Registered address is blank.' @('frm2552:txtPg1Pt1I7RegisteredAddress') 'Registered Address field on Page 1 Item 7 is required.' @('official-hta-runtime#validateAll:L4362')
Rule '2552-validate-010-zip' validate 9 'Zip is blank.' @('frm2552:txPg1I7ZipCode') 'Zip Code field on Page 1 Item 7A is required.' @('official-hta-runtime#validateAll:L4363')
Rule '2552-validate-011-contact' validate 10 'Contact is blank.' @('frm2552:txtPg1Pt1I8ContactNumber') 'Contact Number field on Page 1 Item 8 is required.' @('official-hta-runtime#validateAll:L4364')
Rule '2552-validate-012-email-required' validate 11 'Email is blank.' @('frm2552:txtPg1Pt1I9Email') 'E-mail address on page 1 item 9 is required.' @('official-hta-runtime#validateAll:L4365')
Rule '2552-validate-013-tax-relief-spec' validate 12 'Tax Relief Yes is selected and specification is blank.' @('frm2552:rdoPg1I10TaxReliefYes','frm2552:txtPg1Pt1I10TaxReliefSpec') 'Specify Tax Relief field on Page 1 Item 10A is required.' @('official-hta-runtime#validateAll:L4367-L4372')
Rule '2552-validate-014-transaction-kind' validate 13 'No transaction kind is selected.' @('frm2552:rdoPg1I11TransactionLSE','frm2552:rdoPg1I11TransactionPrimary','frm2552:rdoPg1I11TransactionSecondary') 'Select an option for Page 1 Item 11 Kind of Transaction.' @('official-hta-runtime#validateAll:L4374-L4378')
Rule '2552-validate-015-share-counts' validate 14 'Primary or secondary offering is selected and Item 12A or 12B is blank.' @('frm2552:txtPg1Pt1I12NumOfShare','frm2552:txtPg1Pt1I12TotShare') 'Page 1 Item 12A and 12B cannot not be empty.' @('official-hta-runtime#validateAll:L4379-L4386') 'official-bug-compatible' 'The official message contains the double negative “cannot not”.' 'Use “cannot be empty”.'
Rule '2552-validate-016-overpayment' validate 15 'Item 20 is negative and neither overpayment option is selected.' @('frm2552:txtPg1P2I20TotTaxStllDueOvrPmnt','frm2552:rdoPg1OverpaymentRefund','frm2552:rdoPg1OverpaymentTaxCredCert') 'Select an Overpayment option in Page 1 after Item 25.' @('official-hta-runtime#validateAll:L4388-L4394')
Rule '2552-validate-017-part4' validate 16 'A Part IV row has transaction class without amount or amount without class.' @('frm2552:txtPg2P4I1TransClass','frm2552:txtPg2P4I1Amount') 'Please complete Item #{row} in Part IV Page 2.' @('official-hta-runtime#checkPartIVFields:L4473-L4492')
Rule '2552-validate-018-part5-sch1' validate 17 'A Schedule 1 row incompletely mixes date/seller/buyer/corporation with shares or tax base.' @('Part-V-Schedule-1-fixed-fields') 'Please complete Item #{row} in Page 2 Part V Schedule 1.' @('official-hta-runtime#checkPartVSchFields:L4494-L4534')
Rule '2552-validate-019-part5-sch2' validate 18 'A Schedule 2 row incompletely mixes identity fields with shares, tax base, or rate.' @('Part-V-Schedule-2-fixed-fields') 'Please complete Item #{row} in Page 2 Part V Schedule 2.' @('official-hta-runtime#checkPartVSchFields:L4494-L4534')
Rule '2552-validate-020-part5-sch3' validate 19 'A Schedule 3 row incompletely mixes identity fields with shares, tax base, or rate.' @('Part-V-Schedule-3-fixed-fields') 'Please complete Item #{row} in Page 2 Part V Schedule 3.' @('official-hta-runtime#checkPartVSchFields:L4494-L4534')
Rule '2552-validate-021-part6' validate 20 'A Part VI row incompletely mixes identity fields with number of shares.' @('Part-VI-fixed-fields') 'Please complete Item #{row} in Page 2 Part VI.' @('official-hta-runtime#checkPartVIFields:L4536-L4568')
Rule '2552-popup-022-complete' input 1 'On popup Save/Add, any Part V add-more row lacks date, seller, buyer, corporation, positive shares, tax base, or rate.' @('frm2552:txtPg2Pt5Sch1_{N>=1}Col1','frm2552:txtPg2Pt5Sch1_{N>=1}Col8','frm2552:txtPg2Pt5Sch2_{N>=1}Col1','frm2552:txtPg2Pt5Sch3_{N>=1}Col8') 'Cannot {method}. You have an empty data in 5.{row}' @('official-hta-runtime#CheckEmptyDesc:L3455-L3495')
Rule '2552-email-023-unreachable' validate 21 'Email fails the source regex.' @('frm2552:txtPg1Pt1I9Email') 'Please enter a valid e-mail address on page 1 item 10' @('official-hta-runtime#validateEmail:L4816-L4828','official-hta-runtime#validateAll:L4356-L4399') 'incorrect-official-behavior' 'validateEmail is defined but never called by Validate.' 'Invoke it from the shared validation graph.'
Rule '2552-date-024-invalid' 'blur/change' 2 'A date field is invalid.' @('date-controls') 'Please provide a valid date. (MM/DD/YYYY format)' @('official-hta-runtime#validateDate:L4569-L4636')
Rule '2552-date-025-future-return' 'blur/change' 3 'A valid date is after today.' @('date-controls') 'This date cannot be a future date.' @('official-hta-runtime#validateDate') 'incorrect-official-behavior' 'The field clears but the function returns true.' 'Return false after clearing.'
Rule '2552-rate-026-upper' 'blur/change' 4 'A rate is at least 100.' @('Part-V-rate-fields') 'Tax rate should be below 100.' @('official-hta-runtime#checkRate:L4936-L4943')
Rule '2552-rate-027-negative' 'blur/change' 5 'A rate is negative.' @('Part-V-rate-fields') $null @('official-hta-runtime#checkRate:L4936-L4943') 'incorrect-official-behavior' 'Only the upper bound is enforced.' 'Require a nonnegative rate below 100.'
Rule '2552-save-028-rdo' save 1 'Runtime RDO selector is 000.' @($runtimeScalar) 'Please enter a valid RDO Code on Item 7.' @('official-hta-runtime#initialValidateBeforeSave:L7155-L7161') 'official-bug-compatible' 'Save labels RDO as Item 7 while the printed/Validate item is 5.' 'Use the printed item number consistently.'
Rule '2552-save-029-name' save 2 'Name is blank.' @('frm2552:txtPg1Pt1I6Name') 'Please enter a valid name on Page 1 Item 8' @('official-hta-runtime#initialValidateBeforeSave:L7162') 'official-bug-compatible' 'Save labels the printed Item 6 field as Item 8.' 'Use the printed item number.'
Rule '2552-save-030-address' save 3 'Address is blank.' @('frm2552:txtPg1Pt1I7RegisteredAddress') 'Please enter a valid Registered Address on Page 1 Item 9.' @('official-hta-runtime#initialValidateBeforeSave:L7163') 'official-bug-compatible' 'Save labels the printed Item 7 field as Item 9.' 'Use the printed item number.'
Rule '2552-save-031-contact' save 4 'Contact is blank.' @('frm2552:txtPg1Pt1I8ContactNumber') 'Please enter a valid Contact Number on Page 1 Item 11' @('official-hta-runtime#initialValidateBeforeSave:L7164') 'official-bug-compatible' 'Save labels the printed Item 8 field as Item 11.' 'Use the printed item number.'
Rule '2552-save-032-sparse' save 5 'Any other Validate rule fails.' @() $null @('official-hta-runtime#initialValidateBeforeSave:L7155-L7167','official-hta-runtime#validateAll:L4356-L4399') 'incorrect-official-behavior' 'Save checks date, RDO, name, address, and contact only.' 'Use a shared validation graph with explicit phase exceptions.'
Write-Json (Join-Path $outDir 'validations.json') ([ordered]@{'$schema'='../../schema/validations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;first_error_behavior='Validate stops at the first source-ordered failure; Save uses a narrower graph; popup completeness runs on modal add/save.';rules=$rules})

$calcs=[Collections.Generic.List[object]]::new()
function Calc([string]$Id,[string[]]$Out,[string[]]$In,[string]$Formula,[string]$Trigger,[string[]]$Deps,[string[]]$Refs,[string]$Assessment='verified-correct',[string]$Recommended='Implement with typed decimals and the official whole-peso rounding order.'){$calcs.Add([pscustomobject][ordered]@{calculation_id=$Id;outputs=$Out;inputs=$In;condition=$null;official_formula=$Formula;rounding='toFixed(0), then formatCurrency.';trigger=$Trigger;depends_on=$Deps;source_refs=$Refs;assessment=$Assessment;recommended_app_behavior=$Recommended;confidence='high'})}
Calc '2552-popup-row-tax' @('frm2552:txtPg2Pt5Sch{1..3}_{N>=1}Col8') @('frm2552:txtPg2Pt5Sch{1..3}_{N>=1}Col6','frm2552:txtPg2Pt5Sch{1..3}_{N>=1}Col7') 'Tax due = tax base × rate / 100; Schedule 1 rate is fixed at 0.6%.' Sum_Pg2Pt5AddMore @() @('official-hta-runtime#Sum_Pg2Pt5AddMore:L3890-L3912')
Calc '2552-popup-subtotals' @('Pg2Pt5Sch1SubTotal','Pg2Pt5Sch2SubTotal','Pg2Pt5Sch3SubTotal') @('frm2552:txtPg2Pt5Sch{1..3}_{N>=1}Col8') 'Sum add-more tax-due rows per schedule.' Sum_Pg2Pt5AddMore @('2552-popup-row-tax') @('official-hta-runtime#Sum_Pg2Pt5AddMore:L3890-L3915')
Calc '2552-fixed-row-tax' @('frm2552:txtPg2Pt5Sch{1..3}TaxDue{1..5}') @('frm2552:txtPg2Pt5Sch{1..3}TaxBase{1..5}','frm2552:txtPg2Pt5Sch{2..3}TaxRate{1..5}') 'Tax due = tax base × rate / 100; Schedule 1 uses 0.6%.' pageTwoComputation @() @('official-hta-runtime#pageTwoComputation:L5023-L5038')
Calc '2552-schedule-totals' @('frm2552:txtPg2Pt5Sch1TaxDueTot','frm2552:txtPg2Pt5Sch2TaxDueTot','frm2552:txtPg2Pt5Sch3TaxDueTot') @('frm2552:txtPg2Pt5Sch{1..3}TaxDue{1..5}') 'Sum five displayed tax-due rows per schedule; row 5 carries popup subtotal when used.' totTaxDueComp @('2552-popup-subtotals','2552-fixed-row-tax') @('official-hta-runtime#totTaxDueComp:L5012-L5021')
Calc '2552-page1-schedule-copies' @('frm2552:txtPg1P2I13TaxDue','frm2552:txtPg1P2I14TaxDue','frm2552:txtPg1P2I15TaxDue') @('frm2552:txtPg2Pt5Sch1TaxDueTot','frm2552:txtPg2Pt5Sch2TaxDueTot','frm2552:txtPg2Pt5Sch3TaxDueTot') 'Copy Schedule 1/2/3 totals to Items 13/14/15.' pageTwoSchedTotalToPageOne @('2552-schedule-totals') @('official-hta-runtime#pageTwoSchedTotalToPageOne:L5040-L5055')
Calc '2552-item16-total-tax' @('frm2552:txtPg1P2I16TotTaxDue') @('frm2552:txtPg1P2I13TaxDue','frm2552:txtPg1P2I14TaxDue','frm2552:txtPg1P2I15TaxDue') 'Item 16 = Items 13 + 14 + 15.' pageOneComputation @('2552-page1-schedule-copies') @('official-hta-runtime#pageOneComputation:L4969-L4975')
Calc '2552-item19-credits' @('frm2552:txtPg1P2I19TotTaxCredPmnt') @('frm2552:txtPg1P2I17TaxPaidInPrevRtrn','frm2552:txtPg1P2I18CredTaxWthhld') 'Item 19 = Items 17 + 18.' pageOneComputation @() @('official-hta-runtime#pageOneComputation:L4977-L4982')
Calc '2552-item20-balance' @('frm2552:txtPg1P2I20TotTaxStllDueOvrPmnt') @('frm2552:txtPg1P2I16TotTaxDue','frm2552:txtPg1P2I19TotTaxCredPmnt') 'Item 20 = Item 16 - Item 19.' pageOneComputation @('2552-item16-total-tax','2552-item19-credits') @('official-hta-runtime#pageOneComputation:L4984-L4989')
Calc '2552-item24-penalties' @('frm2552:txtPg1P2I24TotPenalties') @('frm2552:txtPg1P2I21Surcharge','frm2552:txtPg1P2I22Interest','frm2552:txtPg1P2I23Compromise') 'Item 24 = surcharge + interest + compromise.' pageOneComputation @() @('official-hta-runtime#pageOneComputation:L4991-L4997')
Calc '2552-item25-payable' @('frm2552:txtPg1P2I25TotAmntPyable') @('frm2552:txtPg1P2I20TotTaxStllDueOvrPmnt','frm2552:txtPg1P2I24TotPenalties') 'If balance is negative and penalties positive, Item 25 = penalties; otherwise balance + penalties.' pageOneComputation @('2552-item20-balance','2552-item24-penalties') @('official-hta-runtime#pageOneComputation:L4999-L5011') 'incorrect-official-behavior' 'A negative balance with zero penalties produces a negative amount payable; represent overpayment separately and payable as zero.'
Write-Json (Join-Path $outDir 'calculations.json') ([ordered]@{'$schema'='../../schema/calculations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;evaluation_order=@($calcs.calculation_id);calculations=$calcs})
$cases=@();$n=0;foreach($r in @($rules|Where-Object{$_.exact_message})){$n++;$cases+=[pscustomobject][ordered]@{case_id=('case-{0:d2}-{1}'-f$n,$r.rule_id);phase=$r.phase;mutations=@{synthetic_condition=$r.condition};expected_message=$r.exact_message;expected_behavior=$r.official_behavior;rule_id=$r.rule_id}}
Write-Json (Join-Path $fixtureDir 'negative-cases.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;synthetic_only=$true;cases=$cases})
Write-Json (Join-Path $fixtureDir 'calculation-boundaries.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;cases=@(@{case_id='lse-rate';calculation_id='2552-fixed-row-tax';tax_base=100000;rate=0.6;official_output=600},@{case_id='ipo-rate';calculation_id='2552-fixed-row-tax';tax_base=100000;rate=4;official_output=4000},@{case_id='negative-payable';calculation_id='2552-item25-payable';balance=-100;penalties=0;official_output=-100;recommended_output=0})})
$resources=@();foreach($src in @([regex]::Matches($hta,'(?i)<script[^>]+src\s*=\s*(["''])(?<v>.*?)\1')|ForEach-Object{$_.Groups['v'].Value}|Sort-Object -Unique)){$full=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $htaPath) $src));if(Test-Path -LiteralPath $full){$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$true;size=(Get-Item -LiteralPath $full).Length;sha256=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()}}else{$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$false;size=$null;sha256=$null}}};Write-Json (Join-Path $fixtureDir 'official-resource-hashes-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;resources=$resources})

$deadline='LSE and secondary offerings: within five banking days from collection; primary offering: within thirty days from listing.'
$workflow=[ordered]@{'$schema'='../../schema/workflow.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;phases=@(
 @{phase='edit';official_behavior='January 2018 stock-transaction tax return with Part V LSE/primary/secondary schedules.';source_refs=@('official-hta-runtime','official-form-pdf','official-guide-pdf');confidence='high'},@{phase='saved-draft';official_behavior='Save runs a narrow date/identity graph before serializing static, RDO, and popup controls.';source_refs=@('official-hta-runtime#initialValidateBeforeSave:L7155-L7167','official-hta-runtime#saveXML');confidence='high'},@{phase='validated';official_behavior='Validate checks identity, transaction kind, overpayment disposition, and Parts IV–VI.';source_refs=@('official-hta-runtime#validateAll:L4356-L4399');confidence='high'},@{phase='final-copy';official_behavior='Encryption exists, but no January 2018 final copy is available.';source_refs=@('official-hta-runtime#saveXML');confidence='medium'},@{phase='submitted';official_behavior='Online/EFPS transport exists but was not exercised.';source_refs=@('official-hta-runtime#submitOnline','official-hta-runtime#submitToEFPS');confidence='medium'}
);transitions=@(
 @{from='edit';action='Save';to='saved-draft';guard='Sparse Save checks pass.';side_effects=@('Writes flat pseudo-XML.','Serializes runtime rows.');source_refs=@('official-hta-runtime#saveXML')},@{from='edit';action='Validate';to='validated';guard='All validateAll checks pass.';side_effects=@('Disables controls.','Enables final-copy actions.');source_refs=@('official-hta-runtime#validate')},@{from='validated';action='Edit';to='edit';guard=$null;side_effects=@('Re-enables controls conditionally.');source_refs=@('official-hta-runtime#enableAllControl')},@{from='validated';action='Final Copy';to='final-copy';guard='Finalization succeeds.';side_effects=@('Encrypts/compresses the copy.');source_refs=@('official-hta-runtime#saveXML')},@{from='final-copy';action='Transport';to='submitted';guard='Connectivity and acceptance succeed.';side_effects=@('Untested online attempt.');source_refs=@('official-hta-runtime#submitOnline')}
);prerequisites=@('Transaction date','RDO and identity','Tax-relief specification when applicable','Transaction kind and share counts','Complete Parts IV–VI','Overpayment disposition when applicable');required_attachments=@(
 @{attachment_id='bir-2307';label='Certificate of Creditable Tax Withheld at Source (BIR Form 2307), if applicable.';required_when='Creditable withholding applies.';official_ui_enforcement='Not enforced.';source_refs=@('packaged-help#L231-L239');confidence='medium'},@{attachment_id='supporting-documents';label='Proof of exemption, approved Tax Debit Memo, and amended-return payment/return when applicable.';required_when='Corresponding condition applies.';official_ui_enforcement='Not enforced.';source_refs=@('packaged-help#L231-L239');confidence='medium'}
);filing_deadlines=@(@{quarter='Q1';due_date_rule=$deadline;source_refs=@('packaged-help#L183-L190','official-guide-pdf');confidence='high'},@{quarter='Q2';due_date_rule=$deadline;source_refs=@('packaged-help#L183-L190','official-guide-pdf');confidence='high'},@{quarter='Q3';due_date_rule=$deadline;source_refs=@('packaged-help#L183-L190','official-guide-pdf');confidence='high'},@{quarter='Q4';due_date_rule=$deadline;source_refs=@('packaged-help#L183-L190','official-guide-pdf');confidence='high'})}
Write-Json (Join-Path $outDir 'workflow.json') $workflow
$bugs=@($rules|Where-Object{$_.assessment-in@('official-bug-compatible','incorrect-official-behavior','obsolete')}).Count
$assets=@(Asset 'package-7.9.6' 'official-package-executable' $packagePath 'Installed package 7.9.6.0.';Asset 'official-hta-runtime' 'runtime-extracted-hta' $htaPath 'January 2018 ENCS runtime.';Asset 'legacy-1999-excluded' 'runtime-extracted-hta' $legacyPath 'July 1999 predecessor, excluded.';Asset 'packaged-help' 'official-runtime-help' $helpPath 'Unversioned packaged help; deadlines/attachments used, legacy rate text not used for January 2018 calculations.';Asset 'official-form-pdf' 'official-form-pdf' $pdfPath 'January 2018 ENCS form.';Asset 'official-guide-pdf' 'official-guidelines-pdf' $guidePath 'January 2018 guidelines.';Asset 'legacy-encrypted-sample-excluded' 'dummy-profile-encrypted-final-copy' $sample[0].FullName 'Excluded: all 61 keys match July 1999; only 6 match January 2018.' (Join-Path $SampleDir '2552-final-copy-#email-redacted#.xml'))
$manifest=[ordered]@{'$schema'='../../schema/form-manifest.schema.json';schema_version='1.0.0';form_id=$formId;form_code='2552';revision=$revision;package_version=$packageVersion;status='complete';official_assets=$assets;counts=[ordered]@{concrete_fields=238;runtime_field_families=24;fields_total=$fields.Count;typed_fields=$fields.Count;validation_rules=$rules.Count;confirmed_official_bugs=$bugs;calculations=$calcs.Count;negative_fixtures=$cases.Count;unverified_gaps=2};artifacts=[ordered]@{fields='fields.json';validations='validations.json';calculations='calculations.json';workflow='workflow.json';evidence='evidence.md';audit='audit.md';gaps='gaps.md';excluded_legacy_encrypted_keys='fixtures/excluded-legacy-encrypted-field-keys-v796.json';runtime_controls='fixtures/runtime-control-inventory-v796.json';validation_functions='fixtures/validation-function-inventory-v796.json';calculation_functions='fixtures/calculation-function-inventory-v796.json';resources='fixtures/official-resource-hashes-v796.json';negative_fixtures='fixtures/negative-cases.json';calculation_fixtures='fixtures/calculation-boundaries.json'};scope_notes=@('Research only; no renderer/release metadata changed.','No decrypted values or email-bearing filenames emitted.','Legacy sample excluded.','237 static controls + runtime RDO selector + 24 unbounded schedule families preserved.')}
Write-Json (Join-Path $outDir 'manifest.json') $manifest;Write-Utf8 (Join-Path $outDir 'README.md') "# BIR Form 2552 - January 2018`n`nRevision-specific package with 238 concrete fields and 24 unbounded schedule families.`n"
Write-Utf8 (Join-Path $outDir 'evidence.md') "# Evidence`n`n- January 2018 runtime: $($expected.hta).`n- July 1999 predecessor: $($expected.legacy), excluded.`n- Form PDF: $($expected.pdf); guide: $($expected.guide).`n- Sample: ciphertext $($expected.cipher), decrypted $($expected.plain), 61 keys, inventory $($expected.inventory); values never emitted.`n- All 61 keys overlap July 1999; only 6 overlap January 2018. Sample excluded.`n- Inventory: 237 static serialized controls, one runtime RDO selector, 24 unbounded families.`n`nAll email-bearing filenames use `#email-redacted#`.`n"
Write-Utf8 (Join-Path $outDir 'gaps.md') "# Gaps`n`n1. No revision-matched January 2018 encrypted final copy is available; the supplied sample is proven legacy and excluded.`n2. Online/EFPS submission was not exercised.`n"
Write-Utf8 (Join-Path $outDir 'audit.md') "# Audit`n`n- January 2018 revision separation: pass.`n- Legacy sample excluded: 61/61 legacy versus 6/61 current overlap.`n- Typed inventory: 238 concrete + 24 families = $($fields.Count).`n- Validations: $($rules.Count); calculations: $($calcs.Count); negative fixtures: $($cases.Count); official defects: $bugs.`n- Full structural/schema audit must run after generation.`n- No renderer/release/capability/commit/push changes.`n"
$indexPath=Join-Path $RepoRoot 'rules\index.json';$index=Get-Content -Raw -LiteralPath $indexPath|ConvertFrom-Json;$entry=$index.forms|Where-Object{$_.form_id-eq$formId};if($entry){$entry.form_code='2552';$entry.revision=$revision;$entry.package_version=$packageVersion;$entry.priority=29;$entry.status='complete';$entry.path='forms/2552-v2018/manifest.json'}else{$index.forms+=[pscustomobject][ordered]@{form_id=$formId;form_code='2552';revision=$revision;package_version=$packageVersion;priority=29;status='complete';path='forms/2552-v2018/manifest.json'}};$index.forms=@($index.forms|Sort-Object priority);$index.updated='2026-07-23';Write-Json $indexPath $index
[pscustomobject]@{form_id=$formId;concrete_fields=238;families=24;typed_fields=$fields.Count;validations=$rules.Count;calculations=$calcs.Count;negative_fixtures=$cases.Count;confirmed_official_bugs=$bugs;next_form='2553'}|ConvertTo-Json
