param(
 [string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),
 [string]$ExtractedRoot='C:\Users\uriah\AppData\Local\Temp\{68379049-6E6C-4478-A2C5-EF7B77ED7E38}',
 [string]$OfficialDir='C:\Mac\Home\Downloads\forms\2200Sv2018',
 [string]$SampleDir='C:\Mac\Home\Downloads\forms\2200S'
)
$ErrorActionPreference='Stop';$formId='2200s-v2018';$revision='2018-01-01';$packageVersion='7.9.6.0'
$htaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2200S.hta';$helpPath=Join-Path $ExtractedRoot 'helpfile\Help2200S.hta'
$guidePath=Join-Path $OfficialDir '2200-S Jan 2018 Guide revised.pdf';$pdfPath=Join-Path $OfficialDir '2200-S Jan 2018 rev2.pdf';$packagePath='C:\eBIRForms\BIRForms.exe'
$outDir=Join-Path $RepoRoot 'rules\forms\2200s-v2018';$fixtureDir=Join-Path $outDir 'fixtures'
$expected=@{hta='2ccf624c87c8a951443630a0803e5f1f4bd7800bceb850ff14e8160f5f6b59fd';help='e591320154a6eeb68f1f7d983d39e0c89b933cf413a1c4d4f01552ab982eae2f';guide='968ce5e240cfb1ad53ec831d5cd6a94493087bdeefaac88b0d536938cc784062';pdf='2626eab0f2681bd811d12ae6ed60e177d1961e4f462be5ed453d674f3418671b';package='de8ef0815509d65189e6794e1f8135a5ecf5f2800005d1fc5c87043efd96dbca';cipher='68108a0a92dd9951e90eba4b56d54e8f2bbbbaefafadc0802a17fad59cfc0bdc';plain='675d4de1b887d82af009ee5de0be04758c134994d46e32c4e5c67bdb6c53b3dc';inventory='12ee41afde632c9e3d31a4d7bda1f16caa307c0c87e563a1f1fd2f22335476e1'}
function WJ($p,$v){[IO.File]::WriteAllText($p,(($v|ConvertTo-Json -Depth 60)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function WT($p,$v){[IO.File]::WriteAllText($p,$v,[Text.UTF8Encoding]::new($false))}
function HL([string[]]$l){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes(($l-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Attr($t,$n){$m=[regex]::Match($t,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($n)));if($m.Success){$m.Groups[2].Value}else{$null}}
function Asset($id,$kind,$path,$binding,$display=''){$i=Get-Item -LiteralPath $path;[pscustomobject][ordered]@{asset_id=$id;kind=$kind;path=if($display){$display}else{$path};sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();size=$i.Length;revision_binding=$binding}}
foreach($pair in @(@($htaPath,'hta'),@($helpPath,'help'),@($guidePath,'guide'),@($pdfPath,'pdf'),@($packagePath,'package'))){if(-not(Test-Path -LiteralPath $pair[0] -PathType Leaf)){throw"Missing $($pair[0])"};if((Get-FileHash -LiteralPath $pair[0] -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected[$pair[1]]){throw"Hash changed: $($pair[0])"}}
$sample=@(Get-ChildItem -LiteralPath $SampleDir -File -Filter '*.xml');if($sample.Count-ne1){throw "Expected one sample; found $($sample.Count)."};if((Get-FileHash -LiteralPath $sample[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected.cipher){throw 'Sample hash changed.'}
$hta=[IO.File]::ReadAllText($htaPath);$help=[IO.File]::ReadAllText($helpPath);if($hta-notmatch'APPLICATIONNAME="2200S"'-or$hta-notmatch'January 2018'){throw 'January 2018 binding changed.'};if($help-notmatch'(?i)sweetened beverages'-or$help-notmatch'(?i)before removal'){throw 'Help binding changed.'};foreach($p in @($guidePath,$pdfPath)){$b=[IO.File]::ReadAllBytes($p);if([Text.Encoding]::ASCII.GetString($b[0..4])-ne'%PDF-'){throw "PDF magic mismatch: $p"}};New-Item -ItemType Directory -Force -Path $fixtureDir|Out-Null
$redacted=Join-Path $SampleDir '2200S-final-copy-#email-redacted#.xml';$kt=Join-Path $RepoRoot 'rules\tools\extract-encrypted-field-keys.ps1'
$keyJson=&$kt -SourcePath $sample[0].FullName -RedactedSourcePath $redacted -FormId $formId -ExpectedCiphertextSha256 $expected.cipher -ExpectedDecryptedSha256 $expected.plain -ExpectedFieldCount 118 -ExpectedFieldInventorySha256 $expected.inventory
$ka=$keyJson|ConvertFrom-Json;$keys=@($ka.keys);WT (Join-Path $fixtureDir 'encrypted-field-audit-v796.json') ($keyJson-join[Environment]::NewLine)
$fm=[regex]::Match($hta,'(?is)<form\b[^>]*(?:id|name)\s*=\s*["'']frmMain["''][^>]*>(?<body>.*?)</form>');if(-not$fm.Success){throw 'frmMain missing.'};$body=$fm.Groups['body'].Value;$offset=$fm.Groups['body'].Index;$excluded=@(@([regex]::Matches($body,'(?is)<script\b.*?</script>'))+@([regex]::Matches($body,'(?is)<!--.*?-->')))
$controls=[Collections.Generic.List[object]]::new();$ord=0;foreach($m in [regex]::Matches($body,'(?is)<(input|select|textarea|button)\b[^>]*>')){$skip=$false;foreach($r in $excluded){if($m.Index-ge$r.Index-and$m.Index-lt($r.Index+$r.Length)){$skip=$true;break}};if($skip){continue};$ord++;$tag=$m.Value;$el=$m.Groups[1].Value.ToLowerInvariant();$kind=if($el-eq'input'){Attr $tag 'type'}else{$el};if(-not$kind){$kind='text'};$kind=$kind.ToLowerInvariant();$def=Attr $tag 'value';if($kind-in@('radio','checkbox')){$def=if($tag-match'(?i)\bchecked(?:\s*=|\s|>)'){'true'}else{'false'}};$controls.Add([pscustomobject][ordered]@{ordinal=$ord;id=Attr $tag 'id';name=Attr $tag 'name';element=$el;control_kind=$kind;source_line=1+[regex]::Matches($hta.Substring(0,$offset+$m.Index),"`n").Count;default_value=$def;maxlength=Attr $tag 'maxlength';disabled=$tag-match'(?i)\bdisabled(?:\s*=|\s|>)';readonly=$tag-match'(?i)\breadonly(?:\s*=|\s|>)'})}
$serial=@($controls|Where-Object{$_.control_kind-in@('text','select','select-one','textarea','radio','checkbox')-and$_.id});$by=@{};foreach($c in $serial){if(-not$by.ContainsKey($c.id)){$by[$c.id]=$c}};$missing=@($keys|Where-Object{-not$by.ContainsKey($_)});$runtimeRdo='frm2200S:txtRDOCode';$runtimeRdoMatches=@($missing|Where-Object{$_-eq$runtimeRdo});$runtimeFixedKeys=[Collections.Generic.List[string]]::new();$runtimeControls=@{$runtimeRdo=[pscustomobject]@{control_kind='select-one';default_value='';maxlength=$null;source_line=8000}};for($i=0;$i-le9;$i++){foreach($stem in @('txtSalesValue','txtVolumeRemovals','txtBasicTaxDue')){$key="frm2200S:$stem$i";$runtimeFixedKeys.Add($key);$runtimeControls[$key]=[pscustomobject]@{control_kind='text';default_value='0.00';maxlength='25';source_line=if($stem-eq'txtSalesValue'){6971}elseif($stem-eq'txtVolumeRemovals'){6972}else{6973}}}};$runtimeFixedMatches=@($missing|Where-Object{$runtimeFixedKeys-contains$_});$unexpectedMissing=@($missing|Where-Object{$_-ne$runtimeRdo-and$runtimeFixedKeys-notcontains$_});$sampleExtra=@($serial.id|Where-Object{$keys-notcontains$_})
$familyNames=@('sched1Chk','txtsched1Atc','txtsched1Desc','txtsched1TaxBracket','txtsched1AppTaxRate','txtsched1SalesValue','txtsched1VolumeRemovals','txtsched1BasicTaxDue')
$required=@('frm2200S:txtMonth1','frm2200S:txtDate','frm2200S:txtForYr','frm2200S:txtTIN1','frm2200S:txtTIN2','frm2200S:txtTIN3','frm2200S:txtBranchCode',$runtimeRdo,'frm2200S:taxpayerName','frm2200S:txtAddress','frm2200S:txtZipCode','frm2200S:txtTelNum','frm2200S:txtLineBus','frm2200S:txtPSIC','txtEmail','frm2200SoptRegion','frm2200SoptProvince','frm2200SoptCity','frm2200SoptRegion1','frm2200SoptProvince1','frm2200SoptCity1')
$computed=@('frm2200S:totalTaxDue','frm2200S:txtTax16','frm2200S:txtTax17C','frm2200S:txtTax18','frm2200S:txtTax20','frm2200S:txtTax21D','frm2200S:txtTax22','frm2200S:txtTax23B','frm2200S:txtTax23C','frm2200S:txtTax24')
for($i=0;$i-le9;$i++){$computed+="frm2200S:txtBasicTaxDue$i"};$computed+='frm2200S:txtsched1BasicTaxDue0'
function F($key,$c){$kind=if($c){$c.control_kind}else{'runtime-generated-select'};$logical=if($kind-in@('radio','checkbox')){'boolean'}elseif($key-match'(?i)(TIN|RDO|ATC|Zip|PSIC|Month|ForYr|Region|Province|City)'){'code'}elseif($key-match'(?i)(Tax|Amount|SalesValue|Volume|Rate|Bracket)'){'decimal-amount'}else{'string'};$comp=$computed-contains$key;$status=if($comp){'computed'}elseif($required-contains$key){'required'}else{'optional'};$req=$null;if($key-eq'frm2200S:lstTaxTreaty'){$status='conditional';$req='Tax Treaty Yes is selected.'};if($key-eq'frm2200S:txtOthMannerofPymnt'){$status='conditional';$req='Other payment manner is selected.'};$cons=[ordered]@{};if($c-and$c.maxlength-match'^\d+$'){$cons.max_length=[int]$c.maxlength};if($logical-eq'decimal-amount'){$cons.precision=2;$cons.sign='source-dependent'};$enum=[object[]]::new(0);if($logical-eq'boolean'){$enum=[object[]]@('true','false')};$norm=[string[]]::new(0);if($logical-eq'decimal-amount'){$norm=[string[]]@('NumWithComma','roundDownComputation','formatCurrency')};[pscustomobject][ordered]@{field_key=$key;serialized_key=$key;serialized_occurrence=1;label=$key;page=if($key-match'(?i)Sched1|SalesValue|VolumeRemovals|BasicTaxDue|totalTaxDue'){2}else{1};item_number=if($key-match'txtTax(\d+[A-D]?)'){$Matches[1]}elseif($key-match'(?i)Sched1|SalesValue|VolumeRemovals|BasicTaxDue|totalTaxDue'){'Schedule 1'}else{$null};control_kind=$kind;storage_type='string';logical_type=$logical;required=$status;required_when=$req;enabled_when=$null;visible_when=$null;default_value=if($c){$c.default_value}else{'000'};empty_representation='';constraints=[pscustomobject]$cons;enum_values=$enum;normalization=$norm;computed=$comp;calculation_id=if($comp){'See calculations.json'}else{$null};source_refs=@("xml-encrypted-v1#decrypted-field:$key","official-hta-runtime#control:L$(if($c){$c.source_line}else{8000})");confidence='high';notes=@('Present in the revision-matched encrypted dummy final-copy inventory; value excluded.')}}
$fields=[Collections.Generic.List[object]]::new();foreach($k in $keys){$c=if($by.ContainsKey($k)){$by[$k]}elseif($runtimeControls.ContainsKey($k)){$runtimeControls[$k]}else{$null};$fields.Add((F $k $c))}
foreach($n in $familyNames){$k="frm2200S:$n{n>=1}";$logical=if($n-like'*Chk'){'boolean'}elseif($n-match'Atc'){'code'}elseif($n-match'Desc'){'string'}else{'decimal-amount'};$enum=[object[]]::new(0);if($logical-eq'boolean'){$enum=[object[]]@('true','false')};$norm=[string[]]::new(0);if($logical-eq'decimal-amount'){$norm=[string[]]@('NumWithComma','roundDownComputation')};$fields.Add([pscustomobject][ordered]@{field_key=$k;serialized_key=$k;serialized_occurrence=1;label=$k;page=2;item_number='Schedule 1 Others dynamic row';control_kind=if($n-like'*Chk'){'checkbox'}else{'text'};storage_type='string';logical_type=$logical;required='conditional';required_when='Dynamic Others row exists; ATC, description, bracket, rate and volume are required.';enabled_when=$null;visible_when='Dynamic row n exists.';default_value='';empty_representation='';constraints=[pscustomobject]@{index_minimum=1;unbounded=$true};enum_values=$enum;normalization=$norm;computed=$n-match'BasicTaxDue';calculation_id=if($n-match'BasicTaxDue'){'2200s-dynamic-basic-tax'}else{$null};source_refs=@('official-hta-runtime#sched1Fields:L7284-L7307','official-hta-runtime#saveXML');confidence='high';notes=@('Unbounded runtime family; row zero is concrete in the encrypted inventory.')})}
WJ (Join-Path $outDir 'fields.json') ([ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;field_count=$fields.Count;runtime_serializable_element_count=118;inventory_sha256=HL @($fields.field_key|Sort-Object);fields=$fields})
WJ (Join-Path $fixtureDir 'runtime-control-inventory-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;official_hta_sha256=$expected.hta;live_control_count=$controls.Count;static_serialized_count=$serial.Count;sample_key_count=$keys.Count;sample_static_id_match_count=$keys.Count-$missing.Count;runtime_rdo_match_count=$runtimeRdoMatches.Count;runtime_fixed_schedule_match_count=$runtimeFixedMatches.Count;unexpected_sample_missing_count=$unexpectedMissing.Count;static_controls_absent_from_sample_count=$sampleExtra.Count;runtime_family_count=$familyNames.Count;runtime_families=@($familyNames|ForEach-Object{"frm2200S:$_{n>=1}"});controls=$controls})
$fn=Join-Path $RepoRoot 'rules\tools\extract-hta-function-inventory.ps1';WT (Join-Path $fixtureDir 'validation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200S:' -NamePattern '(?i)valid|check|save|date|final|schedule|atc')-join[Environment]::NewLine);WT (Join-Path $fixtureDir 'calculation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200S:' -NamePattern '(?i)comput|total|tax|penalt|balance|round')-join[Environment]::NewLine)
$rules=[Collections.Generic.List[object]]::new();function Rule($id,$phase,$order,$cond,[string[]]$keys,$msg,[string[]]$refs,$assessment='verified-correct',$official='The branch alerts and stops the active operation.',$recommended='Retain as a structured revision-aware error.'){$rules.Add([pscustomobject][ordered]@{rule_id=$id;form_id=$formId;revision=$revision;phase=$phase;order=$order;condition=$cond;fields=$keys;accepted_behavior='Condition is false; processing continues.';rejected_behavior='The active operation stops unless official_behavior states otherwise.';exact_message=$msg;source_refs=$refs;evidence_type=@('source');assessment=$assessment;official_behavior=$official;recommended_app_behavior=$recommended;confidence='high';unresolved_questions=@()})}
Rule '2200s-validate-001-leap29' validate 1 'February 29 is used in a non-leap filing year.' @('Return-period-fields') 'Filing year is not a leap year.' @('official-hta-runtime#validateForm:L7673-L7681')
Rule '2200s-validate-002-february' validate 2 'February day exceeds 29 under source leap branches.' @('Return-period-fields') 'Invalid date entry on item 1.' @('official-hta-runtime#validateForm:L7682-L7690')
Rule '2200s-validate-003-day-required' validate 3 'Day is blank or numerically zero.' @('frm2200S:txtDate') 'Please enter valid day on item 1.' @('official-hta-runtime#validateForm:L7692-L7697')
Rule '2200s-validate-004-year-required' validate 4 'Year is blank.' @('frm2200S:txtForYr') 'Please enter valid year on item 1.' @('official-hta-runtime#validateForm:L7698-L7702')
Rule '2200s-validate-005-year-floor' validate 5 'Year is numerically below 2013.' @('frm2200S:txtForYr') 'Invalid date entry on Item no.1. Entry should not be lower than 1900.' @('official-hta-runtime#validateForm:L7704-L7708') 'official-bug-compatible' 'The enforced floor is 2013 while the message says 1900 and the printed revision is January 2018.' 'Bind the accepted return period explicitly to the supported revision.'
Rule '2200s-validate-006-day-format' validate 6 'Day has one character.' @('frm2200S:txtDate') 'Please enter a valid day on item 1. Format should be MM/DD/YYYY.' @('official-hta-runtime#validateForm:L7714-L7718')
Rule '2200s-validate-007-day-positive' validate 7 'Day compares below 1.' @('frm2200S:txtDate') 'Please enter a valid day in Item 1.' @('official-hta-runtime#validateForm:L7721-L7724')
Rule '2200s-validate-008-month-length' validate 8 'Day exceeds 31 for a 31-day month or 30 for a 30-day month.' @('Return-period-fields') 'Invalid date entry on Item no.1.' @('official-hta-runtime#validateForm:L7727-L7740')
Rule '2200s-validate-009-future' validate 9 'Composed return date is after today.' @('Return-period-fields') 'Date on Item 1 cannot be a future date.' @('official-hta-runtime#validateForm:L7742-L7747')
$identity=@(@('tin','TIN/branch segment is blank.','Please enter a valid TIN number on Item 4.','frm2200S:txtTIN1'),@('rdo','RDO selectedIndex is zero.','Please enter a valid RDO Code on Item 5.',$runtimeRdo),@('name','Taxpayer name is blank.','Please enter a valid Taxpayer Name on Item 6.','frm2200S:taxpayerName'),@('address','Address is blank.',"Please enter Taxpayer's Registered Address on Item 7.",'frm2200S:txtAddress'),@('zip','ZIP is blank or shorter than four characters.',"Please enter Taxpayer's Zip Code on Item 7A.",'frm2200S:txtZipCode'),@('contact','Contact is blank.','Please enter Contact Number on Item 8.','frm2200S:txtTelNum'),@('business','Main line of business is blank.','Please enter a valid Main Line of Business on Item 9.','frm2200S:txtLineBus'),@('psic','PSIC is blank or shorter than four characters.','Please enter a valid PSIC on Item 10.','frm2200S:txtPSIC'),@('email','Email is blank.','Please enter Email Address on Item 11.','txtEmail'));$o=10;foreach($x in $identity){Rule "2200s-validate-$('{0:d3}'-f$o)-$($x[0])" validate $o $x[1] @($x[3]) $x[2] @('official-hta-runtime#validateForm:L7749-L7793');$o++}
Rule '2200s-validate-019-production' validate 19 'Any production region/province/city selector has selectedIndex below 1.' @('frm2200SoptRegion','frm2200SoptProvince','frm2200SoptCity') 'Please enter values on item no. 12. All entries must not be empty.' @('official-hta-runtime#validateForm:L7794-L7799')
Rule '2200s-validate-020-removal' validate 20 'Any removal region/province/city selector has selectedIndex below 1.' @('frm2200SoptRegion1','frm2200SoptProvince1','frm2200SoptCity1') 'Please enter values on item no. 13. All entries must not be empty.' @('official-hta-runtime#validateForm:L7800-L7805')
Rule '2200s-validate-021-treaty' validate 21 'Treaty Yes is selected and treaty list value is zero.' @('frm2200S:optTreaty_1','frm2200S:lstTaxTreaty') 'Please select If yes, please specify on Item 14A.' @('official-hta-runtime#validateForm:L7808-L7812')
Rule '2200s-validate-022-payment-choice' validate 22 'Neither Actual Removal nor Prepayment is selected.' @('frm2200S:chkPymntManner_1','frm2200S:chkPymntManner_2') 'Please select an option on Part II Manner of Payment' @('official-hta-runtime#validateForm:L7814-L7818')
Rule '2200s-validate-023-payment-other' validate 23 'Other payment is selected and description is blank.' @('frm2200S:chkPymntManner_3','frm2200S:txtOthMannerofPymnt') 'Please enter a value on Item 17.' @('official-hta-runtime#validateForm:L7819-L7823')
Rule '2200s-validate-024-deposit' validate 24 'Prepayment is selected and Item 23A is not positive.' @('frm2200S:chkPymntManner_2','frm2200S:txtTax23A') 'Please enter Tax Payment / Deposit on Item 25A.' @('official-hta-runtime#validateForm:L7825-L7832')
Rule '2200s-validate-025-balance' validate 25 'Item 24 balance is positive.' @('frm2200S:txtTax24','frm2200S:txtTax23A') 'Payment not sufficient to cover amount payable. Please check amount in Item 25C.' @('official-hta-runtime#validateForm:L7834-L7842')
Rule '2200s-validate-026-schedule-required' validate 26 'Actual Removal is selected and neither a fixed row nor Others row has positive volume removals.' @('Schedule-1-volume-fields') 'Please fill up Schedule 1.' @('official-hta-runtime#validateSchedule1:L10485-L10526')
Rule '2200s-schedule-027-atc-required' validate 27 'Others ATC is blank or XB.' @('frm2200S:txtsched1Atc{n}') 'Please enter a valid ATC in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7180-L7186')
Rule '2200s-schedule-028-atc-prefix' validate 28 'Others ATC does not begin XB.' @('frm2200S:txtsched1Atc{n}') 'The supplied ATC code in "Others" at Row {row} should start with ''XB''.' @('official-hta-runtime#isValidDataOnSched1:L7187-L7194')
Rule '2200s-schedule-029-atc-fixed' validate 29 'Others ATC duplicates XB010..XB100 fixed table codes.' @('frm2200S:txtsched1Atc{n}') 'Please enter a valid ATC code in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7194-L7200')
Rule '2200s-schedule-030-description' validate 30 'Others description is blank.' @('frm2200S:txtsched1Desc{n}') 'Please enter a Description in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7202-L7207')
Rule '2200s-schedule-031-bracket' validate 31 'Others tax bracket is blank.' @('frm2200S:txtsched1TaxBracket{n}') 'Please enter a Tax Bracket in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7208-L7213')
Rule '2200s-schedule-032-rate' validate 32 'Others applicable rate equals zero.' @('frm2200S:txtsched1AppTaxRate{n}') 'Please enter a valid Applicable rate in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7214-L7219')
Rule '2200s-schedule-033-volume' validate 33 'Others volume removals equals zero.' @('frm2200S:txtsched1VolumeRemovals{n}') 'Please enter a value on Volume Removals column in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7220-L7225')
Rule '2200s-schedule-034-rate-unique' validate 34 'ATC/rate combination duplicates another row under checkTaxRate.' @('frm2200S:txtsched1Atc{n}','frm2200S:txtsched1AppTaxRate{n}') 'Please enter a unique Applicable rate in "Others" at Row {row}.' @('official-hta-runtime#isValidDataOnSched1:L7226-L7232')
Rule '2200s-input-035-email' 'blur/change' 1 'Email fails source regex.' @('txtEmail') 'Please enter valid email address.' @('official-hta-runtime#validateEmail:L9650-L9667')
Rule '2200s-input-036-atc' 'blur/change' 2 'Others ATC syntax is invalid.' @('frm2200S:txtsched1Atc{n}') 'Invalid ATC.' @('official-hta-runtime#checkATCValue:L10535-L10551')
Rule '2200s-save-037-january-leap' save 1 'January selectedIndex is 1 and day exceeds 28 in a non-leap year.' @('Return-period-fields') 'Filing year is not a leap year.' @('official-hta-runtime#initialValidateBeforeSave:L8022-L8030') 'incorrect-official-behavior' 'The code treats selectedIndex 1 as February, but index 1 is January because index 0 is the placeholder.' 'Validate the selected month value, not its presentation index.'
Rule '2200s-save-038-january-day29' save 2 'January selectedIndex is 1 and day exceeds 29 in a leap year.' @('Return-period-fields') 'Invalid date entry.' @('official-hta-runtime#initialValidateBeforeSave:L8031-L8035') 'incorrect-official-behavior' 'The same month-index error rejects valid January 30/31 and does not apply the intended branch to February.' 'Validate an actual calendar date.'
Rule '2200s-save-039-date-required' save 3 'Day/year is blank or day is zero.' @('Return-period-fields') 'Please enter valid day on item 1.' @('official-hta-runtime#initialValidateBeforeSave:L8037-L8047')
Rule '2200s-save-040-year-floor' save 4 'Year is below 1900.' @('frm2200S:txtForYr') 'Invalid date entry on Item no.1. Entry should not be lower than 1900.' @('official-hta-runtime#initialValidateBeforeSave:L8048-L8052')
Rule '2200s-save-041-day-range' save 5 'Day exceeds 31 or is blank.' @('frm2200S:txtDate') 'Please indicate a valid Day.' @('official-hta-runtime#initialValidateBeforeSave:L8053-L8057')
Rule '2200s-save-042-tin' save 6 'TIN/branch segment is blank.' @('TIN-fields') 'Please enter a valid TIN number on Item 4.' @('official-hta-runtime#initialValidateBeforeSave:L8059-L8064')
Rule '2200s-save-043-rdo' save 7 'RDO value compares equal to zero.' @($runtimeRdo) 'Please enter a valid RDO Code on Item 5.' @('official-hta-runtime#initialValidateBeforeSave:L8066-L8071')
Rule '2200s-save-044-name' save 8 'Taxpayer name is blank.' @('frm2200S:taxpayerName') 'Please enter a valid Taxpayer Name on Item 6.' @('official-hta-runtime#initialValidateBeforeSave:L8073-L8077')
Rule '2200s-save-045-address' save 9 'Address is blank.' @('frm2200S:txtAddress') 'Please enter a valid Registered Address on Item 7.' @('official-hta-runtime#initialValidateBeforeSave:L8079-L8084')
Rule '2200s-save-046-zip' save 10 'ZIP is blank or shorter than four characters.' @('frm2200S:txtZipCode') "Please enter Taxpayer's Zip Code on Item 7A." @('official-hta-runtime#initialValidateBeforeSave:L8086-L8090')
Rule '2200s-save-047-contact' save 11 'Contact is blank.' @('frm2200S:txtTelNum') 'Please enter a valid Contact Number on Item 8.' @('official-hta-runtime#initialValidateBeforeSave:L8092-L8097')
Rule '2200s-save-048-business' save 12 'Main line of business is blank.' @('frm2200S:txtLineBus') 'Please enter a valid Main Line of Business on Item 9.' @('official-hta-runtime#initialValidateBeforeSave:L8099-L8103')
Rule '2200s-defect-049-fixed-row9-total' 'blur/change' 3 'Fixed Schedule 1 row 9 has nonzero Basic Tax Due.' @('frm2200S:txtBasicTaxDue9','frm2200S:totalTaxDue') $null @('official-hta-runtime#totalTaxDue:L7459-L7470') 'incorrect-official-behavior' 'The fixed-row loop stops at x <= 8 although concrete rows run 0 through 9, omitting row 9 from Item 16.' 'Sum all ten fixed rows plus every Others row.'
Rule '2200s-defect-050-payment-other-choice' validate 35 'Only Other payment manner is selected.' @('frm2200S:chkPymntManner_1','frm2200S:chkPymntManner_2','frm2200S:chkPymntManner_3') 'Please select an option on Part II Manner of Payment' @('official-hta-runtime#validateForm:L7814-L7823') 'incorrect-official-behavior' 'The required-choice branch checks only Actual Removal and Prepayment, so Other alone is rejected even though a separate Other-description rule exists.' 'Include all printed payment choices in the choice group.'
Rule '2200s-defect-051-save-sparse' save 13 'Any Validate-only PSIC, email, location, treaty, payment, deposit, balance, or Schedule rule fails.' @('Validate-only-fields') $null @('official-hta-runtime#initialValidateBeforeSave:L8022-L8106','official-hta-runtime#validateForm:L7673-L7855') 'incorrect-official-behavior' 'Save ends after main line of business and omits the remainder of the Validate graph.' 'Use a shared phase-aware validation graph.'
Rule '2200s-defect-052-overflow-focus' 'blur/change' 4 'Dynamic basic excise tax exceeds the maximum.' @('frm2200S:txtsched1BasicTaxDue{n}') 'Exceeded maximum amount of 999,999,999,999.99 on Basic Excise Tax Due.' @('official-hta-runtime#computeSched1BasicTaxDue:L7407-L7438') 'official-bug-compatible' 'After clearing the row, source focuses nonexistent txtsched1Taxable{n}; the actual input is txtsched1VolumeRemovals{n}.' 'Focus the actual volume field.'
WJ (Join-Path $outDir 'validations.json') ([ordered]@{'$schema'='../../schema/validations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;first_error_behavior='Validate and Save return after the first source-ordered alert; schedule validation stops at the first invalid Others row.';rules=$rules})
$calcs=[Collections.Generic.List[object]]::new();function Calc($id,[string[]]$out,[string[]]$in,$formula,$trigger,[string[]]$deps,[string[]]$refs,$assessment='verified-correct'){$calcs.Add([pscustomobject][ordered]@{calculation_id=$id;outputs=$out;inputs=$in;condition=$null;official_formula=$formula;rounding='roundDownComputation to two displayed decimal places.';trigger=$trigger;depends_on=$deps;source_refs=$refs;assessment=$assessment;recommended_app_behavior='Use typed decimals and preserve source dependency order except where the source is defective.';confidence='high'})}
Calc '2200s-fixed-basic-tax' @('frm2200S:txtBasicTaxDue{0..9}') @('frm2200S:hideProAppRate{0..9}','frm2200S:txtVolumeRemovals{0..9}') 'Basic tax due[row] = hidden applicable rate x volume removals.' computeBasicTaxDue @() @('official-hta-runtime#computeBasicTaxDue:L7388-L7405')
Calc '2200s-dynamic-basic-tax' @('frm2200S:txtsched1BasicTaxDue{n}') @('frm2200S:txtsched1AppTaxRate{n}','frm2200S:txtsched1VolumeRemovals{n}') 'Others basic tax due = applicable rate x volume removals.' computeSched1BasicTaxDue @() @('official-hta-runtime#computeSched1BasicTaxDue:L7407-L7438')
Calc '2200s-schedule-total' @('frm2200S:totalTaxDue') @('frm2200S:txtBasicTaxDue{0..8}','frm2200S:txtsched1BasicTaxDue{0..n}') 'Sum fixed rows 0..8 (row 9 omitted) plus all Others rows.' totalTaxDue @('2200s-fixed-basic-tax','2200s-dynamic-basic-tax') @('official-hta-runtime#totalTaxDue:L7459-L7528') 'incorrect-official-behavior'
Calc '2200s-item16' @('frm2200S:txtTax16') @('frm2200S:totalTaxDue') 'On Schedule OK, Item 16 copies totalTaxDue.' sched1OK @('2200s-schedule-total') @('official-hta-runtime#sched1OK:L7530-L7533')
Calc '2200s-item17c' @('frm2200S:txtTax17C') @('frm2200S:txtTax17A','frm2200S:txtTax17B') '17C = 17A + 17B.' compute17C @() @('official-hta-runtime#compute17C:L7535-L7544')
Calc '2200s-item18' @('frm2200S:txtTax18') @('frm2200S:txtTax16','frm2200S:txtTax17C') '18 = 16 - 17C.' compute18 @('2200s-item16','2200s-item17c') @('official-hta-runtime#compute18:L7546-L7555')
Calc '2200s-item20' @('frm2200S:txtTax20') @('frm2200S:txtTax18','frm2200S:txtTax19') '20 = 18 - 19.' compute20 @('2200s-item18') @('official-hta-runtime#compute20:L7557-L7581')
Calc '2200s-item21d' @('frm2200S:txtTax21D') @('frm2200S:txtTax21A','frm2200S:txtTax21B','frm2200S:txtTax21C') '21D = 21A + 21B + 21C.' compute21D @() @('official-hta-runtime#compute21D:L7583-L7604')
Calc '2200s-item22' @('frm2200S:txtTax22') @('frm2200S:txtTax20','frm2200S:txtTax21D') '22 = 20 + 21D.' compute22 @('2200s-item20','2200s-item21d') @('official-hta-runtime#compute22:L7613-L7635')
Calc '2200s-item23b' @('frm2200S:txtTax23B') @('frm2200S:txtTax21D','frm2200S:PayPenalties') '23B copies 21D when Pay Penalties is checked, else 0.00.' payPenalties @('2200s-item21d') @('official-hta-runtime#payPenalties:L7605-L7611')
Calc '2200s-item23c' @('frm2200S:txtTax23C') @('frm2200S:txtTax23A','frm2200S:txtTax23B') '23C = 23A + 23B.' compute23C @('2200s-item23b') @('official-hta-runtime#compute23C:L7637-L7646')
Calc '2200s-item24' @('frm2200S:txtTax24') @('frm2200S:txtTax22','frm2200S:txtTax23C') '24 = 22 - 23C.' compute24 @('2200s-item22','2200s-item23c') @('official-hta-runtime#compute24:L7648-L7671')
WJ (Join-Path $outDir 'calculations.json') ([ordered]@{'$schema'='../../schema/calculations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;evaluation_order=@($calcs.calculation_id);calculations=$calcs})
$cases=@();$n=0;foreach($r in @($rules|Where-Object{$_.exact_message})){$n++;$cases+=[pscustomobject][ordered]@{case_id=('case-{0:d2}-{1}'-f$n,$r.rule_id);phase=$r.phase;mutations=@{synthetic_condition=$r.condition};expected_message=$r.exact_message;expected_behavior=$r.official_behavior;rule_id=$r.rule_id}};WJ (Join-Path $fixtureDir 'negative-cases.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;synthetic_only=$true;cases=$cases});WJ (Join-Path $fixtureDir 'calculation-boundaries.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;cases=@(@{case_id='fixed-tax';calculation_id='2200s-fixed-basic-tax';rate=35;volume=10;official_output=350},@{case_id='row9-omitted';calculation_id='2200s-schedule-total';rows0to8=900;row9=100;others=50;official_output=950;complete_output=1050},@{case_id='item24';calculation_id='2200s-item24';item22=1200;item23c=1100;official_output=100})})
$resources=@();foreach($src in @([regex]::Matches($hta,'(?i)<script[^>]+src\s*=\s*(["''])(?<v>.*?)\1')|ForEach-Object{$_.Groups['v'].Value}|Sort-Object -Unique)){$full=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $htaPath) $src));if(Test-Path -LiteralPath $full){$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$true;size=(Get-Item -LiteralPath $full).Length;sha256=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()}}else{$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$false;size=$null;sha256=$null}}};WJ (Join-Path $fixtureDir 'official-resource-hashes-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;resources=$resources})
$deadline='For each place of production, file a separate return and pay before removal of the covered products.'
$workflow=[ordered]@{'$schema'='../../schema/workflow.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;phases=@(@{phase='edit';official_behavior='January 2018 sweetened-beverages excise return with ten fixed product rows and unbounded Others rows.';source_refs=@('official-hta-runtime','official-form-pdf','official-guide-pdf');confidence='high'},@{phase='saved-draft';official_behavior='Save validates date and identity only through main line of business.';source_refs=@('official-hta-runtime#initialValidateBeforeSave:L8022-L8106');confidence='high'},@{phase='validated';official_behavior='Validate runs full identity, location, relief/payment, deposit/balance, and Schedule 1 checks.';source_refs=@('official-hta-runtime#validateForm:L7673-L7855');confidence='high'},@{phase='final-copy';official_behavior='Revision-matched encrypted dummy copy contains exactly 118 concrete keys; values excluded.';source_refs=@('encrypted-field-audit-v796');confidence='high'},@{phase='submitted';official_behavior='Online transport was not exercised.';source_refs=@('official-hta-runtime#sendEmail');confidence='medium'});transitions=@(@{from='edit';action='Save';to='saved-draft';guard='Sparse Save checks pass.';side_effects=@('Writes flat pseudo-XML.');source_refs=@('official-hta-runtime#saveXML')},@{from='edit';action='Validate';to='validated';guard='Full Validate graph passes.';side_effects=@('Disables controls.','Enables Final Copy.');source_refs=@('official-hta-runtime#validateForm')},@{from='validated';action='Edit';to='edit';guard=$null;side_effects=@('Re-enables controls.');source_refs=@('official-hta-runtime#editForm')},@{from='validated';action='Final Copy';to='final-copy';guard='Finalization succeeds.';side_effects=@('Encrypts/compresses copy.');source_refs=@('official-hta-runtime#saveEncryptedProfile')},@{from='final-copy';action='Transport';to='submitted';guard='Connectivity and acceptance succeed.';side_effects=@('Untested online attempt.');source_refs=@('official-hta-runtime#sendEmail')});prerequisites=@('Return date','TIN/RDO and identity','PSIC/email','Production/removal locations','Treaty choice','Payment manner and deposit','Schedule 1');required_attachments=@();filing_deadlines=@(@{quarter='Q1';due_date_rule=$deadline;source_refs=@('revision-help');confidence='medium'},@{quarter='Q2';due_date_rule=$deadline;source_refs=@('revision-help');confidence='medium'},@{quarter='Q3';due_date_rule=$deadline;source_refs=@('revision-help');confidence='medium'},@{quarter='Q4';due_date_rule=$deadline;source_refs=@('revision-help');confidence='medium'})};WJ (Join-Path $outDir 'workflow.json') $workflow
$bugs=@($rules|Where-Object{$_.assessment-in@('official-bug-compatible','incorrect-official-behavior','obsolete')}).Count
$actual=[ordered]@{live_controls=$controls.Count;static_serialized=$serial.Count;sample_keys=$keys.Count;sample_static_matches=$keys.Count-$missing.Count;runtime_rdo_matches=$runtimeRdoMatches.Count;runtime_fixed_schedule_matches=$runtimeFixedMatches.Count;unexpected_missing=$unexpectedMissing.Count;sample_extra_static=$sampleExtra.Count;families=$familyNames.Count;typed_fields=$fields.Count;validations=$rules.Count;calculations=$calcs.Count;negative_fixtures=$cases.Count;confirmed_official_bugs=$bugs}
$expectedCounts=[ordered]@{live_controls=116;static_serialized=87;sample_keys=118;sample_static_matches=87;runtime_rdo_matches=1;runtime_fixed_schedule_matches=30;unexpected_missing=0;sample_extra_static=0;families=8;typed_fields=126;validations=52;calculations=12;negative_fixtures=50;confirmed_official_bugs=7}
foreach($name in $expectedCounts.Keys){if($actual[$name]-ne$expectedCounts[$name]){throw "2200S fail-closed count changed: $name expected $($expectedCounts[$name]), found $($actual[$name])."}}
$assets=@(Asset 'package-7.9.6' 'official-package-executable' $packagePath 'Installed Offline eBIRForms package 7.9.6.0.';Asset 'official-hta-runtime' 'runtime-extracted-hta' $htaPath 'January 2018 runtime.';Asset 'revision-help' 'official-runtime-help' $helpPath 'Packaged 2200S instructions.';Asset 'official-guide-pdf' 'official-guidelines-pdf' $guidePath 'January 2018 revised guide.';Asset 'official-form-pdf' 'official-form-pdf' $pdfPath 'January 2018 rev2 form.';Asset 'xml-encrypted-v1' 'dummy-profile-encrypted-final-copy' $sample[0].FullName 'Revision-matched 118-key dummy final copy; values excluded.' $redacted)
$manifest=[ordered]@{'$schema'='../../schema/form-manifest.schema.json';schema_version='1.0.0';form_id=$formId;form_code='2200S';revision=$revision;package_version=$packageVersion;status='complete';official_assets=$assets;counts=[ordered]@{concrete_fields=118;runtime_field_families=$familyNames.Count;fields_total=$fields.Count;typed_fields=$fields.Count;validation_rules=$rules.Count;confirmed_official_bugs=$bugs;calculations=$calcs.Count;negative_fixtures=$cases.Count;unverified_gaps=1};artifacts=[ordered]@{fields='fields.json';validations='validations.json';calculations='calculations.json';workflow='workflow.json';evidence='evidence.md';audit='audit.md';gaps='gaps.md';encrypted_field_audit='fixtures/encrypted-field-audit-v796.json';runtime_controls='fixtures/runtime-control-inventory-v796.json';validation_functions='fixtures/validation-function-inventory-v796.json';calculation_functions='fixtures/calculation-function-inventory-v796.json';resources='fixtures/official-resource-hashes-v796.json';negative_fixtures='fixtures/negative-cases.json';calculation_fixtures='fixtures/calculation-boundaries.json'};scope_notes=@('Research only; no renderer/release metadata changed.','No decrypted values or email-bearing filenames emitted.','118 revision-matched concrete keys plus eight unbounded Others families are preserved.')}
WJ (Join-Path $outDir 'manifest.json') $manifest;WT (Join-Path $outDir 'README.md') "# BIR Form 2200S - January 2018`n`nRevision-specific Offline eBIRForms rules with 118 concrete keys and eight unbounded Schedule 1 Others families.`n";WT (Join-Path $outDir 'evidence.md') "# Evidence`n`n- January 2018 runtime: $($expected.hta); help: $($expected.help).`n- Guide: $($expected.guide); form PDF: $($expected.pdf).`n- Sample: ciphertext $($expected.cipher), decrypted $($expected.plain), 118 unique keys, inventory $($expected.inventory); values never emitted.`n- Sample/current binding: $($keys.Count-$missing.Count) static matches, $($runtimeRdoMatches.Count) runtime RDO match, $($runtimeFixedMatches.Count) script-generated fixed Schedule 1 matches, $($unexpectedMissing.Count) unexplained missing keys.`n- Eight unbounded Others families begin after concrete row zero.`n`nAll email-bearing filenames use `#email-redacted#`.`n";WT (Join-Path $outDir 'gaps.md') "# Gaps`n`n1. Online submission was not exercised.`n";WT (Join-Path $outDir 'audit.md') "# Audit`n`n- January 2018 binding: pass.`n- Revision-matched encrypted sample: 118 unique keys; values excluded.`n- Typed inventory: 118 concrete + $($familyNames.Count) families.`n- Validations $($rules.Count); calculations $($calcs.Count); negatives $($cases.Count); defects $bugs.`n- Full structural/schema audit must run.`n- No renderer/release/capability/commit/push changes.`n"
$ip=Join-Path $RepoRoot 'rules\index.json';$index=Get-Content -Raw -LiteralPath $ip|ConvertFrom-Json;$e=$index.forms|Where-Object{$_.form_id-eq$formId};if($e){$e.form_code='2200S';$e.revision=$revision;$e.package_version=$packageVersion;$e.priority=36;$e.status='complete';$e.path='forms/2200s-v2018/manifest.json'}else{$index.forms+=[pscustomobject][ordered]@{form_id=$formId;form_code='2200S';revision=$revision;package_version=$packageVersion;priority=36;status='complete';path='forms/2200s-v2018/manifest.json'}};$index.forms=@($index.forms|Sort-Object priority);$index.updated='2026-07-23';WJ $ip $index
[pscustomobject]@{form_id=$formId;live_controls=$controls.Count;static_serialized=$serial.Count;sample_static_matches=$keys.Count-$missing.Count;runtime_rdo_matches=$runtimeRdoMatches.Count;runtime_fixed_schedule_matches=$runtimeFixedMatches.Count;unexpected_missing=$unexpectedMissing.Count;sample_extra_static=$sampleExtra.Count;concrete_fields=118;families=$familyNames.Count;typed_fields=$fields.Count;validations=$rules.Count;calculations=$calcs.Count;negative_fixtures=$cases.Count;confirmed_official_bugs=$bugs;next_form='2200T'}|ConvertTo-Json
