param(
    [string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),
    [string]$ExtractedRoot='C:\Users\uriah\AppData\Local\Temp\{68379049-6E6C-4478-A2C5-EF7B77ED7E38}',
    [string]$OfficialDir='C:\Mac\Home\Downloads\forms\2200ANv2018',
    [string]$SampleDir='C:\Mac\Home\Downloads\forms\2200AN'
)
$ErrorActionPreference='Stop'
$formId='2200an-v2018';$revision='2018-01-01';$packageVersion='7.9.6.0'
$htaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2200ANv2018.hta';$legacyPath=Join-Path $ExtractedRoot 'forms\BIR-Form2200AN.hta'
$helpPath=Join-Path $ExtractedRoot 'helpfile\Help2200AN.hta';$guidePath=Join-Path $OfficialDir '2200-AN Jan 2018 ENCS guidelines final.pdf';$annexPath=Join-Path $OfficialDir '2200-AN Jan 2018 ENCS Annex A.pdf'
$packagePath='C:\eBIRForms\BIRForms.exe';$outDir=Join-Path $RepoRoot 'rules\forms\2200an-v2018';$fixtureDir=Join-Path $outDir 'fixtures'
$expected=@{
 hta='23b5502509383379d993fe724e28fdf2d13010b75cd2694c394bc8c72af34f29';legacy='e3f84d83c3455424c66c9223d124b65f30027d3c57ff4af793b6b5b54feeecb4';help='72c3e8fca3d9ba6eab423081db51f9444afb83b44b801a222bddabdde70da7af';guide='d3b5599f459eeb354a05bd70dd9b9ea526a7660f8337c37dbc4ca48c643d6c25';annex='da64d008464d213c7c3ceb60f4fc752a4cae2d271abd2414bbd4f85a305915a2';package='de8ef0815509d65189e6794e1f8135a5ecf5f2800005d1fc5c87043efd96dbca';cipher='9e217dae0c2fe171104510f4ce3bca20ce1c3decb872f70c730ab8306f503670';plain='f51d0ba8311d2af7a06e44b1d6b5432ce9ad92bb79124f405dbf8738d3444b97';inventory='3b4f71dfca06e7f8b2692eb124450f65d0e0ba9431a94ac86ccfb53742ec36f2'
}
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 60)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function Write-Utf8([string]$Path,[string]$Value){[IO.File]::WriteAllText($Path,$Value,[Text.UTF8Encoding]::new($false))}
function Hash-Lines([string[]]$Lines){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes(($Lines-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Attr([string]$Tag,[string]$Name){$m=[regex]::Match($Tag,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($Name)));if($m.Success){$m.Groups[2].Value}else{$null}}
function Asset([string]$Id,[string]$Kind,[string]$Path,[string]$Binding,[string]$Display=''){$i=Get-Item -LiteralPath $Path;[pscustomobject][ordered]@{asset_id=$Id;kind=$Kind;path=if($Display){$Display}else{$Path};sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant();size=$i.Length;revision_binding=$Binding}}
foreach($pair in @(@($htaPath,'hta'),@($legacyPath,'legacy'),@($helpPath,'help'),@($guidePath,'guide'),@($annexPath,'annex'),@($packagePath,'package'))){if(-not(Test-Path -LiteralPath $pair[0] -PathType Leaf)){throw"Missing $($pair[0])"};if((Get-FileHash -LiteralPath $pair[0] -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected[$pair[1]]){throw"Hash changed: $($pair[0])"}}
$sample=@(Get-ChildItem -LiteralPath $SampleDir -File -Filter '*.xml');if($sample.Count-ne1){throw"Expected one sample; found $($sample.Count)."};if((Get-FileHash -LiteralPath $sample[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected.cipher){throw'Sample hash changed.'}
foreach($pdf in @($guidePath,$annexPath)){$b=[IO.File]::ReadAllBytes($pdf);if([Text.Encoding]::ASCII.GetString($b[0..4])-ne'%PDF-'){throw"PDF magic mismatch: $pdf"}}
$hta=[IO.File]::ReadAllText($htaPath);$legacy=[IO.File]::ReadAllText($legacyPath);$help=[IO.File]::ReadAllText($helpPath)
if($hta-notmatch'(?i)January\s+2018\s+\(ENCS\)'-or$hta-notmatch'(?i)APPLICATIONNAME\s*=\s*["'']2200ANv2018["'']'){throw'January 2018 binding changed.'}
if($help-notmatch'(?i)before removal of the above mentioned products'-or$help-notmatch'(?i)For each place of production'){throw'Packaged help binding changed.'}
New-Item -ItemType Directory -Force -Path $fixtureDir|Out-Null
$keyTool=Join-Path $RepoRoot 'rules\tools\extract-encrypted-field-keys.ps1';$redactedSample=Join-Path $SampleDir '2200AN-final-copy-#email-redacted#.xml'
$keyJson=&$keyTool -SourcePath $sample[0].FullName -RedactedSourcePath $redactedSample -FormId '2200an-legacy-excluded' -ExpectedCiphertextSha256 $expected.cipher -ExpectedDecryptedSha256 $expected.plain -ExpectedFieldCount 209 -ExpectedFieldInventorySha256 $expected.inventory
$ka=$keyJson|ConvertFrom-Json;$legacyKeys=@($ka.keys);Write-Utf8 (Join-Path $fixtureDir 'excluded-legacy-encrypted-field-keys-v796.json') ($keyJson-join[Environment]::NewLine)
$currentIds=@([regex]::Matches($hta,'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique);$legacyIds=@([regex]::Matches($legacy,'(?i)\bid\s*=\s*(["''])(?<id>.*?)\1')|ForEach-Object{$_.Groups['id'].Value}|Where-Object{$_}|Sort-Object -Unique)
$co=@($legacyKeys|Where-Object{$currentIds-contains$_});$lo=@($legacyKeys|Where-Object{$legacyIds-contains$_});$legacyNamespace=@($legacyKeys|Where-Object{$_-like'frm2200AN:*'})
if($co.Count-ne7-or$lo.Count-ne64-or$legacyNamespace.Count-ne196){throw"Sample discrimination changed: current/legacy/static-namespace $($co.Count)/$($lo.Count)/$($legacyNamespace.Count)."}

$fm=[regex]::Match($hta,'(?is)<form\b[^>]*(?:id|name)\s*=\s*["'']frmMain["''][^>]*>(?<body>.*?)</form>');if(-not$fm.Success){throw'frmMain missing.'};$body=$fm.Groups['body'].Value;$offset=$fm.Groups['body'].Index;$excluded=@(@([regex]::Matches($body,'(?is)<script\b.*?</script>'))+@([regex]::Matches($body,'(?is)<!--.*?-->')))
$controls=[Collections.Generic.List[object]]::new();$ordinal=0
foreach($m in [regex]::Matches($body,'(?is)<(input|select|textarea|button)\b[^>]*>')){$skip=$false;foreach($range in $excluded){if($m.Index-ge$range.Index-and$m.Index-lt($range.Index+$range.Length)){$skip=$true;break}};if($skip){continue};$ordinal++;$tag=$m.Value;$el=$m.Groups[1].Value.ToLowerInvariant();$kind=if($el-eq'input'){Attr $tag 'type'}else{$el};if(-not$kind){$kind='text'};$kind=$kind.ToLowerInvariant();$default=Attr $tag 'value';if($kind-in@('radio','checkbox')){$default=if($tag-match'(?i)\bchecked(?:\s*=|\s|>)'){'true'}else{'false'}};$controls.Add([pscustomobject][ordered]@{ordinal=$ordinal;id=Attr $tag 'id';name=Attr $tag 'name';element=$el;control_kind=$kind;source_line=1+[regex]::Matches($hta.Substring(0,$offset+$m.Index),"`n").Count;default_value=$default;maxlength=Attr $tag 'maxlength';disabled=$tag-match'(?i)\bdisabled(?:\s*=|\s|>)';readonly=$tag-match'(?i)\breadonly(?:\s*=|\s|>)'})}
$serial=@($controls|Where-Object{$_.control_kind-in@('text','select','select-one','textarea','radio','checkbox')-and$_.id});$staticIds=@($serial.id|Sort-Object -Unique);$runtimeRdo='frm2200ANv2018:txtRDOCode'
if($controls.Count-ne239-or$serial.Count-ne217-or$staticIds.Count-ne217){throw"Control inventory changed: $($controls.Count)/$($serial.Count)/$($staticIds.Count)."};if($staticIds-contains$runtimeRdo-or$hta-notmatch[regex]::Escape("<select class='iceSelOneMnu' id='frm2200ANv2018:txtRDOCode'")){throw'Runtime RDO derivation changed.'}

$required=@('frm2200ANv2018:AmendedRtn1','frm2200ANv2018:AmendedRtn2','frm2200ANv2018:txtTIN1','frm2200ANv2018:txtTIN2','frm2200ANv2018:txtTIN3','frm2200ANv2018:txtBranchCode',$runtimeRdo,'frm2200ANv2018:txtTaxpayerName','frm2200ANv2018:txtTelNum','frm2200ANv2018:txtAddress','frm2200ANv2018:txtZipCode','frm2200ANv2018optRegion','frm2200ANv2018optProvince','frm2200ANv2018optCity','frm2200ANv2018optRegion1','frm2200ANv2018optProvince1','frm2200ANv2018optCity1')
$computed=@('frm2200ANv2018:txt17C','frm2200ANv2018:txt18','frm2200ANv2018:txt20','frm2200ANv2018:txt21D','frm2200ANv2018:txt22','frm2200ANv2018:txt23B','frm2200ANv2018:txt23C','frm2200ANv2018:txt24','frm2200ANv2018:txtBasicExciseTaxDue','frm2200ANv2018:txtBasicExciseTaxDueNonEssentialGoods','frm2200ANv2018:txtSchedule1C','frm2200ANv2018:txt16')
function Item([string]$k){$map=@{'frm2200ANv2018:txtMonth'='1';'frm2200ANv2018:txtDate'='1';'frm2200ANv2018:txtYear'='1';'frm2200ANv2018:AmendedRtn1'='2';'frm2200ANv2018:AmendedRtn2'='2';'frm2200ANv2018:txtSheets'='3';'frm2200ANv2018:txtTIN1'='5';'frm2200ANv2018:txtTIN2'='5';'frm2200ANv2018:txtTIN3'='5';'frm2200ANv2018:txtBranchCode'='5';'frm2200ANv2018:txtRDOCode'='6';'frm2200ANv2018:txtLineBus'='7';'frm2200ANv2018:txtTaxpayerName'='8';'frm2200ANv2018:txtTelNum'='9';'frm2200ANv2018:txtAddress'='10';'frm2200ANv2018:txtZipCode'='11';'frm2200ANv2018:OptSpecialTax1'='12';'frm2200ANv2018:OptSpecialTax2'='12';'frm2200ANv2018:lstSpecialTax'='12A';'frm2200ANv2018:MannerOfPayment1'='13';'frm2200ANv2018:MannerOfPayment2'='14';'frm2200ANv2018:MannerOfPayment3'='15';'frm2200ANv2018:MannerOfPaymentOthers'='15';'frm2200ANv2018:txt16'='16';'frm2200ANv2018:txt17A'='17A';'frm2200ANv2018:txt17B'='17B';'frm2200ANv2018:txt17C'='17C';'frm2200ANv2018:txt18'='18';'frm2200ANv2018:txt19'='19';'frm2200ANv2018:txt20'='20';'frm2200ANv2018:txt21A'='21A';'frm2200ANv2018:txt21B'='21B';'frm2200ANv2018:txt21C'='21C';'frm2200ANv2018:txt21D'='21D';'frm2200ANv2018:txt22'='22';'frm2200ANv2018:txt23A'='23A';'frm2200ANv2018:txt23B'='23B';'frm2200ANv2018:txt23C'='23C';'frm2200ANv2018:txt24'='24'};if($map.ContainsKey($k)){$map[$k]}elseif($k-match'(?i)(?:XG|Sched)'){'Schedule'}else{$null}}
function Field($c,[string]$k){$logical='string';$norm=[string[]]@();$enum=[object[]]@();if(($c-and$c.control_kind-in@('radio','checkbox'))-or$k-match'(?i)(?:Rtn[12]|OptSpecialTax|MannerOfPayment)'){$logical='boolean';$enum=[object[]]@('true','false')}elseif($k-match'(?i)(?:TIN|Branch|RDO|ATC|IPA|Treaty|Zip|Month|Year)'){$logical='code'}elseif($k-match'(?i)(?:Amount|Taxable|Exempt|TaxDue|TaxRate|Interest|txt1[6-9]|txt2[0-4]|Total|Balance|Surcharge|Compromise)'){$logical='decimal-amount';$norm=[string[]]@('NumWithComma','formatCurrency','round(2)')};$isComp=$computed-contains$k;$status=if($isComp){'computed'}elseif($required-contains$k){'required'}else{'optional'};$req=$null;if($k-eq'frm2200ANv2018:lstSpecialTax'){$status='conditional';$req='Item 12 Yes is selected.'}elseif($k-eq'frm2200ANv2018:MannerOfPaymentOthers'){$status='conditional';$req='Item 15 is selected.'};$cons=[ordered]@{};if($c-and$c.maxlength-match'^\d+$'){$cons.max_length=[int]$c.maxlength};if($logical-eq'decimal-amount'){$cons.precision=2;$cons.sign='source-dependent'};[pscustomobject][ordered]@{field_key=$k;serialized_key=$k;serialized_occurrence=1;label=$k;page=if($k-match'(?i)(?:XG|Sched)'){2}elseif($k-like'frm2200ANv2018:*'){1}else{$null};item_number=Item $k;control_kind=if($c){$c.control_kind}else{'runtime-generated-select'};storage_type='string';logical_type=$logical;required=$status;required_when=$req;enabled_when=if($k-eq'frm2200ANv2018:txt19'){'Amended Return Yes is selected.'}else{$null};visible_when=$null;default_value=if($c){$c.default_value}else{'000'};empty_representation='';constraints=[pscustomobject]$cons;enum_values=$enum;normalization=$norm;computed=$isComp;calculation_id=if($isComp){'See calculations.json'}else{$null};source_refs=@('official-hta-runtime#saveXML',"official-hta-runtime#control:L$(if($c){$c.source_line}else{9774})");confidence='high';notes=[string[]]@('Source-derived from the hash-pinned January 2018 runtime; no revision-matched final copy is available.')}}
$fields=[Collections.Generic.List[object]]::new();foreach($c in $serial){$fields.Add((Field $c $c.id))};$fields.Add((Field ([pscustomobject]@{control_kind='runtime-generated-select';source_line=9774;default_value='000';maxlength=$null}) $runtimeRdo));if($fields.Count-ne218){throw"Expected 218 fields; found $($fields.Count)."}
Write-Json (Join-Path $outDir 'fields.json') ([ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;field_count=$fields.Count;runtime_serializable_element_count=218;inventory_sha256=Hash-Lines @($fields.field_key|Sort-Object);fields=$fields})
Write-Json (Join-Path $fixtureDir 'runtime-control-inventory-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;official_hta_sha256=$expected.hta;live_control_count=$controls.Count;static_serialized_id_count=$staticIds.Count;runtime_generated_scalar_count=1;runtime_generated_scalars=@($runtimeRdo);runtime_family_count=0;revision_matched_final_copy_key_count=0;excluded_legacy_sample_key_count=$legacyKeys.Count;excluded_legacy_namespace_key_count=$legacyNamespace.Count;excluded_legacy_sample_overlap_with_legacy_static_ids=$lo.Count;excluded_legacy_sample_overlap_with_current_ids=$co.Count;controls=$controls})
$fn=Join-Path $RepoRoot 'rules\tools\extract-hta-function-inventory.ps1';Write-Utf8 (Join-Path $fixtureDir 'validation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200ANv2018:' -NamePattern '(?i)valid|check|save|date|submit|final|process')-join[Environment]::NewLine);Write-Utf8 (Join-Path $fixtureDir 'calculation-function-inventory-v796.json') ((&$fn -HtaPath $htaPath -ControlPrefix 'frm2200ANv2018:' -NamePattern '(?i)compute|amount|tax|penalt|balance|format')-join[Environment]::NewLine)

$rules=[Collections.Generic.List[object]]::new()
function Rule([string]$Id,[string]$Phase,$Order,[string]$Condition,[string[]]$Keys,$Message,[string[]]$Refs,[string]$Assessment='verified-correct',[string]$Official='The branch alerts and stops the active operation.',[string]$Recommended='Retain as a structured revision-aware error.'){$rules.Add([pscustomobject][ordered]@{rule_id=$Id;form_id=$formId;revision=$revision;phase=$Phase;order=$Order;condition=$Condition;fields=$Keys;accepted_behavior='Condition is false; processing continues.';rejected_behavior='The active operation stops unless official_behavior states otherwise.';exact_message=$Message;source_refs=$Refs;evidence_type=@('source');assessment=$Assessment;official_behavior=$Official;recommended_app_behavior=$Recommended;confidence='high';unresolved_questions=@()})}
Rule '2200an-validate-001-future-month' validate 1 'Month is after current month and year is current or later.' @('frm2200ANv2018:txtMonth','frm2200ANv2018:txtYear') 'Date should not be later than the current date.' @('official-hta-runtime#validate:L8948-L8952')
Rule '2200an-validate-002-future-day' validate 2 'Day is after today within current month/year.' @('frm2200ANv2018:txtMonth','frm2200ANv2018:txtDate','frm2200ANv2018:txtYear') 'Date should not be later than the current date.' @('official-hta-runtime#validate:L8953-L8955')
Rule '2200an-validate-003-future-year' validate 3 'Year is after current year.' @('frm2200ANv2018:txtYear') 'Date should not be later than the current date.' @('official-hta-runtime#validate:L8956-L8958')
$prod=@('frm2200ANv2018optRegion','frm2200ANv2018optProvince','frm2200ANv2018optCity');for($i=0;$i-lt3;$i++){Rule ("2200an-validate-00{0}-production"-f($i+4)) validate ($i+4) 'The corresponding production location selector has selectedIndex 0.' @($prod[$i]) 'Please select the place of production in item 10.' @("official-hta-runtime#validate:L$((8963+6*$i))-L$((8968+6*$i))")}
$rem=@('frm2200ANv2018optRegion1','frm2200ANv2018optProvince1','frm2200ANv2018optCity1');for($i=0;$i-lt3;$i++){Rule ("2200an-validate-00{0}-removal"-f($i+7)) validate ($i+7) 'The corresponding removal location selector has selectedIndex 0.' @($rem[$i]) 'Please select the place of removal in item 11.' @("official-hta-runtime#validate:L$((8982+6*$i))-L$((8987+6*$i))")}
Rule '2200an-validate-010-amended' validate 10 'Neither amended-return radio is selected.' @('frm2200ANv2018:AmendedRtn1','frm2200ANv2018:AmendedRtn2') 'Please select an option in item number 2.' @('official-hta-runtime#validate:L9023-L9027')
Rule '2200an-validate-011-special-tax' validate 11 'Neither special-tax/tax-relief radio is selected.' @('frm2200ANv2018:OptSpecialTax1','frm2200ANv2018:OptSpecialTax2') 'Please select an option in item number 12.' @('official-hta-runtime#validate:L9029-L9034')
Rule '2200an-validate-012-relief-spec' validate 12 'Tax relief Yes is selected and list value is blank.' @('frm2200ANv2018:OptSpecialTax1','frm2200ANv2018:lstSpecialTax') 'Please specify tax relief in item 12A.' @('official-hta-runtime#validate:L9036-L9041')
Rule '2200an-validate-013-payment' validate 13 'No Item 13-15 manner of payment is selected.' @('frm2200ANv2018:MannerOfPayment1','frm2200ANv2018:MannerOfPayment2','frm2200ANv2018:MannerOfPayment3') 'Please select from items 13, 14 and 15 the manner of payment.' @('official-hta-runtime#validate:L9043-L9048')
Rule '2200an-validate-014-other-payment' validate 14 'Other Similar Scheme is selected and specification is blank.' @('frm2200ANv2018:MannerOfPayment3','frm2200ANv2018:MannerOfPaymentOthers') 'Please specify the other similar schemes in item 15.' @('official-hta-runtime#validate:L9050-L9054')
Rule '2200an-validate-015-tin' validate 15 'Any TIN segment or branch code is blank.' @('frm2200ANv2018:txtTIN1','frm2200ANv2018:txtTIN2','frm2200ANv2018:txtTIN3','frm2200ANv2018:txtBranchCode') 'Please enter a valid TIN number on Item 5.' @('official-hta-runtime#validate:L9056-L9059')
Rule '2200an-validate-016-rdo' validate 16 'Runtime RDO selectedIndex is 0.' @($runtimeRdo) 'Please enter a valid RDO Code on Item 6.' @('official-hta-runtime#validate:L9060-L9064')
Rule '2200an-validate-017-name' validate 17 'Taxpayer name is blank.' @('frm2200ANv2018:txtTaxpayerName') 'Please enter a valid Taxpayer Name on Item 8.' @('official-hta-runtime#validate:L9069-L9072')
Rule '2200an-validate-018-phone' validate 18 'Telephone number is blank.' @('frm2200ANv2018:txtTelNum') 'Please enter a valid Telephone Number on Item 9.' @('official-hta-runtime#validate:L9073-L9076')
Rule '2200an-validate-019-address' validate 19 'Registered address is blank.' @('frm2200ANv2018:txtAddress') "Please enter Taxpayer's Registered Address on Item 10." @('official-hta-runtime#validate:L9077-L9080')
Rule '2200an-validate-020-zip' validate 20 'ZIP code is blank.' @('frm2200ANv2018:txtZipCode') "Please enter Taxpayer's Zip Code on Item 11." @('official-hta-runtime#validate:L9081-L9084')
Rule '2200an-defect-021-duplicate-special-tax' validate 21 'Neither special-tax radio is selected, after the identical Item 12 check already passed.' @('frm2200ANv2018:OptSpecialTax1','frm2200ANv2018:OptSpecialTax2') 'Please select an option in item 13.' @('official-hta-runtime#validate:L9094-L9098') 'incorrect-official-behavior' 'This branch is unreachable because rule 011 checks the same condition first and reports Item 12.' 'Keep one check using the printed item number.'
Rule '2200an-validate-022-special-tax-list' validate 22 'Tax relief Yes is selected and list selectedIndex is 0.' @('frm2200ANv2018:OptSpecialTax1','frm2200ANv2018:lstSpecialTax') 'Please select an option in item 13A.' @('official-hta-runtime#validate:L9100-L9107') 'official-bug-compatible' 'The message conflicts with the earlier Item 12A wording.' 'Use the printed item number consistently.'
Rule '2200an-input-023-ipa' 'blur/change' 1 'IPA code is not blank and not one of the 13 hard-coded codes.' @('frm2200ANv2018:txtSched3IPA1','frm2200ANv2018:txtSched3IPA2') 'Invalid IPA Code! Please refer to IPA Codes in Schedule 6.' @('official-hta-runtime#validateIPA:L8756-L8772')
Rule '2200an-input-024-atc' 'blur/change' 2 'ATC code is not blank and not one of the 13 hard-coded codes.' @('Schedule-ATC-fields') 'Invalid ATC Code! Please refer to the ATC Codes in Schedule 1.' @('official-hta-runtime#validateATC:L8818-L8834')
Rule '2200an-input-025-treaty-code' 'blur/change' 3 'Treaty code is not blank and not one of the 40 hard-coded codes.' @('frm2200ANv2018:txtSched2TreatyCode1','frm2200ANv2018:txtSched2TreatyCode2') 'Invalid Treaty Code! Please refer to the treaty code in schedule 5.' @('official-hta-runtime#validateTreatyCode:L8836-L8853')
Rule '2200an-input-026-check-date' 'blur/change' 4 'A return-period component makes the date later than today.' @('frm2200ANv2018:txtMonth','frm2200ANv2018:txtDate','frm2200ANv2018:txtYear') 'Date should not be later than the current date.' @('official-hta-runtime#checkDate:L9169-L9183') 'official-bug-compatible' 'The alert neither clears nor blocks the value; Validate repeats the check.' 'Return a structured invalid result and block progression.'
Rule '2200an-defect-027-date-required' validate 23 'Month, day, or year is blank.' @('frm2200ANv2018:txtMonth','frm2200ANv2018:txtDate','frm2200ANv2018:txtYear') $null @('official-hta-runtime#validate:L8945-L8961','official-hta-runtime#validate:L9000-L9013') 'incorrect-official-behavior' 'The required/year-range block is commented out; blank components can pass comparisons.' 'Require a complete return period.'
Rule '2200an-defect-028-calendar-date' validate 24 'Return period is an impossible calendar date such as February 31.' @('frm2200ANv2018:txtMonth','frm2200ANv2018:txtDate','frm2200ANv2018:txtYear') $null @('official-hta-runtime#validate:L8945-L8961') 'incorrect-official-behavior' 'Only component comparisons against today run; calendar validity is never checked.' 'Validate the composed calendar date.'
Rule '2200an-defect-029-line-business' validate 25 'Line of business is blank.' @('frm2200ANv2018:txtLineBus') 'Please enter a valid Line of Business/Occupation on Item 7.' @('official-hta-runtime#validate:L9065-L9068') 'incorrect-official-behavior' 'The entire required branch is commented out.' 'Enforce when legally required.'
Rule '2200an-defect-030-schedule2' validate 26 'Schedule 2 rows are incomplete.' @('Schedule-2-fields') 'Please fill up Schedule 2 row {row} completely.' @('official-hta-runtime#validateSched2:L8522-L8598','official-hta-runtime#validate:L9128-L9137') 'incorrect-official-behavior' 'Every Schedule 2 check and the call from Validate are commented out.' 'Validate each populated row as a unit.'
Rule '2200an-defect-031-schedule3' validate 27 'Schedule 3 rows are incomplete.' @('Schedule-3-fields') 'Please fill up Schedule 3 row {row} completely.' @('official-hta-runtime#validateSched3:L8600-L8639','official-hta-runtime#validate:L9128-L9137') 'incorrect-official-behavior' 'Every substantive Schedule 3 check and the call from Validate are commented out.' 'Validate each populated row as a unit.'
Rule '2200an-defect-032-overremittance' validate 28 'Item 24 is negative and no over-remittance disposition is selected.' @('frm2200ANv2018:txt24','Over-remittance-fields') 'Please select an option for over-remittance below item 28.' @('official-hta-runtime#validate:L9117-L9127') 'incorrect-official-behavior' 'The entire branch is commented out and its message references stale Item 28.' 'Use the current printed balance item and require disposition when applicable.'
Rule '2200an-defect-033-tax-row-manual' validate 29 'A fixed Schedule 1 Tax Due is inconsistent with its taxable bases/rate.' @('frm2200ANv2018:txtXG021Taxable1','frm2200ANv2018:txtXG021TaxDue','Schedule-1-fields') $null @('official-hta-runtime#control:L1611-L1629','official-hta-runtime#computeBasicExciseAuto:L9263-L9287') 'incorrect-official-behavior' 'Tax Due fields are editable; the source sums them but does not derive them from the row bases.' 'Compute each row from the revision-pinned legal rate table.'
Rule '2200an-save-034-tin' save 1 'Any TIN segment or branch code is blank.' @('frm2200ANv2018:txtTIN1','frm2200ANv2018:txtTIN2','frm2200ANv2018:txtTIN3','frm2200ANv2018:txtBranchCode') 'Please enter a valid TIN number on Item 5.' @('official-hta-runtime#initialValidateBeforeSave:L9785-L9789')
Rule '2200an-save-035-rdo' save 2 'RDO value is 000.' @($runtimeRdo) 'Please enter a valid RDO Code on Item 6.' @('official-hta-runtime#initialValidateBeforeSave:L9790-L9793')
Rule '2200an-save-036-name' save 3 'Taxpayer/withholding-agent name is blank.' @('frm2200ANv2018:txtTaxpayerName') "Please enter a valid Withholding Agent's Name on Item 8." @('official-hta-runtime#initialValidateBeforeSave:L9794-L9797')
Rule '2200an-defect-037-save-sparse' save 4 'Any Validate-only required field is missing.' @('frm2200ANv2018:txtAddress','frm2200ANv2018:txtZipCode','frm2200ANv2018:txtTelNum','frm2200ANv2018optCity','frm2200ANv2018optCity1') $null @('official-hta-runtime#initialValidateBeforeSave:L9785-L9799','official-hta-runtime#validate:L8945-L9150') 'incorrect-official-behavior' 'Save checks only TIN, RDO, and name.' 'Use a shared phase-aware validation graph.'
Rule '2200an-defect-038-validate-year' 'blur/change' 5 'validateYear is invoked.' @('frm2200ANv2018:txtYear') 'Invalid year. Year should not be later than the current year.' @('official-hta-runtime#validateYear:L8931-L8942','official-hta-runtime#control:L315-L317') 'obsolete' 'The only call site is in commented markup; it also uses deprecated getYear, yielding years since 1900.' 'Do not invoke; use full-year typed date validation.'
Write-Json (Join-Path $outDir 'validations.json') ([ordered]@{'$schema'='../../schema/validations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;first_error_behavior='Validate stops at the first active source-ordered branch; many schedule and date branches are commented out; Save uses a narrow graph.';rules=$rules})

$calcs=[Collections.Generic.List[object]]::new()
function Calc([string]$Id,[string[]]$Out,[string[]]$In,[string]$Formula,[string]$Trigger,[string[]]$Deps,[string[]]$Refs,[string]$Assessment='verified-correct',[string]$Recommended='Implement with typed decimals and the official two-decimal display order.'){$calcs.Add([pscustomobject][ordered]@{calculation_id=$Id;outputs=$Out;inputs=$In;condition=$null;official_formula=$Formula;rounding='formatCurrency after source arithmetic.';trigger=$Trigger;depends_on=$Deps;source_refs=$Refs;assessment=$Assessment;recommended_app_behavior=$Recommended;confidence='high'})}
Calc '2200an-sched3-row' @('frm2200ANv2018:txtSched3TaxWithheld{1..2}') @('frm2200ANv2018:txtSched3TotInterest{1..2}','frm2200ANv2018:txtSched3TaxRate{1..2}') 'Tax withheld = total interest x rate / 100.' computeSched3 @() @('official-hta-runtime#computeSched3:L8774-L8784')
Calc '2200an-sched2-row' @('frm2200ANv2018:txtSched2TaxesWithheld{1..2}') @('Schedule-2-amounts','frm2200ANv2018:txtSched2TaxRate{1..2}') 'Tax withheld = amount x rate / 100.' computeSched2 @() @('official-hta-runtime#computeSched2:L8796-L8806')
Calc '2200an-basic-auto-total' @('frm2200ANv2018:txtBasicExciseTaxDue') @('22 fixed automatic-products Tax Due fields') 'Sum the 22 enumerated XG Tax Due fields.' computeBasicExciseAuto @() @('official-hta-runtime#computeBasicExciseAuto:L9263-L9287')
Calc '2200an-basic-goods-total' @('frm2200ANv2018:txtBasicExciseTaxDueNonEssentialGoods') @('5 non-essential-goods Tax Due fields') 'Sum XG100, XG110, XG120, and two Others Tax Due fields.' computeBasicExciseGoods @() @('official-hta-runtime#computeBasicExciseGoods:L9289-L9296')
Calc '2200an-item16' @('frm2200ANv2018:txtSchedule1C','frm2200ANv2018:txt16') @('frm2200ANv2018:txtBasicExciseTaxDue','frm2200ANv2018:txtBasicExciseTaxDueNonEssentialGoods') 'Schedule 1C = automatic-products total + non-essential-goods total; copy to Item 16.' computeSchedule1C @('2200an-basic-auto-total','2200an-basic-goods-total') @('official-hta-runtime#computeSchedule1C:L9298-L9303')
Calc '2200an-item17c' @('frm2200ANv2018:txt17C') @('frm2200ANv2018:txt17A','frm2200ANv2018:txt17B') 'Item 17C = Item 17A + Item 17B.' compute17C @() @('official-hta-runtime#compute17C:L9216-L9220')
Calc '2200an-item18' @('frm2200ANv2018:txt18') @('frm2200ANv2018:txt16','frm2200ANv2018:txt17C') 'Item 18 = Item 16 - Item 17C.' compute18 @('2200an-item16','2200an-item17c') @('official-hta-runtime#compute18:L9222-L9226')
Calc '2200an-item20' @('frm2200ANv2018:txt20') @('frm2200ANv2018:txt18','frm2200ANv2018:txt19') 'Item 20 = Item 18 - Item 19.' compute20 @('2200an-item18') @('official-hta-runtime#compute20:L9228-L9232')
Calc '2200an-item21d' @('frm2200ANv2018:txt21D','frm2200ANv2018:txt23B') @('frm2200ANv2018:txt21A','frm2200ANv2018:txt21B','frm2200ANv2018:txt21C') 'Item 21D = 21A + 21B + 21C; copy to Item 23B.' compute21D @() @('official-hta-runtime#compute21D:L9234-L9241')
Calc '2200an-item22-double-penalty' @('frm2200ANv2018:txt22') @('frm2200ANv2018:txt20','frm2200ANv2018:txt21A','frm2200ANv2018:txt21B','frm2200ANv2018:txt21C','frm2200ANv2018:txt21D') 'Item 22 = Item 20 + Items 21A + 21B + 21C + Item 21D, double-counting penalties.' compute22 @('2200an-item20','2200an-item21d') @('official-hta-runtime#compute22:L9243-L9250') 'incorrect-official-behavior' 'Item 22 should add Item 20 and Item 21D once.'
Calc '2200an-item23c' @('frm2200ANv2018:txt23C') @('frm2200ANv2018:txt23A','frm2200ANv2018:txt23B') 'Item 23C = Item 23A + Item 23B.' compute23C @('2200an-item21d') @('official-hta-runtime#compute23C:L9252-L9256')
Calc '2200an-item24' @('frm2200ANv2018:txt24') @('frm2200ANv2018:txt22','frm2200ANv2018:txt23C') 'Item 24 = Item 22 - Item 23C.' compute24 @('2200an-item22-double-penalty','2200an-item23c') @('official-hta-runtime#compute24:L9258-L9261')
Calc '2200an-obsolete-sched1-total' @('frm2200ANv2018:txt16') @('obsolete Schedule 1 Tax fields') 'Due to commented operands, total is initialized through an assignment that formats its own undefined value.' computeSched1Total @() @('official-hta-runtime#computeSched1Total:L8877-L8889') 'obsolete' 'Do not use; the current active total path is computeBasicExciseAuto/Goods -> computeSchedule1C.'
Write-Json (Join-Path $outDir 'calculations.json') ([ordered]@{'$schema'='../../schema/calculations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;evaluation_order=@($calcs.calculation_id);calculations=$calcs})
$cases=@();$n=0;foreach($r in @($rules|Where-Object{$_.exact_message})){$n++;$cases+=[pscustomobject][ordered]@{case_id=('case-{0:d2}-{1}'-f$n,$r.rule_id);phase=$r.phase;mutations=@{synthetic_condition=$r.condition};expected_message=$r.exact_message;expected_behavior=$r.official_behavior;rule_id=$r.rule_id}}
Write-Json (Join-Path $fixtureDir 'negative-cases.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;synthetic_only=$true;cases=$cases})
Write-Json (Join-Path $fixtureDir 'calculation-boundaries.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;cases=@(@{case_id='schedule-row';calculation_id='2200an-sched3-row';amount=100000;rate=15;official_output=15000},@{case_id='double-penalty';calculation_id='2200an-item22-double-penalty';item20=1000;penalty_components_total=100;item21d=100;official_output=1200;recommended_output=1100},@{case_id='item24';calculation_id='2200an-item24';item22=1200;item23c=1100;official_output=100})})
$resources=@();foreach($src in @([regex]::Matches($hta,'(?i)<script[^>]+src\s*=\s*(["''])(?<v>.*?)\1')|ForEach-Object{$_.Groups['v'].Value}|Sort-Object -Unique)){$full=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $htaPath) $src));if(Test-Path -LiteralPath $full){$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$true;size=(Get-Item -LiteralPath $full).Length;sha256=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()}}else{$resources+=[pscustomobject][ordered]@{src=$src;path=$full;present=$false;size=$null;sha256=$null}}};Write-Json (Join-Path $fixtureDir 'official-resource-hashes-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;resources=$resources})

$deadline='For each place of production, file a separate return and pay before removal of the covered products.'
$workflow=[ordered]@{'$schema'='../../schema/workflow.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;phases=@(
 @{phase='edit';official_behavior='January 2018 excise-tax return for automobiles and non-essential goods with fixed schedules.';source_refs=@('official-hta-runtime','official-guide-pdf','official-annex-pdf');confidence='high'},@{phase='saved-draft';official_behavior='Save checks only TIN, RDO, and name before flat serialization.';source_refs=@('official-hta-runtime#initialValidateBeforeSave:L9785-L9799','official-hta-runtime#saveXML');confidence='high'},@{phase='validated';official_behavior='Validate checks identity, location, tax-relief and payment selections, but schedule/date completeness branches are disabled.';source_refs=@('official-hta-runtime#validate:L8945-L9150');confidence='high'},@{phase='final-copy';official_behavior='Encryption exists, but the available 209-key copy uses the legacy frm2200AN namespace and is excluded.';source_refs=@('official-hta-runtime#saveEncryptedProfile','excluded-legacy-encrypted-keys');confidence='medium'},@{phase='submitted';official_behavior='Online transport exists but was not exercised.';source_refs=@('official-hta-runtime#sendEmail');confidence='medium'}
);transitions=@(
 @{from='edit';action='Save';to='saved-draft';guard='Sparse Save checks pass.';side_effects=@('Writes flat pseudo-XML.');source_refs=@('official-hta-runtime#saveXML')},@{from='edit';action='Validate';to='validated';guard='Active Validate checks pass.';side_effects=@('Disables controls.','Enables final copy.');source_refs=@('official-hta-runtime#validate')},@{from='validated';action='Edit';to='edit';guard=$null;side_effects=@('Re-enables controls.');source_refs=@('official-hta-runtime#enableAllControl')},@{from='validated';action='Final Copy';to='final-copy';guard='Finalization succeeds.';side_effects=@('Encrypts/compresses the copy.');source_refs=@('official-hta-runtime#saveEncryptedProfile')},@{from='final-copy';action='Transport';to='submitted';guard='Connectivity and acceptance succeed.';side_effects=@('Untested online attempt.');source_refs=@('official-hta-runtime#sendEmail')}
);prerequisites=@('TIN/RDO and taxpayer identity','Production and removal locations','Tax-relief choice/specification','Manner of payment','Schedules should be complete although active Validate omits them');required_attachments=@();filing_deadlines=@(@{quarter='Q1';due_date_rule=$deadline;source_refs=@('packaged-help#L137-L150');confidence='high'},@{quarter='Q2';due_date_rule=$deadline;source_refs=@('packaged-help#L137-L150');confidence='high'},@{quarter='Q3';due_date_rule=$deadline;source_refs=@('packaged-help#L137-L150');confidence='high'},@{quarter='Q4';due_date_rule=$deadline;source_refs=@('packaged-help#L137-L150');confidence='high'})}
Write-Json (Join-Path $outDir 'workflow.json') $workflow
$bugs=@($rules|Where-Object{$_.assessment-in@('official-bug-compatible','incorrect-official-behavior','obsolete')}).Count
$assets=@(Asset 'package-7.9.6' 'official-package-executable' $packagePath 'Installed package 7.9.6.0.';Asset 'official-hta-runtime' 'runtime-extracted-hta' $htaPath 'January 2018 ENCS runtime.';Asset 'legacy-runtime-excluded' 'runtime-extracted-hta' $legacyPath 'Legacy predecessor, used only for sample exclusion.';Asset 'packaged-help' 'official-runtime-help' $helpPath 'Unversioned packaged instructions; deadline fact only.';Asset 'official-guide-pdf' 'official-guidelines-pdf' $guidePath 'January 2018 ENCS guidelines.';Asset 'official-annex-pdf' 'official-annex-pdf' $annexPath 'January 2018 ENCS Annex A.';Asset 'legacy-encrypted-sample-excluded' 'dummy-profile-encrypted-final-copy' $sample[0].FullName 'Excluded: 196/209 form keys use legacy frm2200AN namespace; only 7 keys overlap current IDs.' $redactedSample)
$manifest=[ordered]@{'$schema'='../../schema/form-manifest.schema.json';schema_version='1.0.0';form_id=$formId;form_code='2200AN';revision=$revision;package_version=$packageVersion;status='complete';official_assets=$assets;counts=[ordered]@{concrete_fields=218;runtime_field_families=0;fields_total=$fields.Count;typed_fields=$fields.Count;validation_rules=$rules.Count;confirmed_official_bugs=$bugs;calculations=$calcs.Count;negative_fixtures=$cases.Count;unverified_gaps=2};artifacts=[ordered]@{fields='fields.json';validations='validations.json';calculations='calculations.json';workflow='workflow.json';evidence='evidence.md';audit='audit.md';gaps='gaps.md';excluded_legacy_encrypted_keys='fixtures/excluded-legacy-encrypted-field-keys-v796.json';runtime_controls='fixtures/runtime-control-inventory-v796.json';validation_functions='fixtures/validation-function-inventory-v796.json';calculation_functions='fixtures/calculation-function-inventory-v796.json';resources='fixtures/official-resource-hashes-v796.json';negative_fixtures='fixtures/negative-cases.json';calculation_fixtures='fixtures/calculation-boundaries.json'};scope_notes=@('Research only; no renderer/release metadata changed.','No decrypted values or email-bearing filenames emitted.','Legacy 209-key sample excluded by namespace.','217 static serialized controls + one runtime RDO selector; no current dynamic field families.')}
Write-Json (Join-Path $outDir 'manifest.json') $manifest;Write-Utf8 (Join-Path $outDir 'README.md') "# BIR Form 2200AN - January 2018`n`nRevision-specific package with 218 concrete serialized fields and no dynamic families.`n"
Write-Utf8 (Join-Path $outDir 'evidence.md') "# Evidence`n`n- January 2018 runtime: $($expected.hta); legacy runtime: $($expected.legacy), excluded.`n- Guide: $($expected.guide); Annex A: $($expected.annex); help: $($expected.help).`n- Sample: ciphertext $($expected.cipher), decrypted $($expected.plain), 209 keys, inventory $($expected.inventory); values never emitted.`n- 196 sample keys use legacy `frm2200AN`; only 7 generic keys overlap current IDs. Sample excluded.`n- Inventory: 217 static serialized controls plus one runtime RDO selector; zero families.`n`nAll email-bearing filenames use `#email-redacted#`.`n"
Write-Utf8 (Join-Path $outDir 'gaps.md') "# Gaps`n`n1. No revision-matched January 2018 encrypted final copy is available; the supplied sample is proven legacy and excluded.`n2. Online submission was not exercised.`n"
Write-Utf8 (Join-Path $outDir 'audit.md') "# Audit`n`n- January 2018 revision separation: pass.`n- Legacy sample excluded by namespace: 196 legacy form keys; 7 current generic overlaps.`n- Typed inventory: 218 concrete, zero families.`n- Validations: $($rules.Count); calculations: $($calcs.Count); negative fixtures: $($cases.Count); official defects: $bugs.`n- Full structural/schema audit must run after generation.`n- No renderer/release/capability/commit/push changes.`n"
$indexPath=Join-Path $RepoRoot 'rules\index.json';$index=Get-Content -Raw -LiteralPath $indexPath|ConvertFrom-Json;$entry=$index.forms|Where-Object{$_.form_id-eq$formId};if($entry){$entry.form_code='2200AN';$entry.revision=$revision;$entry.package_version=$packageVersion;$entry.priority=32;$entry.status='complete';$entry.path='forms/2200an-v2018/manifest.json'}else{$index.forms+=[pscustomobject][ordered]@{form_id=$formId;form_code='2200AN';revision=$revision;package_version=$packageVersion;priority=32;status='complete';path='forms/2200an-v2018/manifest.json'}};$index.forms=@($index.forms|Sort-Object priority);$index.updated='2026-07-23';Write-Json $indexPath $index
[pscustomobject]@{form_id=$formId;concrete_fields=218;families=0;typed_fields=$fields.Count;validations=$rules.Count;calculations=$calcs.Count;negative_fixtures=$cases.Count;confirmed_official_bugs=$bugs;next_form='2200C'}|ConvertTo-Json
