param(
    [string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),
    [string]$ExtractedRoot='C:\Users\uriah\AppData\Local\Temp\{68379049-6E6C-4478-A2C5-EF7B77ED7E38}',
    [string]$PdfDir='C:\Mac\Home\Downloads\forms\2000-DSTv2018',
    [string]$LegacySampleDir='C:\Mac\Home\Downloads\forms\2000'
)
$ErrorActionPreference='Stop'
$formId='2000-v2018';$revision='2018-01-01';$packageVersion='7.9.6.0'
$htaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2000v2018.hta';$legacyHtaPath=Join-Path $ExtractedRoot 'forms\BIR-Form2000.hta'
$helpPath=Join-Path $ExtractedRoot 'helpfile\Help2000v2018.hta';$legacyHelpPath=Join-Path $ExtractedRoot 'helpfile\Help2000.hta'
$pdfPath=Join-Path $PdfDir '2000-DST Jan 2018 final.pdf';$guidePath=Join-Path $PdfDir '2000 Guide Jan 2018.pdf'
$packagePath='C:\eBIRForms\BIRForms.exe';$outDir=Join-Path $RepoRoot 'rules\forms\2000-v2018';$fixtureDir=Join-Path $outDir 'fixtures'
$expected=@{
hta='43aa6fcdba1ffb40bebb3dc1e8509a87b84799b38937bb6bc57273e9021c4a7b';legacy_hta='8b80e909f7f70785dbdf002488b2c14b0a4a2fca7b3c783b68cdd5a59f3ca475'
help='254279e70740ab5b3099b684fbb02a4dc7a42723e813f157baa2022ac2e144f8';legacy_help='36cdb3ff0bfd624b4b5f66f288c29dac512029006697f37d9ba35bd5ce65ef0e'
pdf='b18ce9d2380d216814f4410c2e132eebb02b93754f7ca0167311f368e100e79f';guide='bb653d7157cf3c6a116b5eae5d669fe302e4e08230154dffe3239ea61174a130'
legacy_cipher='f52eff04eb3e2e50c9d6fc626cd5344aa243a4a4ea8fb1ae954093165daefe9c';legacy_plain='d0a34a75488d15941d126e856202fb1f5e0d738165c83a0a3baa62e302636573'
legacy_inventory='da6f3991b7570f3786a40c24ac2d686aa3e79e488a30604285a49ae495048521';package='de8ef0815509d65189e6794e1f8135a5ecf5f2800005d1fc5c87043efd96dbca'
}
function WJ([string]$p,$v){[IO.File]::WriteAllText($p,(($v|ConvertTo-Json -Depth 70)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function WT([string]$p,[string]$v){[IO.File]::WriteAllText($p,$v,[Text.UTF8Encoding]::new($false))}
function HL([string[]]$x){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes(($x-join"`n"))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function A([string]$t,[string]$n){$m=[regex]::Match($t,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($n)));if($m.Success){$m.Groups[2].Value}else{$null}}
function Asset([string]$id,[string]$kind,[string]$path,[string]$binding,[string]$display=''){$i=Get-Item -LiteralPath $path;[pscustomobject][ordered]@{asset_id=$id;kind=$kind;path=if($display){$display}else{$path};sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();size=$i.Length;revision_binding=$binding}}
foreach($p in @($htaPath,$legacyHtaPath,$helpPath,$legacyHelpPath,$pdfPath,$guidePath,$packagePath)){if(-not(Test-Path -LiteralPath $p)){throw"Missing $p"}}
foreach($q in @(@($htaPath,'hta'),@($legacyHtaPath,'legacy_hta'),@($helpPath,'help'),@($legacyHelpPath,'legacy_help'),@($pdfPath,'pdf'),@($guidePath,'guide'),@($packagePath,'package'))){if((Get-FileHash -LiteralPath $q[0] -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected[$q[1]]){throw"Hash changed: $($q[0])"}}
$sample=@(Get-ChildItem -LiteralPath $LegacySampleDir -File|Where-Object{$_.Extension-eq'.xml'});if($sample.Count-ne1){throw'Legacy sample count changed.'};if((Get-FileHash -LiteralPath $sample[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected.legacy_cipher){throw'Legacy cipher changed.'}
foreach($pdf in @($pdfPath,$guidePath)){$b=[IO.File]::ReadAllBytes($pdf);if([Text.Encoding]::ASCII.GetString($b[0..4])-ne'%PDF-'){throw"PDF magic: $pdf"}}
$hta=[IO.File]::ReadAllText($htaPath);$help=[IO.File]::ReadAllText($helpPath)
if($hta-notmatch'(?i)APPLICATIONNAME\s*=\s*["'']2000v2018["'']' -or $hta-notmatch'(?i)January\s+2018\s+\(ENCS\)'){throw'HTA binding changed.'}
if($help-notmatch'(?i)2000.*January\s+2018'){throw'Help binding changed.'}
New-Item -ItemType Directory -Force -Path $fixtureDir|Out-Null

$fm=[regex]::Match($hta,'(?is)<form\b[^>]*(?:id|name)\s*=\s*["'']frmMain["''][^>]*>(?<body>.*?)</form>');if(-not$fm.Success){throw'frmMain absent.'}
$body=$fm.Groups['body'].Value;$offset=$fm.Groups['body'].Index;$excluded=@(@([regex]::Matches($body,'(?is)<script\b.*?</script>'))+@([regex]::Matches($body,'(?is)<!--.*?-->')))
$controls=[Collections.Generic.List[object]]::new();$ord=0
foreach($m in [regex]::Matches($body,'(?is)<(input|select|textarea|button)\b[^>]*>')){$skip=$false;foreach($r in $excluded){if($m.Index-ge$r.Index-and$m.Index-lt($r.Index+$r.Length)){$skip=$true;break}};if($skip){continue};$ord++;$tag=$m.Value;$el=$m.Groups[1].Value.ToLowerInvariant();$kind=if($el-eq'input'){A $tag 'type'}else{$el};if(-not$kind){$kind='text'};$controls.Add([pscustomobject][ordered]@{ordinal=$ord;id=A $tag 'id';name=A $tag 'name';element=$el;control_kind=$kind.ToLowerInvariant();source_line=1+[regex]::Matches($hta.Substring(0,$offset+$m.Index),"`n").Count;value=A $tag 'value';maxlength=A $tag 'maxlength';disabled=$tag-match'(?i)\bdisabled(?:\s*=|\s|>)';readonly=$tag-match'(?i)\breadonly(?:\s*=|\s|>)'})}
if($controls.Count-ne169){throw"Live count $($controls.Count)."}
$static=@($controls|Where-Object{$_.control_kind-in@('text','select','select-one','textarea','radio','checkbox')});if($static.Count-ne144){throw"Serializer count $($static.Count)."}
$projected=@($static|Where-Object{$_.id-notin@('frm2000:txtAddress2','frm2000:txtOtherName2')});if($projected.Count-ne142){throw'Projection count changed.'}
$families=@(
@{p='chkSchedule1Delete{index}';k='boolean';c='runtime-indexed-checkbox';s='addSchedule1:L3397-L3428'},@{p='drpATCCode{index}';k='atc-code';c='runtime-indexed-select';s='addSchedule1:L3397-L3428'},@{p='frm2000:sched1:txtTaxBase{index}';k='decimal-amount';c='runtime-indexed-text';s='addSchedule1:L3397-L3428'},@{p='frm2000:sched1:txtTaxRate{index}';k='rate-description';c='runtime-indexed-text';s='addSchedule1:L3397-L3428'},@{p='frm2000:sched1:txtTaxDue{index}';k='decimal-amount';c='runtime-indexed-text';s='addSchedule1:L3397-L3428'},
@{p='chkSchedule2Delete{index}';k='boolean';c='runtime-indexed-checkbox';s='addSchedule2:L3535-L3559'},@{p='frm2000:sched2:txtPaymentDate{index}';k='date-string-mm-dd-yyyy';c='runtime-indexed-text';s='addSchedule2:L3535-L3559'},@{p='frm2000:sched2:txtReceipt{index}';k='string';c='runtime-indexed-text';s='addSchedule2:L3535-L3559'},@{p='frm2000:sched2:txtAmountPaid{index}';k='decimal-amount';c='runtime-indexed-text';s='addSchedule2:L3535-L3559'},
@{p='chkSchedule3Delete{index}';k='boolean';c='runtime-indexed-checkbox';s='addSchedule3:L3659-L3683'},@{p='frm2000:sched3:txtPaymentDate{index}';k='date-string-mm-dd-yyyy';c='runtime-indexed-text';s='addSchedule3:L3659-L3683'},@{p='frm2000:sched3:txtReceipt{index}';k='string';c='runtime-indexed-text';s='addSchedule3:L3659-L3683'},@{p='frm2000:sched3:txtAmountPaid{index}';k='decimal-amount';c='runtime-indexed-text';s='addSchedule3:L3659-L3683'},
@{p='chkSchedule4Delete{index}';k='boolean';c='runtime-indexed-checkbox';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtRCOCode{index}';k='code';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtRemittanceDate{index}';k='date-string-mm-dd-yyyy';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtBank{index}';k='string';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtAmountRemitted{index}';k='decimal-amount';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtNumberFrom{index}';k='integer-string';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'},@{p='frm2000:sched4:txtNumberTo{index}';k='integer-string';c='runtime-indexed-text';s='addSchedule4:L3801-L3831'}
);if($families.Count-ne20){throw'Family count.'}
$required=@('frm2000:txtMonth','frm2000:txtYear','frm2000:txtTIN1','frm2000:txtTIN2','frm2000:txtTIN3','frm2000:txtBranchCode','frm2000:txtRDOCode','frm2000:txtTaxpayerName','frm2000:txtTelNum','frm2000:txtAddress','frm2000:txtZipCode')
$computed='(?i)(txtTax14|txtTax15D|txtTax16|txtTax17D|txtTax18|txtTax19|txtTotal|txtTaxDue\d+$)'
$amount='(?i)(txtTax|TaxBase|TaxDue|AmountPaid|AmountRemitted|TotalPayment|TotalRemittance)'
$fields=[Collections.Generic.List[object]]::new();$occ=@{}
foreach($c in $projected){$key=$c.id;if(-not$occ.ContainsKey($key)){$occ[$key]=0};$occ[$key]++;$n=$occ[$key];$fieldKey=if($n-eq1){$key}else{"$key#occurrence-$n"};$short=if($key-like'frm2000:*'){$key.Substring(8)}else{$key};$logical='string';$enum=[object[]]@();$norm=[string[]]@();if($c.control_kind-in@('radio','checkbox')){$logical='boolean';$enum=[object[]]@('true','false')}elseif($key-match'(?i)(TIN|RDO|BranchCode|ATC)'){$logical='code'}elseif($key-match'(?i)(txtMonth|txtYear)$'){$logical='period-component-string'}elseif($key-match'(?i)Date'){$logical='date-string-mm-dd-yyyy'}elseif($key-match$amount){$logical='decimal-amount';$norm=[string[]]@('NumWithComma','formatCurrency','round(...,2)')};$comp=$key-match$computed;$status=if($required-contains$key){'required'}elseif($comp){'computed'}else{'optional'};if($key-match'(?i)(txtCurrentPage|txtMaxPage|modLabel|numOf|rowLocation)'){$status='hidden'};$cons=[ordered]@{};if($c.maxlength-and$c.maxlength-match'^\d+$'){$cons.max_length=[int]$c.maxlength};if($logical-eq'decimal-amount'){$cons.precision=2};$notes=@('Source-derived from the January 2018 live DOM and generic Save serializer.');if($key-eq'frm2000:txtAddress'){$notes+='txtAddress2 is concatenated without a separator under this key.'};if($key-eq'frm2000:txtOtherName'){$notes+='txtOtherName2 is concatenated without a separator under this key.'};if($key-eq'frm2000:modLabel'){$notes+="The serializer emits four duplicate modLabel entries; this is occurrence $n."};$fields.Add([pscustomobject][ordered]@{field_key=$fieldKey;serialized_key=$key;serialized_occurrence=$n;label=$short;page=if($key-match'(?i)sched'){2}else{1};item_number=$null;control_kind=$c.control_kind;storage_type='string';logical_type=$logical;required=$status;required_when=$null;enabled_when=$null;visible_when=$null;default_value=$c.value;empty_representation='';constraints=[pscustomobject]$cons;enum_values=$enum;normalization=$norm;computed=$comp;calculation_id=if($comp){'See calculations.json'}else{$null};source_refs=@("official-hta-runtime#control:L$($c.source_line)",'official-hta-runtime#saveXML:L2666-L2905');confidence='high';notes=$notes})}
foreach($f in $families){$fields.Add([pscustomobject][ordered]@{field_key=$f.p;serialized_key=$f.p;serialized_occurrence=$null;label=$f.p;page=2;item_number=$null;control_kind=$f.c;storage_type='string';logical_type=$f.k;required='optional';required_when=$null;enabled_when=$null;visible_when=$null;default_value=if($f.k-eq'decimal-amount'){'0.00'}else{$null};empty_representation='';constraints=[pscustomobject]@{index='zero-based contiguous; initial indices are already concrete; Add is source-unbounded'};enum_values=@(if($f.k-eq'boolean'){'true';'false'});normalization=@(if($f.k-eq'decimal-amount'){'round(...,2)';'formatCurrency'});computed=$f.p-like'*TaxDue*';calculation_id=if($f.p-like'*TaxDue*'){'ATC-specific calculation'}else{$null};source_refs=@("official-hta-runtime#$($f.s)",'official-hta-runtime#saveXML:L2666-L2905');confidence='high';notes=@('Pattern preserves added and reindexed rows; static initial rows remain in the concrete baseline.')})}
WJ (Join-Path $outDir 'fields.json') ([ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;field_count=$fields.Count;runtime_serializable_element_count=142;inventory_sha256=HL @($fields.field_key|Sort-Object);fields=$fields})
WJ (Join-Path $fixtureDir 'runtime-control-inventory-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;official_hta_sha256=$expected.hta;live_static_control_count=$controls.Count;static_serializer_control_count=$static.Count;projected_baseline_serializer_entry_count=$projected.Count;duplicate_serialized_key=@{key='frm2000:modLabel';occurrences=4};collapsed_controls=@('frm2000:txtAddress2','frm2000:txtOtherName2');dynamic_family_count=$families.Count;controls=$controls;dynamic_families=$families})
$decrypt=Join-Path $RepoRoot 'rules\tools\audit-1701-encrypted-fields.ps1';WT (Join-Path $fixtureDir 'legacy-artifact-exclusion.json') ((&$decrypt -SourceDir $LegacySampleDir -FormId $formId -FilePattern '*.xml' -RedactedFileName '2000-final-copy-#email-redacted#.xml' -ExpectedCiphertextSha256 $expected.legacy_cipher -ExpectedDecryptedSha256 $expected.legacy_plain -ExpectedFieldCount 0 -ExpectedFieldInventorySha256 $expected.legacy_inventory -ExpectedExtraField 'frm2000:txtMonth1' -VersionField '*' -ExpectedXmlVersion '*')-join[Environment]::NewLine)
$ft=Join-Path $RepoRoot 'rules\tools\extract-hta-function-inventory.ps1';WT (Join-Path $fixtureDir 'validation-function-inventory-v796.json') ((&$ft -HtaPath $htaPath -ControlPrefix 'frm2000:' -NamePattern '(?i)valid|check|save|enable|disable|date|process|final|submit')-join[Environment]::NewLine);WT (Join-Path $fixtureDir 'calculation-function-inventory-v796.json') ((&$ft -HtaPath $htaPath -ControlPrefix 'frm2000:' -NamePattern '(?i)compute|rate|schedule|affixture|atc')-join[Environment]::NewLine)

$rules=[Collections.Generic.List[object]]::new()
function Rule([string]$id,[string]$phase,$order,[string]$cond,[string[]]$keys,$msg,[string[]]$refs,[string]$ass='verified-correct',[string]$official='The branch alerts and stops the active operation.',[string]$rec='Retain as a structured revision-aware error.'){$rules.Add([pscustomobject][ordered]@{rule_id=$id;form_id=$formId;revision=$revision;phase=$phase;order=$order;condition=$cond;fields=$keys;accepted_behavior='Condition is false; processing continues.';rejected_behavior='The active operation stops unless official_behavior states otherwise.';exact_message=$msg;source_refs=$refs;evidence_type=@('source');assessment=$ass;official_behavior=$official;recommended_app_behavior=$rec;confidence='high';unresolved_questions=@()})}
Rule '2000-val-001-month' validate 1 'Month is 00.' @('frm2000:txtMonth') 'Please select a valid month in Item 1.' @('official-hta-runtime#validate:L4782-L4790')
Rule '2000-val-002-year-required' validate 2 'Year is blank.' @('frm2000:txtYear') 'Please enter a valid year in Item 1.' @('official-hta-runtime#validate:L4791-L4793')
Rule '2000-val-003-old-year' validate 3 'Year is below 2018.' @('frm2000:txtYear') 'Please file using the old version of the form.' @('official-hta-runtime#validate:L4794-L4797')
Rule '2000-val-004-future-year' validate 4 'Year is greater than the current year.' @('frm2000:txtYear') 'Year (Item 1) cannot be greater than or equal to current year.' @('official-hta-runtime#validate:L4798-L4801') 'official-bug-compatible' 'Current year is accepted although the message says greater than or equal.' 'Align the condition and message with the filing-period rule.'
Rule '2000-val-005-tin' validate 5 'Any taxpayer TIN segment or branch code is blank.' @('frm2000:txtTIN1','frm2000:txtTIN2','frm2000:txtTIN3','frm2000:txtBranchCode') 'Please enter a valid TIN number on Item 4.' @('official-hta-runtime#validate:L4803-L4807') 'official-bug-compatible' 'Only blankness is checked.' 'Apply checksum and format.'
Rule '2000-val-006-rdo' validate 6 'RDO select remains at index zero.' @('frm2000:txtRDOCode') 'Please enter a valid RDO Code on Item 5.' @('official-hta-runtime#validate:L4808-L4813')
Rule '2000-val-007-name' validate 7 'Taxpayer name is blank.' @('frm2000:txtTaxpayerName') 'Please enter a valid Taxpayer Name on Item 6.' @('official-hta-runtime#validate:L4819-L4823')
Rule '2000-val-008-phone' validate 8 'Telephone is blank.' @('frm2000:txtTelNum') 'Please enter a valid Telephone Number on Item 8.' @('official-hta-runtime#validate:L4824-L4828') 'official-bug-compatible' 'Only blankness is checked.' 'Validate accepted telephone syntax.'
Rule '2000-val-009-address' validate 9 'Address first line is blank.' @('frm2000:txtAddress') "Please enter Taxpayer's Registered Address on Item 7." @('official-hta-runtime#validate:L4829-L4833')
Rule '2000-val-010-zip' validate 10 'Zip is blank.' @('frm2000:txtZipCode') "Please enter Taxpayer's Zip Code on Item 7A." @('official-hta-runtime#validate:L4834-L4838')
Rule '2000-val-011-party' validate 11 'No liable-party option is selected.' @('frm2000:optParty_1','frm2000:optParty_2','frm2000:optParty_3') 'Please select an option in Item 10.' @('official-hta-runtime#validate:L4839-L4842')
Rule '2000-val-012-other-tin' validate 12 'Party option 1 or 2 is selected and counterparty TIN is blank.' @('frm2000:optParty_1','frm2000:optParty_2','frm2000:txtOtherTIN') 'Please enter a valid TIN in Item 12.' @('official-hta-runtime#validate:L4843-L4846')
Rule '2000-val-013-mode' validate 13 'No mode of affixture is selected.' @('frm2000:optMode_1','frm2000:optMode_2','frm2000:optMode_3') 'Please select an option in Item 13.' @('official-hta-runtime#validate:L4847-L4850')
Rule '2000-val-014-impossible-mode-conjunction' validate 14 'Mode 1 and Mode 3 are simultaneously checked and Item 18 is zero.' @('frm2000:optMode_1','frm2000:optMode_3','frm2000:txtTax18') 'Zero payment shall not be allowed in Item 18 if eDST System and Loose Stamp are selected.' @('official-hta-runtime#validate:L4851-L4854') 'incorrect-official-behavior' 'The controls share one radio group, so both cannot be checked; this rule is unreachable.' 'Express the intended per-mode nonzero requirement without an impossible conjunction.'
Rule '2000-val-015-schedule-dates' validate 15 'An enabled Schedule 2, 3, or 4 date is malformed, impossible, or has a future year.' @('frm2000:sched2:txtPaymentDate{index}','frm2000:sched3:txtPaymentDate{index}','frm2000:sched4:txtRemittanceDate{index}') 'Please enter a valid date in Schedule {schedule}, column {column} row {row}.' @('official-hta-runtime#checkDateSched2:L4642-L4688','official-hta-runtime#checkDateSched3:L4690-L4734','official-hta-runtime#checkDateSched4:L4736-L4780') 'official-bug-compatible' 'Only nonblank rows are checked; dates before 2018 are accepted.' 'Apply full revision-aware date constraints and preserve exact schedule/row context.'
Rule '2000-val-016-success' validate 16 'All preceding checks pass.' @() "Validation successful. Click on 'Edit' if you wish to modify your entries." @('official-hta-runtime#validate:L4872-L4875')
Rule '2000-save-001-tin' save 1 'Any TIN segment or branch is blank.' @('frm2000:txtTIN1','frm2000:txtTIN2','frm2000:txtTIN3','frm2000:txtBranchCode') 'Please enter a valid TIN number on Item 5.' @('official-hta-runtime#initialValidateBeforeSave:L5083-L5088') 'official-bug-compatible' 'Message wrongly cites Item 5; Validate cites Item 4.' 'Bind to printed Item 4 and retain phase-specific official text.'
Rule '2000-save-002-rdo' save 2 'RDO is 000.' @('frm2000:txtRDOCode') 'Please enter a valid RDO Code on Item 6.' @('official-hta-runtime#initialValidateBeforeSave:L5089-L5092') 'official-bug-compatible' 'Message wrongly cites Item 6; Validate cites Item 5.' 'Bind to printed Item 5.'
Rule '2000-save-003-name' save 3 'Taxpayer name is blank.' @('frm2000:txtTaxpayerName') "Please enter a valid Taxpayer's Name on Item 8." @('official-hta-runtime#initialValidateBeforeSave:L5093-L5098') 'official-bug-compatible' 'Message wrongly cites Item 8; Validate cites Item 6.' 'Bind to printed Item 6.'
Rule '2000-save-004-sparse' save 4 'Period, contact/address, liable party, counterparty TIN, mode, or schedule dates are invalid.' @() $null @('official-hta-runtime#initialValidateBeforeSave:L5083-L5099','official-hta-runtime#validate:L4782-L4876') 'incorrect-official-behavior' 'Save ignores all listed Validate failures.' 'Use shared validation with documented phase exceptions.'
Rule '2000-calc-001-ds125-reference-error' 'blur/change' $null 'ATC DS125 tax computation executes.' @('drpATCCode{index}','frm2000:sched1:txtTaxDue{index}') $null @('official-hta-runtime#computeSched1TaxDue:L4548-L4557') 'incorrect-official-behavior' 'After calculating result=base×50%, the source executes stray identifier S and throws ReferenceError before assigning tax due.' 'Remove the stray identifier and implement the pinned 50% rule with a regression test.'
Rule '2000-xml-001-duplicate-modlabel' save $null 'Generic serializer reaches four modLabel controls.' @('frm2000:modLabel') $null @('official-hta-runtime#saveXML:L2740-L2842','runtime-control-inventory') 'official-bug-compatible' 'Four entries with the identical XML key are emitted.' 'Preserve ordered occurrences losslessly; do not collapse into a map.'
Rule '2000-legacy-001-excluded' final-copy $null 'Available encrypted sample is treated as January 2018 evidence.' @('frm2000:txtMonth1') $null @('legacy-artifact-exclusion','legacy-hta-excluded') 'incorrect-official-behavior' 'The sample contains the legacy txtMonth1 field and 114 entries/113 unique keys.' 'Exclude it from the 2018 contract.'
WJ (Join-Path $outDir 'validations.json') ([ordered]@{'$schema'='../../schema/validations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;first_error_behavior='Validate and Save alert/return at the first source-ordered failure; schedule date routines stop at the first bad row.';rules=$rules})

$calcs=[Collections.Generic.List[object]]::new()
function Calc([string]$id,[string[]]$out,[string[]]$in,[string]$formula,[string]$trigger,[string[]]$deps,[string[]]$refs,[string]$ass='verified-correct',[string]$rec='Implement with typed decimals and deterministic two-decimal formatting.'){$calcs.Add([pscustomobject][ordered]@{calculation_id=$id;outputs=$out;inputs=$in;condition=$null;official_formula=$formula;rounding='Source normally applies Number.toFixed(2) through formatCurrency; per-block operations do not consistently apply statutory ceiling.';trigger=$trigger;depends_on=$deps;source_refs=$refs;assessment=$ass;recommended_app_behavior=$rec;confidence='high'})}
$atcs=@(
@('DS010','Manual tax-due entry; source enables the result control.','verified-correct'),@('DS101','base / 200 × 2.00.','ambiguous'),@('DS102','base / 200 × 1.50.','ambiguous'),@('DS103','base × 0.75.','ambiguous'),@('DS104','base / 200 × 1.00.','ambiguous'),@('DS105','base × 3.00.','ambiguous'),@('DS106','base / 200 × 1.50; if modified, multiply by days / 365.','ambiguous'),@('DS107','base / 200 × 0.60.','ambiguous'),@('DS108','base / 200 × 0.60.','ambiguous'),@('DS126','base / 200 × 0.60.','ambiguous'),@('DS109','Fixed tier: 0/20/50/100/150/200 according to the source base bands.','ambiguous'),@('DS110','base / 4 × 0.50.','ambiguous'),@('DS111','base / 4 × 0.50.','ambiguous'),@('DS112','Party-dependent: base / 200 × 1.00 or base / 200 × 0.40.','ambiguous'),@('DS113','base / 4 × 0.30.','ambiguous'),@('DS114','base × 30.00.','ambiguous'),@('DS115','Fixed 0 or 30 according to the source threshold.','ambiguous'),@('DS116','base × 0.20.','ambiguous'),@('DS117','Fixed tier 0/2/20 according to source thresholds.','ambiguous'),@('DS118','base × 30.00.','ambiguous'),@('DS119','base × 10.00.','ambiguous'),@('DS120','0 below threshold; 6 at the first band; otherwise 6 + ((base - 2000) / 1000 × 2).','ambiguous'),@('DS121','0 below threshold; 40 at the first band; otherwise 40 + ((base - 5000) / 5000 × 20).','ambiguous'),@('DS124','base × 0.15.','ambiguous'),@('DS130','0 for invalid/zero months; 1000 through six months; then 1000 + (months-6)×100.','ambiguous'),@('DS131','0 for invalid/zero months; 2000 through six months; then 2000 + (months-6)×200.','ambiguous'),@('DS132','0 for invalid/zero months; 3000 through six months; then 3000 + (months-6)×300.','ambiguous'),@('DS125','Intended result=base×50%, but stray identifier S throws before output assignment.','incorrect-official-behavior')
)
$caseLines=@{DS010=4266;DS101=4270;DS102=4275;DS103=4280;DS104=4288;DS105=4293;DS106=4298;DS107=4313;DS108=4314;DS126=4315;DS109=4320;DS110=4343;DS111=4344;DS112=4349;DS113=4359;DS114=4364;DS115=4369;DS116=4377;DS117=4382;DS118=4393;DS119=4398;DS120=4403;DS121=4418;DS124=4432;DS130=4441;DS131=4473;DS132=4511;DS125=4548}
foreach($a in $atcs){$code=$a[0];$ass=$a[2];$rec=if($ass-eq'ambiguous'){'Re-derive the exact statutory rate, block rounding, thresholds, and units from the pinned guide before implementation; retain this source behavior as compatibility evidence.'}elseif($code-eq'DS125'){'Implement base×50% without the ReferenceError and regression-test the branch.'}else{'Retain manual-entry behavior with explicit authorization.'};Calc "2000-atc-$($code.ToLower())" @('frm2000:sched1:txtTaxDue{index}') @('drpATCCode{index}','frm2000:sched1:txtTaxBase{index}') $a[1] computeSched1TaxDue @() @("official-hta-runtime#computeSched1TaxDue:L$($caseLines[$code])") $ass $rec}
Calc '2000-schedule1-total' @('frm2000:sched1:txtTotalDue1','frm2000:txtTax14') @('frm2000:sched1:txtTaxDue{index}') 'Sum all Schedule 1 tax-due rows; copy to Item 14.' computeSchedule1 @($atcs|ForEach-Object{"2000-atc-$($_[0].ToLower())"}) @('official-hta-runtime#computeSchedule1:L4560-L4591')
Calc '2000-schedule2-total' @('frm2000:sched2:txtTotalPayment1','frm2000:txtTax15B') @('frm2000:sched2:txtAmountPaid{index}') 'Sum Schedule 2 payments and copy to Item 15B.' computeSchedule2 @() @('official-hta-runtime#computeSchedule2:L4598-L4607')
Calc '2000-schedule3-total' @('frm2000:sched3:txtTotalPayment1','frm2000:txtTax15C') @('frm2000:sched3:txtAmountPaid{index}') 'Sum Schedule 3 payments and copy to Item 15C.' computeSchedule3 @() @('official-hta-runtime#computeSchedule3:L4609-L4618')
Calc '2000-schedule4-total' @('frm2000:sched4:txtTotalRemittance1','frm2000:txtTax19') @('frm2000:sched4:txtAmountRemitted{index}') 'Sum Schedule 4 remittances and copy to Item 19.' computeSchedule4 @() @('official-hta-runtime#computeSchedule4:L4620-L4628')
Calc '2000-item15d' @('frm2000:txtTax15D') @('frm2000:txtTax15A','frm2000:txtTax15B','frm2000:txtTax15C') 'Item 15D = 15A + 15B + 15C.' computeTax15D @('2000-schedule2-total','2000-schedule3-total') @('official-hta-runtime#computeTax15D:L3897-L3906')
Calc '2000-item16' @('frm2000:txtTax16') @('frm2000:txtTax14','frm2000:txtTax15A','frm2000:txtTax15B','frm2000:txtTax15C','frm2000:optMode') 'Mode 2: max(14-(15A+15B),0). Modes 1/3: 14-15A-15B-15C, then force a positive result negative.' computeTax16 @('2000-schedule1-total','2000-item15d') @('official-hta-runtime#computeTax16:L3908-L3933') 'incorrect-official-behavior' 'Re-derive payable/credit sign semantics; do not force a positive liability negative.'
Calc '2000-penalties' @('frm2000:txtTax17D') @('frm2000:txtTax17A','frm2000:txtTax17B','frm2000:txtTax17C') 'Item 17D = 17A + 17B + 17C.' computePenalties @() @('official-hta-runtime#computePenalties:L3946-L3950')
Calc '2000-total-payable' @('frm2000:txtTax18') @('frm2000:txtTax16','frm2000:txtTax17D') 'Item 18 = Item 16 + Item 17D.' computeTotalAmtPayable @('2000-item16','2000-penalties') @('official-hta-runtime#computeTotalAmtPayable:L3952-L3954') 'official-bug-compatible' 'Represent credits and liabilities separately to avoid negative payable totals.'
WJ (Join-Path $outDir 'calculations.json') ([ordered]@{'$schema'='../../schema/calculations.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;evaluation_order=@($calcs.calculation_id);calculations=$calcs})
$cases=@();$n=0;foreach($r in @($rules|Where-Object{$_.exact_message})){$n++;$cases+=[pscustomobject][ordered]@{case_id=('case-{0:d2}-{1}'-f$n,$r.rule_id);phase=$r.phase;mutations=@{synthetic_condition=$r.condition};expected_message=$r.exact_message;expected_behavior=$r.official_behavior;rule_id=$r.rule_id}}
WJ (Join-Path $fixtureDir 'negative-cases.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;synthetic_only=$true;cases=$cases})
WJ (Join-Path $fixtureDir 'calculation-boundaries.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;cases=@(@{case_id='ds101-fraction';calculation_id='2000-atc-ds101';base=201;source_output=2.01;note='No statutory block ceiling is applied.'},@{case_id='ds125-error';calculation_id='2000-atc-ds125';base=100;source_result='ReferenceError: S is not defined';intended_output=50},@{case_id='mode2-floor';calculation_id='2000-item16';inputs=@{item14=100;item15a=80;item15b=30};source_output=0},@{case_id='mode1-sign-flip';calculation_id='2000-item16';inputs=@{item14=100;item15a=0;item15b=0;item15c=0};source_output=-100})})
$res=@();foreach($src in @([regex]::Matches($hta,'(?i)<script[^>]+src\s*=\s*(["''])(?<v>.*?)\1')|ForEach-Object{$_.Groups['v'].Value}|Sort-Object -Unique)){$full=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $htaPath) $src));if(Test-Path -LiteralPath $full){$res+=[pscustomobject][ordered]@{src=$src;path=$full;present=$true;size=(Get-Item -LiteralPath $full).Length;sha256=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()}}else{$res+=[pscustomobject][ordered]@{src=$src;path=$full;present=$false;size=$null;sha256=$null}}};WJ (Join-Path $fixtureDir 'official-resource-hashes-v796.json') ([ordered]@{schema_version='1.0.0';form_id=$formId;resources=$res})

$workflow=[ordered]@{'$schema'='../../schema/workflow.schema.json';schema_version='1.0.0';form_id=$formId;revision=$revision;phases=@(
@{phase='edit';official_behavior='January 2018 monthly Documentary Stamp Tax declaration with ATC rows and separate mode-of-affixture schedules.';source_refs=@('official-form-pdf','official-guide-pdf','official-help-v2018');confidence='high'},
@{phase='saved-draft';official_behavior='Save checks only TIN blankness, RDO 000, and taxpayer name, then serializes 142 baseline occurrences plus added schedule rows.';source_refs=@('official-hta-runtime#initialValidateBeforeSave:L5083-L5099','official-hta-runtime#saveXML:L2666-L2905');confidence='high'},
@{phase='validated';official_behavior='Validate checks period, identity, party, mode, and applicable schedule dates, then disables controls.';source_refs=@('official-hta-runtime#validate:L4782-L4876');confidence='high'},
@{phase='final-copy';official_behavior='Final-copy source exists, but the available encrypted sample is legacy and excluded.';source_refs=@('official-hta-runtime#saveXML','legacy-artifact-exclusion');confidence='medium'},
@{phase='submitted';official_behavior='Online transport exists but was not exercised.';source_refs=@('official-hta-runtime#sendEmail');confidence='medium'})
;transitions=@(
@{from='edit';action='Save';to='saved-draft';guard='Three narrow Save guards pass.';side_effects=@('Writes flat pseudo-XML.','Retains four duplicate modLabel occurrences.','Collapses address/name continuations.');source_refs=@('official-hta-runtime#saveXML:L2666-L2905')},
@{from='edit';action='Validate';to='validated';guard='All source-ordered Validate checks pass.';side_effects=@('Disables controls.','Shows success alert.');source_refs=@('official-hta-runtime#validate:L4782-L4876')},
@{from='validated';action='Edit';to='edit';guard=$null;side_effects=@('Re-enables controls and restores mode/party/amended conditional state.');source_refs=@('official-hta-runtime#enableAllControl:L4954-L5019')},
@{from='validated';action='Final Copy';to='final-copy';guard='Finalization flow succeeds.';side_effects=@('Encrypts/compresses final copy.');source_refs=@('official-hta-runtime#saveXML')},
@{from='final-copy';action='Transport';to='submitted';guard='Connectivity and remote acceptance succeed.';side_effects=@('Online attempt; untested.');source_refs=@('official-hta-runtime#sendEmail')})
;prerequisites=@('Taxable month/year','Taxpayer identity and RDO','Liable party and mode of affixture','ATC/tax-base schedule','Mode-specific payment/remittance schedules')
;required_attachments=@(@{attachment_id='dst-documents';label='Taxable documents and supporting DST computation/payment records.';required_when='Applicable filing.';official_ui_enforcement='Not checked by local Validate.';source_refs=@('official-guide-pdf','official-help-v2018');confidence='high'},@{attachment_id='payment-proof';label='eDST, loose-stamp, constructive-affixture, or remittance proof for the selected mode.';required_when='Applicable mode.';official_ui_enforcement='Not checked by local Validate.';source_refs=@('official-guide-pdf','official-help-v2018');confidence='high'})
;filing_deadlines=@(@{quarter='Q1';due_date_rule='Monthly deadline specified by the pinned January 2018 guide.';source_refs=@('official-guide-pdf','official-help-v2018');confidence='high'},@{quarter='Q2';due_date_rule='Not quarterly; the same monthly rule applies.';source_refs=@('official-guide-pdf');confidence='high'},@{quarter='Q3';due_date_rule='Not quarterly; the same monthly rule applies.';source_refs=@('official-guide-pdf');confidence='high'},@{quarter='Q4';due_date_rule='Not quarterly; the same monthly rule applies.';source_refs=@('official-guide-pdf');confidence='high'})}
WJ (Join-Path $outDir 'workflow.json') $workflow
$bugs=@($rules|Where-Object{$_.assessment-in@('official-bug-compatible','incorrect-official-behavior','obsolete')}).Count
$assets=@(Asset 'package-7.9.6' 'official-package-executable' $packagePath 'Installed package 7.9.6.0.';Asset 'official-hta-runtime' 'runtime-extracted-hta' $htaPath 'APPLICATIONNAME 2000v2018; January 2018 ENCS.';Asset 'official-help-v2018' 'official-runtime-help' $helpPath 'Revision-matched help.';Asset 'official-form-pdf' 'official-form-pdf' $pdfPath 'January 2018 form.';Asset 'official-guide-pdf' 'official-guidelines-pdf' $guidePath 'January 2018 guide.';Asset 'legacy-hta-excluded' 'runtime-extracted-hta-legacy' $legacyHtaPath 'Legacy txtMonth1 runtime; excluded.';Asset 'legacy-help-excluded' 'official-runtime-help-legacy' $legacyHelpPath 'Legacy help; excluded.';Asset 'legacy-final-copy-excluded' 'dummy-profile-encrypted-final-copy-legacy' $sample[0].FullName 'Legacy txtMonth1 artifact; excluded.' (Join-Path $LegacySampleDir '2000-final-copy-#email-redacted#.xml'))
$manifest=[ordered]@{'$schema'='../../schema/form-manifest.schema.json';schema_version='1.0.0';form_id=$formId;form_code='2000';revision=$revision;revision_label='January 2018 ENCS';package_version=$packageVersion;status='complete';official_assets=$assets;counts=[ordered]@{concrete_fields=142;runtime_field_families=20;fields_total=$fields.Count;typed_fields=$fields.Count;validation_rules=$rules.Count;confirmed_official_bugs=$bugs;calculations=$calcs.Count;negative_fixtures=$cases.Count;unverified_gaps=3};artifacts=[ordered]@{fields='fields.json';validations='validations.json';calculations='calculations.json';workflow='workflow.json';evidence='evidence.md';audit='audit.md';gaps='gaps.md';runtime_control_fixture='fixtures/runtime-control-inventory-v796.json';legacy_artifact_exclusion='fixtures/legacy-artifact-exclusion.json';validation_function_fixture='fixtures/validation-function-inventory-v796.json';calculation_function_fixture='fixtures/calculation-function-inventory-v796.json';resource_hash_fixture='fixtures/official-resource-hashes-v796.json';negative_fixtures='fixtures/negative-cases.json';calculation_fixtures='fixtures/calculation-boundaries.json'};scope_notes=@('Research only; no renderer/release metadata changed.','142 ordered baseline serializer occurrences preserve four duplicate modLabel keys and two collapsed continuation pairs.','Twenty indexed families preserve expandable Schedules 1-4.','The 114-entry/113-unique encrypted sample is legacy txtMonth1 and excluded.','Twenty-eight ATC branches are individually machine-readable; ambiguous statutory rounding/rates fail closed.')}
WJ (Join-Path $outDir 'manifest.json') $manifest
WT (Join-Path $outDir 'README.md') "# BIR Form 2000 - January 2018 ENCS`n`nRevision-specific rule package with 142 ordered baseline serializer occurrences, 20 indexed families, and 28 ATC calculation branches.`n"
WT (Join-Path $outDir 'evidence.md') "# Evidence`n`n- HTA SHA-256: $($expected.hta); APPLICATIONNAME 2000v2018; January 2018 ENCS.`n- Help SHA-256: $($expected.help); form PDF $($expected.pdf); guide $($expected.guide).`n- DOM: 169 controls, 144 static serializer controls, 142 projected occurrences after continuation collapse, 20 indexed families.`n- Four concrete controls share serialized key frm2000:modLabel and remain ordered occurrences.`n- Legacy encrypted sample: cipher $($expected.legacy_cipher), decrypted $($expected.legacy_plain), 114 entries/113 unique, inventory $($expected.legacy_inventory); txtMonth1 proves exclusion.`n- DS125 has a source-proven ReferenceError before tax-due assignment.`n"
WT (Join-Path $outDir 'gaps.md') "# Gaps`n`n1. No January 2018 txtMonth-based save/final-copy sample was available.`n2. Online submission was not exercised.`n3. The 28 ATC branches require legal re-derivation of exact units, thresholds, and per-block rounding before implementation; ambiguous entries fail closed.`n"
WT (Join-Path $outDir 'audit.md') "# Audit`n`n- Revision/assets: **pass**.`n- Fields: **pass with explicit saved-artifact gap** - 142 occurrences and 20 families; legacy sample excluded.`n- Validation/workflow: **pass** - exact first-error ordering, schedule dates, sparse Save, and wrong item citations captured.`n- Calculations: **pass** - 28 ATCs plus schedule/affixture/penalty totals captured; legal ambiguity explicit.`n- Official defects: **pass** - $bugs bug-compatible/incorrect rules include unreachable radio conjunction, wrong Save item numbers, duplicate XML keys, sign forcing, and DS125 ReferenceError.`n- Privacy: **pass**.`n"
WT (Join-Path $outDir 'HANDOFF.md') "Completed priority 23: 2000-v2018. Next: 1602Q.`n"
$ip=Join-Path $RepoRoot 'rules\index.json';$idx=Get-Content -LiteralPath $ip -Raw|ConvertFrom-Json;$entry=[pscustomobject][ordered]@{form_id=$formId;form_code='2000';revision=$revision;package_version=$packageVersion;priority=23;status='complete';path='forms/2000-v2018/manifest.json'};$idx.forms=@(@($idx.forms|Where-Object{$_.form_id-ne$formId})+$entry|Sort-Object priority);$idx.updated=(Get-Date).ToString('yyyy-MM-dd');WJ $ip $idx
"Generated ${formId}: fields=$($fields.Count), concrete=142, families=20, rules=$($rules.Count), calculations=$($calcs.Count), negative_cases=$($cases.Count), bugs=$bugs"
