param([Parameter(Mandatory = $true)][string]$OutputPath)

$ErrorActionPreference = 'Stop'
$form = '1601eq-v2018'
$revision = '2018-01-01'
$rules = @()

function Add-Rule {
    param(
        [string]$Id, [string]$Phase, [Nullable[int]]$Order, [string]$Condition, [string[]]$Fields,
        [string]$Message, [string[]]$Sources, [string[]]$Evidence, [string]$Assessment,
        [string]$Official, [string]$Recommended, [string]$Confidence = 'high',
        [string[]]$Questions = @(), [string]$Accepted = 'Condition is false and processing continues.',
        [string]$Rejected = 'Official processing applies the documented rejection or mutation.'
    )
    $script:rules += [ordered]@{
        rule_id=$Id; form_id=$form; revision=$revision; phase=$Phase; order=$Order; condition=$Condition; fields=$Fields;
        accepted_behavior=$Accepted; rejected_behavior=$Rejected; exact_message=$Message; source_refs=$Sources;
        evidence_type=$Evidence; assessment=$Assessment; official_behavior=$Official; recommended_app_behavior=$Recommended;
        confidence=$Confidence; unresolved_questions=$Questions
    }
}

Add-Rule '1601eq-input-001' 'input' $null 'A keypress in year, sheet count, TIN core segments, ZIP code, or telephone is not a digit or an allowed control key.' @('frm1601EQ:txtYear','frm1601EQ:txtNoSheets','frm1601EQ:txtTIN1','frm1601EQ:txtTIN2','frm1601EQ:txtTIN3','frm1601EQ:txtZipCode','frm1601EQ:txtTelNum') $null @('official-hta-runtime#L276,L355,L391-L393,L495,L513','shared-string-util#wholenumber:L364-L387') @('runtime-dom','source') 'verified-correct' 'wholenumber permits digits plus Backspace, Tab, Enter, Escape and equivalent control keys.' 'Apply the same character filter, but also validate complete values after paste/programmatic assignment.'
Add-Rule '1601eq-input-002' 'input' $null 'A branch-code keypress is not ASCII A-Z/a-z, 0-9, or an allowed control key.' @('frm1601EQ:txtBranchCode') $null @('official-hta-runtime#L394','shared-string-util#letternumber:L389-L412') @('runtime-dom','source') 'verified-correct' 'Branch input accepts ASCII alphanumeric characters and has maxlength 5.' 'Normalize to uppercase and validate the official branch-code shape as a complete value.'
Add-Rule '1601eq-input-003' 'input' $null 'A runtime ATC tax-base keypress is not a digit, dot, or allowed control key.' @('frm1601EQ:txtTaxBase1','frm1601EQ:txtTaxBase2','frm1601EQ:txtTaxBase3','frm1601EQ:txtTaxBase4','frm1601EQ:txtTaxBase5','frm1601EQ:txtTaxBase6') $null @('official-hta-runtime#getATCCode:L2922-L2929','shared-string-util#numbersonly:L148-L174') @('source','runtime-dom') 'official-bug-compatible' 'The later duplicate numbersonly declaration wins and permits any number of decimal points; blur round() converts malformed text to 0.00.' 'Accept one optional decimal point and reject malformed pasted/programmatic values instead of silently coercing them to zero.'
Add-Rule '1601eq-input-004' 'input' $null 'Text exceeds the control maxlength.' @('frm1601EQ:txtYear','frm1601EQ:txtNoSheets','frm1601EQ:txtTIN1','frm1601EQ:txtTIN2','frm1601EQ:txtTIN3','frm1601EQ:txtBranchCode','frm1601EQ:txtTaxpayerName','frm1601EQ:txtAddress','frm1601EQ:txtZipCode','frm1601EQ:txtTelNum','txtEmail') $null @('official-hta-runtime#L276-L539') @('runtime-dom') 'verified-correct' 'HTML maxlength bounds typed input: year 4, sheets 2, TIN cores 3 each, branch 5, name 50, each address line 150, ZIP 12, telephone 20, email 20.' 'Enforce the same storage limits with explicit validation errors, including paste and import paths.'
Add-Rule '1601eq-blur-001' 'blur/change' $null 'Taxpayer name or address loses focus.' @('frm1601EQ:txtTaxpayerName','frm1601EQ:txtAddress') $null @('official-hta-runtime#L435,L472','shared-string-util#capital') @('runtime-dom','source') 'verified-correct' 'capital uppercases and trims the value on blur.' 'Normalize deterministically at the model boundary as well as in the editor.'
Add-Rule '1601eq-blur-002' 'blur/change' $null 'A tax base loses focus.' @('frm1601EQ:txtTaxBase1','frm1601EQ:txtTaxBase2','frm1601EQ:txtTaxBase3','frm1601EQ:txtTaxBase4','frm1601EQ:txtTaxBase5','frm1601EQ:txtTaxBase6') $null @('official-hta-runtime#getATCCode:L2922-L2929','shared-string-util#round:L286-L319') @('source','runtime-dom') 'official-bug-compatible' 'round() truncates integer input to 12 digits, rounds half-up to two decimals, comma-groups, and coerces NaN or excess precision to 0.00.' 'Use decimal arithmetic, reject excess precision/length explicitly, and never silently replace malformed input with zero.'
Add-Rule '1601eq-change-001' 'blur/change' $null 'Taxable year changes.' @('frm1601EQ:txtYear') $null @('official-hta-runtime#changeYear:L2636-L2641','official-hta-runtime#changeATCRate:L2665-L2690','fixtures/atc-catalog-v796.json','official-2019-pdf#p2:ATC-rates') @('source','runtime-binary','official-pdf') 'incorrect-official-behavior' 'Existing selected ATC rates and withheld amounts are recomputed; for year <=2018 WI/WC650=25%, WI/WC651=32%, and WI/WC663 or WI/WC710=20%. For later years the package catalog is used, but it retains confirmed stale/wrong rates including Government WC651=32 and WC710=20, and WI/WC661=10, where the January 2019 form prints 15.' 'Represent rates as effective-dated, revision-scoped catalog data; for January 2019 use the official PDF values and recompute dependent amounts transactionally.'
Add-Rule '1601eq-change-002' 'blur/change' $null 'Category changes after at least one ATC row exists and the user confirms.' @('frm1601EQ:optCategory:P','frm1601EQ:optCategory:G') 'By changing Category your selected ATC will be remove.' @('official-hta-runtime#changeCategory:L2717-L2756') @('source') 'official-bug-compatible' 'A confirmation is shown; confirmation clears Items 19-30, all selected ATCs, and both ATC tables. Cancellation reverses the category radio choice.' 'Use grammatical warning text and clear only after an explicit confirmation while preserving a recoverable undo state.'
Add-Rule '1601eq-change-003' 'blur/change' $null 'Amended Return No is selected.' @('frm1601EQ:optAmend:N','frm1601EQ:txtTax22') $null @('official-hta-runtime#L311-L312') @('runtime-dom') 'verified-correct' 'Item 22 is disabled, reset to 0.00, and downstream totals are recomputed.' 'Apply the same dependency and preserve the prior value only in reversible editor state, not submitted data.'
Add-Rule '1601eq-change-004' 'blur/change' $null 'Any Taxes Withheld changes from Yes to No after ATCs exist and the user confirms.' @('frm1601EQ:optWithheld:Y','frm1601EQ:optWithheld:N') 'You are about to change the value . Doing this will clear all \n computation fields Do you wish to proceed?' @('official-hta-runtime#changeTaxWithheldNO:L3449-L3483') @('source') 'official-bug-compatible' 'Confirmation clears Items 19-30 and all ATC rows; cancellation restores Yes.' 'Use corrected message text and a reversible confirmation.'
Add-Rule '1601eq-change-005' 'blur/change' $null 'Item 30 changes sign.' @('frm1601EQ:txtTax30','frm1601EQ:ifRefund','frm1601EQ:ifIssueCert','frm1601EQ:ifCarriedOver') $null @('official-hta-runtime#computeOfTotalAmtDue:L3081-L3096') @('source') 'verified-correct' 'Negative Item 30 enables the three disposition choices; zero or positive clears and disables all three.' 'Apply the same state rule.'
Add-Rule '1601eq-change-006' 'blur/change' $null 'One Item 30 over-remittance disposition is checked.' @('frm1601EQ:ifRefund','frm1601EQ:ifIssueCert','frm1601EQ:ifCarriedOver') $null @('official-hta-runtime#checkRefund:L3116-L3121','official-hta-runtime#checkIssueCert:L3124-L3129','official-hta-runtime#checkCarriedOver:L3132-L3137') @('source') 'verified-correct' 'Checking one choice clears the other two.' 'Model as a single enum rather than three independent booleans while preserving XML compatibility.'
Add-Rule '1601eq-change-007' 'blur/change' $null 'Item 11 category filters the package ATC catalog.' @('frm1601EQ:optCategory:P','frm1601EQ:optCategory:G','AtcCode1') $null @('official-hta-runtime#getWithholdingAgentATC:L2643-L2662','official-hta-runtime#changedrpATCList:L2759-L2782','fixtures/atc-catalog-v796.json') @('source','runtime-binary') 'official-bug-compatible' 'Private renders 111 ordered slots and Government renders 96; four malformed categoryless catalog records are loaded but unreachable.' 'Keep the malformed records in provenance data, exclude them from selectable choices, and validate the catalog during ingestion.'

Add-Rule '1601eq-validate-001' 'validate' 1 'Item 1 is blank.' @('frm1601EQ:txtYear') 'Please enter a valid year on Item 1.' @('official-hta-runtime#validateForm:L3141-L3146') @('source') 'verified-correct' 'Stops, focuses Item 1, and returns false.' 'Require a four-digit year.'
Add-Rule '1601eq-validate-002' 'validate' 2 'Item 1 is greater than the current calendar year.' @('frm1601EQ:txtYear') 'Invalid entry on Item 1. Entry should not be a future Date.' @('official-hta-runtime#validateForm:L3147-L3151') @('source') 'verified-correct' 'Resets Item 1 to the current year, focuses it, and stops.' 'Reject without silently mutating the user value.'
Add-Rule '1601eq-validate-003' 'validate' 3 'Item 1 is less than 2018.' @('frm1601EQ:txtYear') 'Invalid entry on Item 1. Entry should not be a previous year from 2018.' @('official-hta-runtime#validateForm:L3152-L3156') @('source') 'verified-correct' 'Clears Item 1, focuses it, and stops.' 'Enforce the revision applicability boundary explicitly.'
Add-Rule '1601eq-validate-004' 'validate' 4 'Q1 of the current year is selected before April.' @('frm1601EQ:txtYear','frm1601EQ:optQuarter:1') 'Unable to select first Quarter due to the current date. Payment should be made after the Quarter' @('official-hta-runtime#validateForm:L3161-L3173') @('source') 'verified-correct' 'Clears Q1 and stops; a prior-year Q1 is accepted.' 'Use a filing-period calendar service and preserve selection on error.'
Add-Rule '1601eq-validate-005' 'validate' 5 'Q2 of the current year is selected before July.' @('frm1601EQ:txtYear','frm1601EQ:optQuarter:2') 'Unable to select second Quarter due to the current date. Payment should be made after the Quarter' @('official-hta-runtime#validateForm:L3174-L3185') @('source') 'verified-correct' 'Clears Q2 and stops; a prior-year Q2 is accepted.' 'Use a filing-period calendar service and preserve selection on error.'
Add-Rule '1601eq-validate-006' 'validate' 6 'Q3 of the current year is selected before October.' @('frm1601EQ:txtYear','frm1601EQ:optQuarter:3') 'Unable to select third Quarter due to the current date. Payment should be made after the Quarter' @('official-hta-runtime#validateForm:L3186-L3197') @('source') 'verified-correct' 'Clears Q3 and stops; a prior-year Q3 is accepted.' 'Use a filing-period calendar service and preserve selection on error.'
Add-Rule '1601eq-validate-007' 'validate' 7 'Q4 of the current year is selected.' @('frm1601EQ:txtYear','frm1601EQ:optQuarter:4') 'Unable to select fourth Quarter due to the current date. Payment should be made after the Quarter' @('official-hta-runtime#validateForm:L3198-L3205') @('source') 'verified-correct' 'Always clears current-year Q4 and stops; only prior-year Q4 is accepted.' 'Make the end-of-quarter eligibility rule explicit and timezone-stable.'
Add-Rule '1601eq-validate-008' 'validate' 8 'No quarter radio is selected.' @('frm1601EQ:optQuarter:1','frm1601EQ:optQuarter:2','frm1601EQ:optQuarter:3','frm1601EQ:optQuarter:4') 'Please select Quarter on Item 2' @('official-hta-runtime#validateForm:L3206-L3209') @('source') 'verified-correct' 'Stops at Item 2.' 'Require exactly one quarter.'
Add-Rule '1601eq-validate-009' 'validate' 9 'Neither Item 4 radio is selected.' @('frm1601EQ:optWithheld:Y','frm1601EQ:optWithheld:N') 'Please select an option for Item 4.' @('official-hta-runtime#validateForm:L3211-L3214') @('source') 'verified-correct' 'Stops at Item 4.' 'Require exactly one choice.'
Add-Rule '1601eq-validate-010' 'validate' 10 'Neither Item 11 category radio is selected.' @('frm1601EQ:optCategory:P','frm1601EQ:optCategory:G') 'Please select an option for Item 11.' @('official-hta-runtime#validateForm:L3215-L3218') @('source') 'verified-correct' 'Stops at Item 11.' 'Require exactly one category.'
Add-Rule '1601eq-validate-011' 'validate' 11 'Any Item 6 TIN core segment or branch code is blank.' @('frm1601EQ:txtTIN1','frm1601EQ:txtTIN2','frm1601EQ:txtTIN3','frm1601EQ:txtBranchCode') 'Please enter a valid TIN number on Item 6.' @('official-hta-runtime#validateForm:L3220-L3226') @('source') 'incorrect-official-behavior' 'Only nonblankness is tested; partial core segments, a one-character branch, and no checksum validation can pass.' 'Require exactly 3-3-3 core digits, a valid branch representation, and the shared TIN checksum where applicable.'
Add-Rule '1601eq-validate-012' 'validate' 12 'Item 7 select has selectedIndex 0.' @('frm1601EQ:txtRDOCode') 'Please enter a valid RDO Code on Item 7.' @('official-hta-runtime#validateForm:L3227-L3230') @('source') 'verified-correct' 'Stops when the placeholder RDO is selected.' 'Require a catalog-backed RDO code.'
Add-Rule '1601eq-validate-013' 'validate' 13 'Item 8 name is blank.' @('frm1601EQ:txtTaxpayerName') 'Please enter a valid Taxpayer Name on Item 8.' @('official-hta-runtime#validateForm:L3231-L3234') @('source') 'verified-correct' 'Stops on blank name.' 'Require a nonblank trimmed withholding-agent name.'
Add-Rule '1601eq-validate-014' 'validate' 14 'Item 10 telephone is blank.' @('frm1601EQ:txtTelNum') 'Please enter a valid Telephone Number on Item 10.' @('official-hta-runtime#validateForm:L3235-L3238') @('source') 'ambiguous' 'Requires a telephone number but validates no length or format beyond keypress filtering.' 'Confirm the legal/guide requirement; if required, validate a complete contact number rather than nonblankness.'
Add-Rule '1601eq-validate-015' 'validate' 15 'Item 9 address is blank.' @('frm1601EQ:txtAddress') "Please enter Taxpayer's Registered Address on Item 9." @('official-hta-runtime#validateForm:L3239-L3242') @('source') 'verified-correct' 'Checks only the first address control, although save concatenates two controls.' 'Validate the combined registered address and preserve line boundaries explicitly.'
Add-Rule '1601eq-validate-016' 'validate' 16 'Item 9A ZIP is blank.' @('frm1601EQ:txtZipCode') "Please enter Taxpayer's Zip Code on Item 9A." @('official-hta-runtime#validateForm:L3243-L3246') @('source') 'ambiguous' 'Requires a digit-only ZIP but performs no complete-value validation.' 'Confirm requiredness and validate an allowed Philippine postal-code representation.'
Add-Rule '1601eq-validate-017' 'validate' 17 'Item 12 email is blank.' @('txtEmail') 'Please enter valid Email Address on Item 12.' @('official-hta-runtime#validateForm:L3247-L3250') @('source') 'incorrect-official-behavior' 'Any nonblank string up to 20 characters passes; no email syntax check is called.' 'Validate a syntactically valid email and allow the official published maximum if it exceeds this UI limit.'
Add-Rule '1601eq-validate-018' 'validate' 18 'Item 4 is Yes and the first ATC row is blank.' @('frm1601EQ:optWithheld:Y','frm1601EQ:txtAtcCd1') 'Please fill up Part II Computation of Tax if item 4 is set to Yes.' @('official-hta-runtime#validateForm:L3251-L3256') @('source') 'verified-correct' 'Shows the ATC modal and returns without an explicit false value.' 'Require at least one selected ATC and return a typed validation failure.'
Add-Rule '1601eq-validate-019' 'validate' 19 'For any selected ATC row, Tax Base is blank or compares equal to 0.00.' @('frm1601EQ:txtAtcCd1','frm1601EQ:txtTaxBase1') 'Please enter a valid value for tax base for {ATC_CODE}.' @('official-hta-runtime#validateForm:L3257-L3267') @('source') 'verified-correct' 'Scans rows in display order and stops at the first blank/zero tax base.' 'Require a positive decimal tax base for each selected ATC and identify the row/code.'
Add-Rule '1601eq-validate-020' 'validate' 20 'Item 30 is negative and no over-remittance disposition is selected.' @('frm1601EQ:txtTax30','frm1601EQ:ifRefund','frm1601EQ:ifIssueCert','frm1601EQ:ifCarriedOver') 'Please select an Overpayment option in Part II Item 30.' @('official-hta-runtime#validateForm:L3271-L3277') @('source') 'verified-correct' 'Stops when no disposition is selected.' 'Require exactly one disposition for a negative amount.'
Add-Rule '1601eq-validate-021' 'validate' 21 'All earlier Validate checks pass.' @('frm1601EQ:cmdValidate') 'Validation successful. Click on Edit if you wish to modify your entries.' @('official-hta-runtime#validateForm:L3279-L3287') @('source') 'verified-correct' 'Stores Part II table size, disables editable controls, enables Edit/upload/final-copy paths, and shows success.' 'Use an explicit validated state invalidated by any model change.'

Add-Rule '1601eq-save-001' 'save' 1 'Any Item 6 TIN core segment or branch code is blank.' @('frm1601EQ:txtTIN1','frm1601EQ:txtTIN2','frm1601EQ:txtTIN3','frm1601EQ:txtBranchCode') 'Please enter a valid TIN number on Item 6.' @('official-hta-runtime#initialValidateBeforeSave:L3485-L3490') @('source') 'incorrect-official-behavior' 'Save preflight checks only nonblankness and permits partial/invalid TIN values.' 'Use the same complete TIN validation for Save and Validate, or explicitly allow drafts without claiming validity.'
Add-Rule '1601eq-save-002' 'save' 2 'Item 7 value is 000.' @('frm1601EQ:txtRDOCode') 'Please enter a valid RDO Code on Item 7.' @('official-hta-runtime#initialValidateBeforeSave:L3491-L3494') @('source') 'verified-correct' 'Save stops on the RDO placeholder.' 'Require a catalog-backed RDO for non-draft saves.'
Add-Rule '1601eq-save-003' 'save' 3 'Item 8 name is blank.' @('frm1601EQ:txtTaxpayerName') "Please enter a valid Withholding Agent's Name on Item 8." @('official-hta-runtime#initialValidateBeforeSave:L3495-L3500') @('source') 'verified-correct' 'Save stops with wording different from Validate.' 'Use one consistent field label and message.'
Add-Rule '1601eq-save-004' 'save' 4 'TIN, RDO, and name pass Save preflight even if every other Validate rule fails.' @('frm1601EQ:txtYear','frm1601EQ:optQuarter:1','frm1601EQ:optWithheld:Y','txtEmail') $null @('official-hta-runtime#initialValidateBeforeSave:L3485-L3501','official-hta-runtime#saveXML:L2166-L2170') @('source') 'official-bug-compatible' 'Draft Save does not invoke validateForm and may persist otherwise invalid/incomplete return data.' 'Support explicit drafts, clearly label them unvalidated, and require full validation for final-copy/submission.'
Add-Rule '1601eq-save-005' 'save' 5 'The two address controls are serialized and reopened.' @('frm1601EQ:txtAddress') $null @('official-hta-runtime#saveXML:L2306-L2311','official-hta-runtime#loadData:L1724-L1748') @('source','xml') 'incorrect-official-behavior' 'Both controls are concatenated into one escaped XML value without a delimiter; reopen splits the escaped byte-like string at position 127, which can move the line boundary or split a percent escape.' 'Serialize address lines losslessly as separate modeled values while retaining the official combined XML projection.'
Add-Rule '1601eq-save-006' 'save' 6 'A saved return is reopened.' @('txtEmail') $null @('official-hta-runtime#loadDataATCRow:L1787-L1828','xml-editable-v1#field:txtEmail') @('source','xml') 'incorrect-official-behavior' 'The saved txtEmail is read, then overwritten with globalEmail from the active profile.' 'Preserve the return email on reopen and surface any profile mismatch as an explicit user choice.'
Add-Rule '1601eq-save-007' 'save' 7 'A non-amended filename family already contains an amended V-version.' @('frm1601EQ:optAmend:N') "If your intention is to make an amended return, kindly tick Amended Return to 'Yes' before hitting 'Save' or 'Final Copy' or 'Submit'." @('official-hta-runtime#saveXML:L2181-L2203') @('source') 'verified-correct' 'Save is refused to avoid overwriting/creating a non-amended return after amended versions exist.' 'Preserve explicit versioning and prevent ambiguous overwrite.'

Add-Rule '1601eq-final-001' 'final-copy' 1 'Submit / Final Copy is invoked after successful Validate and no prior final-state resend branch applies.' @('frm1601EQ:btnFinalCopy','txtFinalFlag') 'Please ensure that you have INTERNET access and a VALID email address is indicated in your tax return.\n\nAre you sure you want to submit?' @('official-hta-runtime#openAlertEmail:L4096-L4167') @('source') 'official-bug-compatible' 'The button is a submission-first workflow; it does not offer a separate ordinary local final-copy action before checking Internet.' 'Separate local final-copy generation from optional online submission.'
Add-Rule '1601eq-final-002' 'final-copy' 2 'The user confirms final-copy/submission but checkNetConnection reports no Internet.' @('txtFinalFlag') 'The system detected that you have no internet connection.\nPlease contact your internet service provider.' @('official-hta-runtime#openAlertEmail:L4153-L4163','official-hta-runtime#saveEncryptedProfile:L1913-L2000') @('source') 'official-bug-compatible' 'Sets txtFinalFlag=3, invokes saveEncryptedProfile/saveXML(true), and creates an encrypted IAF_RDO_Copy artifact despite reporting no connection.' 'Allow deterministic offline final copy directly and document state transitions without relying on a network probe.'
Add-Rule '1601eq-final-003' 'final-copy' 3 'A read-only final copy with txtFinalFlag other than 2 is saved again.' @('txtFinalFlag','driveSelectTPExport') 'You will no longer be allowed to modify since this is already the final copy.\nDo you want to save this in USB flash drive or CD-RW instead?' @('official-hta-runtime#saveXML:L2108-L2164') @('source') 'verified-correct' 'Confirmation generates and encrypts an IAF_RDO_Copy artifact and opens export selection; cancellation stops.' 'Provide an explicit export-copy action with the same immutability semantics.'
Add-Rule '1601eq-final-004' 'final-copy' 4 'A final non-amended return already exists and the current attempt is not a special resend state.' @('frm1601EQ:optAmend:N','txtFinalFlag') "If your intention is to make an amended return, kindly tick Amended Return to 'Yes' before hitting 'Save' or 'Final Copy' or 'Submit'." @('official-hta-runtime#openAlertEmail:L4145-L4152','official-hta-runtime#saveXML:L2238-L2243') @('source') 'verified-correct' 'Final-copy/submission is refused.' 'Preserve immutable versioning and require an explicit amended return.'

Add-Rule '1601eq-submit-001' 'submit' 1 'Online enrollment/credential confirmation proceeds.' @('txtEnroll','ebirOnlineUsername','ebirOnlineSecret','ebirOnlineConfirmUsername') $null @('official-hta-runtime#sendEmail:L4284-L4294') @('source') 'unverified' 'May set txtEnroll=Y, copies the password into serialized ebirOnlineSecret, then generates an encrypted final copy before transport.' 'Never serialize plaintext credentials into return XML; use platform credential storage.' 'high' @('The encrypted-output credential exposure has not been decrypted and inspected for this form package.')
Add-Rule '1601eq-submit-002' 'submit' 2 'RenameAndSendFile returns 0.' @('txtFinalFlag') 'Submit Successful. Subject to validation by BIR. \n\n A notification will be sent to your email ({EMAIL}). Please print or save the email as an evidence of efiled return.' @('official-hta-runtime#sendEmail:L4355-L4366') @('source') 'unverified' 'Sets txtFinalFlag=1, updates the save file, shows success, and offers payment options.' 'Only mark submitted after an authenticated server acknowledgement; store immutable receipt evidence.' 'high' @('Online submission was intentionally not performed.')
Add-Rule '1601eq-submit-003' 'submit' 3 'Transport returns nonzero or throws.' @('txtFinalFlag') 'Your Tax Return was not submitted online due to any of the \n following reasons that may interrupt the submission process: \n - No internet connection \n - Slow internet connection \n - Overly restrictive firewall' @('official-hta-runtime#sendEmail:L4367-L4375') @('source') 'unverified' 'Sets txtFinalFlag=2 and updates the save file for resend.' 'Record the actual transport error safely, retain a retryable state, and avoid claiming one of several guessed causes.' 'high' @('Online submission was intentionally not performed.')

$document = [ordered]@{
    '$schema'='../../schema/validations.schema.json'; schema_version='1.0.0'; form_id=$form; revision=$revision;
    first_error_behavior='Validate and Save preflight stop at the first ordered failure. Input and change handlers run independently. Final-copy/submission has its own ordered guards.';
    rules=$rules
}
$directory = Split-Path -Parent $OutputPath
[IO.Directory]::CreateDirectory($directory) | Out-Null
[IO.File]::WriteAllText($OutputPath, ($document | ConvertTo-Json -Depth 20) + "`n", [Text.UTF8Encoding]::new($false))
Write-Output ([ordered]@{rule_count=$rules.Count;output=$OutputPath} | ConvertTo-Json)
