param([Parameter(Mandatory=$true)][string]$HtaPath,[Parameter(Mandatory=$true)][string]$XmlPath,[Parameter(Mandatory=$true)][string]$FieldsOutputPath,[Parameter(Mandatory=$true)][string]$ControlsOutputPath)
$ErrorActionPreference='Stop';$hta=[IO.File]::ReadAllText($HtaPath);$xml=[IO.File]::ReadAllText($XmlPath)
function Attr($tag,$name){$m=[regex]::Match($tag,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($name)));if($m.Success){$m.Groups[2].Value}elseif([regex]::IsMatch($tag,"(?i)\b$([regex]::Escape($name))\b")){'true'}else{$null}}
$scripts=@([regex]::Matches($hta,'<script\b.*?</script>','IgnoreCase,Singleline'));$controls=@();$ordinal=0
foreach($m in [regex]::Matches($hta,'<(input|select|textarea|button)\b[^>]*>','IgnoreCase,Singleline')){$inside=$false;foreach($s in $scripts){if($m.Index-ge$s.Index-and$m.Index-lt($s.Index+$s.Length)){$inside=$true;break}};if($inside){continue};$ordinal++;$tag=$m.Value;$element=$m.Groups[1].Value.ToLowerInvariant();$type=if($element-eq'input'){Attr $tag 'type'}else{$element};if(-not$type){$type='text'};$controls += [ordered]@{ordinal=$ordinal;id=Attr $tag 'id';name=Attr $tag 'name';element=$element;control_kind=$type.ToLowerInvariant();source_line=1+([regex]::Matches($hta.Substring(0,$m.Index),"`n")).Count;value=Attr $tag 'value';maxlength=Attr $tag 'maxlength';disabled=[bool](Attr $tag 'disabled');readonly=[bool](Attr $tag 'readonly');serializable_by_save_loop=$type.ToLowerInvariant()-notin@('button','hidden','undefined','submit')}}
$families=@(
 [ordered]@{id_pattern='frm1600PT:txtPg1I6RDO';control_kind='select-one';minimum_instances=1;maximum_instances=1;existence='Injected from the runtime RDO catalog.';source_refs=@('official-hta-runtime#getRdo:L4687-L4701')},
 [ordered]@{id_pattern='AtcCode{1..N}';control_kind='checkbox';minimum_instances=0;maximum_instances=31;existence='Government category has the maximum 31 slots; Private has 6.';source_refs=@('official-hta-runtime#changedrpATCList:L5072-L5100','fixtures/atc-catalog-v796.json')},
 [ordered]@{id_pattern='frm1600PT:txtAtcCd{1..N}';control_kind='text';minimum_instances=5;maximum_instances=31;existence='Part II rows 1-5 always exist; rows 6-N are selected-ATC rows.';source_refs=@('official-hta-runtime#populateAtcPart2:L3793-L3807','official-hta-runtime#getATCCode:L3823-L3965')},
 [ordered]@{id_pattern='frm1600PT:txtPg1P2TaxBase{1..N}';control_kind='text';minimum_instances=5;maximum_instances=31;existence='Parallel selected-ATC tax base.';source_refs=@('official-hta-runtime#getATCCode:L3823-L3965')},
 [ordered]@{id_pattern='frm1600PT:txtPg1P2TaxRate{1..N}';control_kind='text';minimum_instances=5;maximum_instances=31;existence='Parallel catalog tax rate.';source_refs=@('official-hta-runtime#getATCCode:L3823-L3965')},
 [ordered]@{id_pattern='frm1600PT:txtPg1P2TaxWithheld{1..N}';control_kind='text';minimum_instances=5;maximum_instances=31;existence='Parallel computed tax withheld.';source_refs=@('official-hta-runtime#getATCCode:L3823-L3965')}
)
$controlDoc=[ordered]@{schema_version='1.0.0';form_id='1600pt-v2018';package_version='7.9.6.0';official_hta_sha256=(Get-FileHash -LiteralPath $HtaPath -Algorithm SHA256).Hash.ToLowerInvariant();static_control_count=$controls.Count;static_controls_with_id_count=@($controls|Where-Object{$_.id}).Count;static_controls_without_id_count=@($controls|Where-Object{-not$_.id}).Count;static_controls=$controls;runtime_generated_control_families=$families;maximum_runtime_control_instances=$controls.Count+1+31+(4*31);notes=@('Maximum union uses Government category and all 31 ATCs; it is not one observed save.')}
$entries=[Collections.Generic.List[object]]::new();foreach($m in [regex]::Matches($xml,'<div>(?<key>.*?)=(?<value>.*?)\k<key>=</div>','Singleline')){$entries.Add([ordered]@{key=$m.Groups['key'].Value;value=$m.Groups['value'].Value;source='xml'})}
foreach($n in 7..31){$entries.Add([ordered]@{key="AtcCode$n";value='false';source='union'})};foreach($n in 6..31){foreach($prefix in @('txtAtcCd','txtPg1P2TaxBase','txtPg1P2TaxRate','txtPg1P2TaxWithheld')){$key="frm1600PT:$prefix$n";if(-not($entries.key-contains$key)){$value=if($prefix-match'Tax(Base|Rate|Withheld)'){'0.00'}else{''};$entries.Add([ordered]@{key=$key;value=$value;source='union'})}}}
$required=@('frm1600PT:txtPg1I1Month','frm1600PT:txtPg1I1Year','frm1600PT:txtPg1I6RDO','frm1600PT:rdoPg1Pt1I6RDO','frm1600PT:txtPg1Pt1I7WithholdingAgentsName','frm1600PT:txtPg1Pt1I8RegisteredAddress','frm1600PT:txPg1I8ZipCode','frm1600PT:txtPg1Pt1I9ContactNumber','frm1600PT:txtPg1Pt1I11Email')
function Item($k){if($k-match'I1(Month|Year)$'){return '1'};if($k-match'I2Amended'){return '2'};if($k-match'I3TaxWithheld'){return '3'};if($k-match'I4NoOfSheets'){return '4'};if($k-match'TIN[1-4]$|BranchMask'){return '5'};if($k-match'I6RDO'){return '6'};if($k-match'I7Withholding'){return '7'};if($k-match'I8Registered|I8Zip'){return '8'};if($k-match'I9Contact'){return '9'};if($k-match'I10Category'){return '10'};if($k-match'I11Email'){return '11'};if($k-match'I12TaxRelief'){return '12'};if($k-match'I(1[8-9]|2[0-7])'){return $Matches[1]};$null}
function Label($k){$map=@{'frm1600PT:txtPg1I1Month'='Filing month';'frm1600PT:txtPg1I1Year'='Filing two-digit year';'frm1600PT:txtPg1I6RDO'='Visible RDO code';'frm1600PT:rdoPg1Pt1I6RDO'='Legacy mirrored RDO code';'frm1600PT:txtPg1Pt1I7WithholdingAgentsName'='Withholding agent name';'frm1600PT:txtPg1Pt1I8RegisteredAddress'='Registered address';'frm1600PT:txPg1I8ZipCode'='ZIP code';'frm1600PT:txtPg1Pt1I9ContactNumber'='Contact number';'frm1600PT:txtPg1Pt1I11Email'='Email address'};if($map.ContainsKey($k)){return $map[$k]};if($k-match'AtcCode(\d+)$'){return "ATC selector slot $($Matches[1])"};if($k-match'txtAtcCd(\d+)$'){return "Part II row $($Matches[1]) ATC code"};if($k-match'txtPg1P2Tax(Base|Rate|Withheld)(\d+)$'){return "Part II row $($Matches[2]) tax $($Matches[1].ToLower())"};if($k-match'Pg2Sc1(.+?)([1-5])$'){return "Schedule 1 row $($Matches[2]) $($Matches[1])"};$k-replace'^frm1600PT:',''}
$fields=@();foreach($e in $entries){$k=$e.key;$bool=$e.value-in@('true','false')-or$k-match'^(AtcCode)|:(rdoPg1I2|rdoPg1I3|rdoPg1I10|rdoPg1I12)';$money=$k-match'(TaxBase|TaxRate|TaxWithheld|AmtOfIncPmt|AmtOfTxWthhld|TotTx|I1[89]|I2[0-7]|txtAmount)';$computed=$k-match'(TaxWithheld\d+|I18Tot|I21Tot|I22Tax|I26Tot|I27Tot|AmtOfTxWthhld|TotTxWthhld)';$hidden=$k-match'^(hPartIITableSize|driveSelectTPExport|txtFinalFlag|txtEnroll|ebirOnline)|:txt(Current|Max)Page$';$norm=@();if($money){$norm+='legacy currency formatting'};$refs=if($e.source-eq'union'){@('official-hta-runtime#getATCCode:L3823-L3965','fixtures/atc-catalog-v796.json')}else{@('xml-editable-v1','official-hta-runtime#frmMain')};$notes=@();if($e.source-eq'union'){$notes+='Exists only in maximum ATC union.'}
 $fields += [ordered]@{field_key=$k;serialized_key=$k;serialized_occurrence=1;label=Label $k;page=if($hidden){$null}elseif($k-match'Pg2Sc1|txtPg2'){2}else{1};item_number=Item $k;control_kind=if($bool){'checkbox/radio'}elseif($k-match'(RDO|Region|Province|City)'){'select'}elseif($hidden){'hidden'}else{'text'};storage_type='string';logical_type=if($bool){'boolean'}elseif($money){'decimal'}else{'string'};required=if($hidden){'hidden'}elseif($computed){'computed'}elseif($required-contains$k){'required'}elseif($k-match'Pg2Sc1|TaxRelief|txtAtcCd|TaxBase|TaxRate|TaxWithheld'){'conditional'}else{'optional'};required_when=if($k-match'Pg2Sc1'){'Schedule 1 row contains any data.'}elseif($k-match'(txtAtcCd|TaxBase|TaxRate|TaxWithheld)'){'Any Taxes Withheld is Yes and corresponding ATC is selected.'}else{$null};enabled_when=$null;visible_when=$null;default_value=$e.value;empty_representation='';constraints=@{};enum_values=@();normalization=$norm;computed=[bool]$computed;calculation_id=$null;source_refs=@($refs);confidence='high';notes=$notes}}
$keys=$fields.field_key;$hasher=[Security.Cryptography.SHA256]::Create();$sha=(-join($hasher.ComputeHash([Text.Encoding]::UTF8.GetBytes(($keys-join"`n")))|ForEach-Object{$_.ToString('x2')}));$hasher.Dispose();$fieldDoc=[ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id='1600pt-v2018';revision='2018-01-01';field_count=$fields.Count;runtime_serializable_element_count=$fields.Count;inventory_sha256=$sha;fields=$fields}
[IO.Directory]::CreateDirectory((Split-Path -Parent $FieldsOutputPath))|Out-Null;[IO.Directory]::CreateDirectory((Split-Path -Parent $ControlsOutputPath))|Out-Null;[IO.File]::WriteAllText($FieldsOutputPath,($fieldDoc|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ControlsOutputPath,($controlDoc|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false));[ordered]@{fields=$fields.Count;unique=@($keys|Sort-Object -Unique).Count;sha256=$sha;static_controls=$controls.Count;maximum_controls=$controlDoc.maximum_runtime_control_instances}|ConvertTo-Json
