param(
 [Parameter(Mandatory=$true)][string]$HtaPath,
 [Parameter(Mandatory=$true)][string]$XmlPath,
 [Parameter(Mandatory=$true)][string]$FieldsOutputPath,
 [Parameter(Mandatory=$true)][string]$ControlsOutputPath
)
$ErrorActionPreference='Stop';$hta=[IO.File]::ReadAllText($HtaPath);$xml=[IO.File]::ReadAllText($XmlPath)
function Attr($tag,$name){$m=[regex]::Match($tag,('(?i)\b{0}\s*=\s*([''"])(.*?)\1'-f[regex]::Escape($name)));if($m.Success){$m.Groups[2].Value}elseif([regex]::IsMatch($tag,"(?i)\b$([regex]::Escape($name))\b")){'true'}else{$null}}
$scripts=@([regex]::Matches($hta,'<script\b.*?</script>','IgnoreCase,Singleline'));$controls=@();$ordinal=0
foreach($m in [regex]::Matches($hta,'<(input|select|textarea|button)\b[^>]*>','IgnoreCase,Singleline')){
 $inside=$false;foreach($s in $scripts){if($m.Index-ge$s.Index-and$m.Index-lt($s.Index+$s.Length)){$inside=$true;break}};if($inside){continue}
 $ordinal++;$tag=$m.Value;$element=$m.Groups[1].Value.ToLowerInvariant();$type=if($element-eq'input'){Attr $tag 'type'}else{$element};if(-not$type){$type='text'}
 $controls += [ordered]@{ordinal=$ordinal;id=Attr $tag 'id';name=Attr $tag 'name';element=$element;control_kind=$type.ToLowerInvariant();source_line=1+([regex]::Matches($hta.Substring(0,$m.Index),"`n")).Count;value=Attr $tag 'value';maxlength=Attr $tag 'maxlength';disabled=[bool](Attr $tag 'disabled');readonly=[bool](Attr $tag 'readonly');serializable_by_save_loop=$type.ToLowerInvariant()-notin@('button','hidden','undefined','submit')}
}
$controlDoc=[ordered]@{schema_version='1.0.0';form_id='1603q-v2018';package_version='7.9.6.0';official_hta_sha256=(Get-FileHash -LiteralPath $HtaPath -Algorithm SHA256).Hash.ToLowerInvariant();static_control_count=$controls.Count;static_controls_with_id_count=@($controls|Where-Object{$_.id}).Count;static_controls_without_id_count=@($controls|Where-Object{-not$_.id}).Count;static_controls=$controls;runtime_generated_control_families=@([ordered]@{id_pattern='frm1603Q:rdoCode';control_kind='select-one';minimum_instances=1;maximum_instances=1;existence='Injected by getRdo from the runtime RDO catalog.';source_refs=@('official-hta-runtime#getRdo:L3092-L3105')});maximum_runtime_control_instances=$controls.Count+1;notes=@('No repeatable dynamic data rows exist; the RDO select replaces its placeholder container at runtime.')}
$entries=@();foreach($m in [regex]::Matches($xml,'<div>(?<key>.*?)=(?<value>.*?)\k<key>=</div>','Singleline')){$entries += [ordered]@{key=$m.Groups['key'].Value;value=$m.Groups['value'].Value}}
$required=@('frm1603Q:txtYear','frm1603Q:txtTIN1','frm1603Q:txtTIN2','frm1603Q:txtTIN3','frm1603Q:txtBranchCode','frm1603Q:rdoCode','frm1603Q:txtTaxpayerName','frm1603Q:txtAddress','frm1603Q:txtZipCode','frm1603Q:txtTelNum')
function Item($k){if($k-match'txtYear'){return '1'};if($k-match'optQuarter'){return '2'};if($k-match'AmendedRtn'){return '3'};if($k-match'TaxWithheld'){return '4'};if($k-match'txtSheets'){return '5'};if($k-match'txtTIN|txtBranchCode'){return '6'};if($k-match'rdoCode'){return '7'};if($k-match'txtTaxpayerName'){return '8'};if($k-match'txtAddress|txtZipCode'){return '9'};if($k-match'txtTelNum'){return '10'};if($k-match'CatAgent'){return '11'};if($k-match'SpecialTax|selTreaty'){return '12'};if($k-match'txtTax(\d+)$'){return $Matches[1]};$null}
function Label($k){$map=@{'frm1603Q:txtYear'='Filing year';'frm1603Q:rdoCode'='RDO code';'frm1603Q:txtTaxpayerName'='Withholding agent name';'frm1603Q:txtAddress'='Registered address';'frm1603Q:txtZipCode'='ZIP code';'frm1603Q:txtTelNum'='Telephone number';'txtEmail'='Email address';'frm1603Q:selTreaty'='Treaty selection'};if($map.ContainsKey($k)){return $map[$k]};if($k-match'txtTIN([123])$'){return "TIN segment $($Matches[1])"};if($k-match'optQuarter([1-4])$'){return "Quarter $($Matches[1]) selection"};if($k-match'Sched1:(.+)'){return "Schedule 1 $($Matches[1])"};$k-replace'^frm1603Q:',''}
$fields=@();foreach($e in $entries){$k=$e.key;$bool=$e.value-in@('true','false')-or$k-match':(optQuarter|AmendedRtn|TaxWithheld|CatAgent|SpecialTax)';$money=$k-match'(txtTax\d+|txtAmount|Sched1:txt(Value|TaxBase|TaxRate|TaxWithheld|TotalTax))';$computed=$k-match'(txtTax1[478]|txtTax2[23]|Sched1:txt(TaxBase|TaxWithheld|TotalTax))';$hidden=$k-match'^(txtFinalFlag|txtEnroll|ebirOnline|driveSelectTPExport)|:txt(Current|Max)Page$';$norm=@();if($money){$norm+= 'legacy currency formatting'}
 $fields += [ordered]@{field_key=$k;serialized_key=$k;serialized_occurrence=1;label=Label $k;page=if($hidden){$null}elseif($k-match'Pg2|Sched1'){2}else{1};item_number=Item $k;control_kind=if($bool){'checkbox/radio'}elseif($k-match'(rdoCode|selTreaty)'){'select'}elseif($hidden){'hidden'}else{'text'};storage_type='string';logical_type=if($bool){'boolean'}elseif($money){'decimal'}else{'string'};required=if($hidden){'hidden'}elseif($computed){'computed'}elseif($required-contains$k){'required'}elseif($k-match'Sched1|SpecialTax|selTreaty'){'conditional'}else{'optional'};required_when=if($k-match'Sched1'){'Item 4 Any Taxes Withheld is Yes.'}else{$null};enabled_when=$null;visible_when=$null;default_value=$e.value;empty_representation='';constraints=if($k-match'txtTIN[123]$'){@{exact_length=3}}elseif($k-match'txtBranchCode$'){@{min_length=1;max_length=5}}else{@{}};enum_values=@();normalization=$norm;computed=[bool]$computed;calculation_id=$null;source_refs=@('xml-editable-v1','official-hta-runtime#frmMain');confidence='high';notes=@()}
}
$keys=$fields.field_key;$hasher=[Security.Cryptography.SHA256]::Create();$sha=(-join($hasher.ComputeHash([Text.Encoding]::UTF8.GetBytes(($keys-join"`n")))|ForEach-Object{$_.ToString('x2')}));$hasher.Dispose()
$fieldDoc=[ordered]@{'$schema'='../../schema/fields.schema.json';schema_version='1.0.0';form_id='1603q-v2018';revision='2018-01-01';field_count=$fields.Count;runtime_serializable_element_count=$fields.Count;inventory_sha256=$sha;fields=$fields}
[IO.Directory]::CreateDirectory((Split-Path -Parent $FieldsOutputPath))|Out-Null;[IO.Directory]::CreateDirectory((Split-Path -Parent $ControlsOutputPath))|Out-Null
[IO.File]::WriteAllText($FieldsOutputPath,($fieldDoc|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ControlsOutputPath,($controlDoc|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false))
[ordered]@{fields=$fields.Count;unique=@($keys|Sort-Object -Unique).Count;inventory_sha256=$sha;static_controls=$controls.Count;maximum_controls=$controlDoc.maximum_runtime_control_instances}|ConvertTo-Json
