[package]
name = "bir-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
urlencoding = { workspace = true }
chrono = { workspace = true }
aes = { workspace = true }
cbc = { workspace = true }
sha2 = { workspace = true }
flate2 = { workspace = true }
zeroize = { workspace = true }
aes-gcm = { workspace = true }
suppaftp = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
rss = { workspace = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
keyring = { workspace = true }
dotenvy = { workspace = true }
rand = "0.10.1"
hex = "0.4.3"
imap = "2.4.1"
mailparse = "0.16.1"
native-tls = "0.2.18"
data-encoding = "2.11.0"
open = "5.3.4"
directories = "6.0.0"

[dev-dependencies]
insta = "1"
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }
