//! Generate compile-time frozen HTML bundle includes for bir-print.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const SLUGS: &[&str] = &[
    "2551q-2018",
    "0619e-2018",
    "0619f-2018",
    "0605-1999",
    "1601c-2018",
    "1701q-2018",
    "2550q-2024",
    "1701-2018",
    "1702rt-2018c",
    "1702mx-2018c",
];

fn asset_names(html: &str) -> Vec<String> {
    let mut names = Vec::new();
    let needle = "../assets/";
    let mut rest = html;
    while let Some(at) = rest.find(needle) {
        let after = &rest[at + needle.len()..];
        let Some(end) = after.find('"') else {
            break;
        };
        let name = &after[..end];
        if name.ends_with(".png") && !names.iter().any(|existing| existing == name) {
            names.push(name.to_string());
        }
        rest = &after[end..];
    }
    names
}

fn rust_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let frozen = manifest.join("../../html-frozen");
    println!("cargo:rerun-if-changed={}", frozen.display());

    let mut out = String::from("// @generated by crates/bir-print/build.rs. Do not edit.\n");
    out.push_str("pub struct FrozenBundle {\n");
    out.push_str("    pub slug: &'static str,\n");
    out.push_str("    pub html: &'static str,\n");
    out.push_str("    pub css: &'static str,\n");
    out.push_str("    pub assets: &'static [(&'static str, &'static [u8])],\n");
    out.push_str("}\n\n");
    out.push_str("pub fn bundle(slug: &str) -> Option<FrozenBundle> {\n");
    out.push_str("    match slug {\n");

    for slug in SLUGS {
        let html_path = frozen.join(slug).join("index.html");
        let html = fs::read_to_string(&html_path).unwrap_or_else(|error| {
            panic!("missing {}: {error}", html_path.display());
        });
        let assets = asset_names(&html);
        out.push_str("        ");
        out.push_str(&rust_string(slug));
        out.push_str(" => Some(FrozenBundle {\n");
        out.push_str("            slug: ");
        out.push_str(&rust_string(slug));
        out.push_str(",\n");
        out.push_str(
            "            html: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../html-frozen/",
        );
        out.push_str(slug);
        out.push_str("/index.html\")),\n");
        out.push_str(
            "            css: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../html-frozen/",
        );
        out.push_str(slug);
        out.push_str("/form.css\")),\n");
        out.push_str("            assets: &[\n");
        for name in assets {
            let asset_path = frozen.join("assets").join(&name);
            if !asset_path.is_file() {
                panic!("missing asset {}", asset_path.display());
            }
            out.push_str("                (");
            out.push_str(&rust_string(&name));
            out.push_str(
                ", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../html-frozen/assets/",
            );
            out.push_str(&name);
            out.push_str("\"))),\n");
        }
        out.push_str("            ],\n");
        out.push_str("        }),\n");
    }

    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("frozen_bundles.rs");
    fs::write(dest, out).unwrap();
}
