#!/usr/bin/env python3
"""
Generate a formtype.json skeleton + SVG page shells from an official BIR PDF.

This is a dev-time calibration tool — it is NOT used at runtime.
The generated formtype.json is a draft that must be reviewed and calibrated
by a human before committing. The Rust runtime loads committed formtype.json
files via include_str!() and never invokes this script.

Install:
  python3 -m pip install --user pymupdf

Examples:
  # From a local PDF:
  python3 scripts/generate_formtype.py \\
    --input official.pdf \\
    --form-id 2551Qv2018

  # From the official BIR CDN URL:
  python3 scripts/generate_formtype.py \\
    --input "https://bir-cdn.bir.gov.ph/local/pdf/2551Q%20Jan%202018%20ENCS%20final%20rev%203_copy.pdf" \\
    --form-id 2551Qv2018

  # With rectangle detection for field candidates:
  python3 scripts/generate_formtype.py \\
    --input official.pdf \\
    --form-id 2551Qv2018 \\
    --detect-fields
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import urllib.request
from dataclasses import asdict, dataclass, field
from pathlib import Path

try:
    import fitz  # PyMuPDF
except ImportError:
    print("ERROR: PyMuPDF not installed. Run: python3 -m pip install --user pymupdf", file=sys.stderr)
    sys.exit(1)


FORMTYPES_DIR = Path(__file__).resolve().parent.parent / "formtypes"


@dataclass
class WidgetSpec:
    type: str  # "text" or "checkbox"
    width: float
    height: float
    max_length: int | None = None
    comb: bool | None = None
    font_size: float | None = None


@dataclass
class FieldCandidate:
    key: str
    kind: str  # "text", "cells", "checkbox", "amount"
    page: int
    x: float
    y: float
    cell_w: float | None = None
    optional: bool = False
    widget: WidgetSpec | None = None


@dataclass
class FormTypeSchema:
    form_id: str
    page_width: float
    page_height: float
    fields: list[FieldCandidate] = field(default_factory=list)


@dataclass
class MetadataSchema:
    form_id: str
    title: str
    official_source: str
    sha256: str
    page_width_pt: float
    page_height_pt: float
    page_count: int
    notes: str = "Generated by scripts/generate_formtype.py. Review before committing."


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate formtype.json + SVG pages from an official BIR PDF.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--input", required=True,
        help="Path or URL to the official BIR PDF file.",
    )
    parser.add_argument(
        "--form-id", required=True,
        help="Form type identifier (e.g. 2551Qv2018).",
    )
    parser.add_argument(
        "--title", default="",
        help="Human-readable form title (e.g. 'Quarterly Percentage Tax Return').",
    )
    parser.add_argument(
        "--detect-fields", action="store_true",
        help="Attempt to detect field rectangles from vector drawings in the PDF.",
    )
    parser.add_argument(
        "--overwrite", action="store_true",
        help="Overwrite existing formtype directory if it exists.",
    )
    return parser.parse_args()


def fetch_pdf(source: str, work_dir: Path) -> Path:
    """Download or copy the PDF to a local path."""
    target = work_dir / "source.pdf"
    if source.startswith(("http://", "https://")):
        print(f"  Downloading {source}...")
        urllib.request.urlretrieve(source, target)
    else:
        shutil.copyfile(source, target)
    return target


def compute_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def extract_svg_pages(pdf_path: Path, pages_dir: Path) -> tuple[int, float, float]:
    """Convert each page of the PDF to an SVG file.

    Returns (page_count, page_width_pt, page_height_pt).
    """
    doc = fitz.open(pdf_path)
    if len(doc) < 1:
        raise RuntimeError("PDF has no pages")

    width = doc[0].rect.width
    height = doc[0].rect.height

    for index, page in enumerate(doc):
        svg_content = page.get_svg_image(text_as_path=True)
        svg_file = pages_dir / f"page{index + 1}.svg"
        svg_file.write_text(svg_content)
        print(f"  Extracted page {index + 1} → {svg_file.name} ({len(svg_content):,} bytes)")

    return len(doc), width, height


def detect_field_rectangles(pdf_path: Path, page_width: float, page_height: float) -> list[FieldCandidate]:
    """Detect potential form field locations from vector rectangles in the PDF.

    This is a heuristic — it looks for small rectangles (likely text input boxes
    or checkboxes) drawn as vector paths. Results are draft candidates that must
    be reviewed and named manually.
    """
    doc = fitz.open(pdf_path)
    candidates: list[FieldCandidate] = []
    field_idx = 0

    for page_num, page in enumerate(doc, start=1):
        drawings = page.get_drawings()
        for drawing in drawings:
            rect = drawing.get("rect")
            if rect is None:
                continue

            x, y, x2, y2 = rect
            w = x2 - x
            h = y2 - y

            # Skip page-sized or very large rectangles (borders, backgrounds)
            if w > page_width * 0.8 or h > page_height * 0.5:
                continue
            # Skip very tiny rectangles (dots, decorations)
            if w < 5 or h < 5:
                continue
            # Skip very tall rectangles (section dividers, columns)
            if h > 30:
                continue

            # Classify by size
            if 8 <= w <= 16 and 8 <= h <= 16:
                # Likely a checkbox
                candidates.append(FieldCandidate(
                    key=f"_field_{field_idx:03d}",
                    kind="checkbox",
                    page=page_num,
                    x=round(x, 1),
                    y=round(y, 1),
                    optional=True,
                    widget=WidgetSpec(type="checkbox", width=round(w, 1), height=round(h, 1)),
                ))
            elif w >= 20:
                # Likely a text input box
                is_comb = w < 60  # Short boxes are likely comb-style cells
                candidates.append(FieldCandidate(
                    key=f"_field_{field_idx:03d}",
                    kind="cells" if is_comb else "text",
                    page=page_num,
                    x=round(x, 1),
                    y=round(y, 1),
                    cell_w=14.0 if is_comb else None,
                    widget=WidgetSpec(
                        type="text",
                        width=round(w, 1),
                        height=round(h, 1),
                        max_length=max(1, int(w / 14)) if is_comb else None,
                        comb=True if is_comb else None,
                        font_size=8.5,
                    ),
                ))
            field_idx += 1

    print(f"  Detected {len(candidates)} field candidates ({sum(1 for c in candidates if c.kind == 'checkbox')} checkboxes, {sum(1 for c in candidates if c.kind != 'checkbox')} text)")
    return candidates


def serialize_formtype(schema: FormTypeSchema) -> dict:
    """Convert to JSON-serializable dict, stripping None values."""
    result = {
        "form_id": schema.form_id,
        "page_width": schema.page_width,
        "page_height": schema.page_height,
        "fields": [],
    }
    for f in schema.fields:
        fd: dict = {
            "key": f.key,
            "kind": f.kind,
            "page": f.page,
            "x": f.x,
            "y": f.y,
        }
        if f.cell_w is not None:
            fd["cell_w"] = f.cell_w
        if f.optional:
            fd["optional"] = True
        if f.widget:
            wd: dict = {"type": f.widget.type, "width": f.widget.width, "height": f.widget.height}
            if f.widget.max_length is not None:
                wd["max_length"] = f.widget.max_length
            if f.widget.comb is not None:
                wd["comb"] = f.widget.comb
            if f.widget.font_size is not None:
                wd["font_size"] = f.widget.font_size
            fd["widget"] = wd
        result["fields"].append(fd)
    return result


def main() -> int:
    args = parse_args()
    form_id: str = args.form_id

    output_dir = FORMTYPES_DIR / form_id
    pages_dir = output_dir / "pages"

    if output_dir.exists() and not args.overwrite:
        print(f"ERROR: {output_dir} already exists. Use --overwrite to replace.", file=sys.stderr)
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)
    pages_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating formtype for {form_id}:")

    # Step 1: Fetch/copy the PDF
    pdf_path = fetch_pdf(args.input, output_dir)
    sha256 = compute_sha256(pdf_path)
    print(f"  SHA-256: {sha256}")

    # Step 2: Extract SVG pages
    page_count, page_width, page_height = extract_svg_pages(pdf_path, pages_dir)
    print(f"  Page size: {page_width} × {page_height} pt ({page_count} pages)")

    # Step 3: Detect field candidates (optional)
    fields: list[FieldCandidate] = []
    if args.detect_fields:
        fields = detect_field_rectangles(pdf_path, page_width, page_height)

    # Step 4: Write formtype.json
    formtype = FormTypeSchema(
        form_id=form_id,
        page_width=page_width,
        page_height=page_height,
        fields=fields,
    )
    formtype_path = output_dir / "formtype.json"
    formtype_path.write_text(json.dumps(serialize_formtype(formtype), indent=2) + "\n")
    print(f"  Wrote {formtype_path.name} ({len(fields)} fields)")

    # Step 5: Write metadata.json
    source_url = args.input if args.input.startswith(("http://", "https://")) else "file://" + args.input
    metadata = MetadataSchema(
        form_id=form_id,
        title=args.title or form_id,
        official_source=source_url,
        sha256=sha256,
        page_width_pt=page_width,
        page_height_pt=page_height,
        page_count=page_count,
    )
    metadata_path = output_dir / "metadata.json"
    metadata_path.write_text(json.dumps(asdict(metadata), indent=2) + "\n")
    print(f"  Wrote {metadata_path.name}")

    # Step 6: Clean up downloaded source PDF (not needed in output)
    pdf_path.unlink(missing_ok=True)

    print(f"\n✅ Done. Output: {output_dir}/")
    print(f"   formtype.json — {'DRAFT with detected fields' if fields else 'EMPTY (add fields manually)'}")
    print(f"   metadata.json — source provenance")
    print(f"   pages/        — {page_count} SVG page shells")
    if fields:
        print(f"\n⚠️  Field keys are placeholder names (_field_NNN). Rename them to match")
        print(f"   BIR field identifiers before committing (e.g. frm2551Qv2018:txtTIN1).")

    return 0


if __name__ == "__main__":
    sys.exit(main())
